### ISSUE TITLE
Lentisphaerae genomes are incorrectly classified

### ISSUE THREAD

**Issue by fplaza** [Ecogenomics/GTDBTk#100]
Hi,

First of all, thank you very much for developping this tool.

I tried to classify the genome of _Victivallis vadensis_ strain DSM 14823 with GTDBTk

```
mkdir tmp
cd tmp
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/096/415/GCA_003096415.1_ASM309641v1/GCA_003096415.1_ASM309641v1_genomic.fna.gz
gzip -d GCA_003096415.1_ASM309641v1_genomic.fna.gz
~/miniconda2/bin/conda run gtdbtk classify_wf --genome_dir . --out_dir .
user_genome     classification  fastani_reference       fastani_taxonomy        fastani_ani     fastani_af      closest_placement_reference     closest_placement_taxonomy      closest_placement_ani   closest_placement_af    classification_method        note    other_related_references(genome_id,species_name,ANI,AF)
GCA_003096415.1_ASM309641v1_genomic     d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__UBA1784;f__UBA1784;g__UBA11493;s__ UBA11493        d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__UBA1784;f__UBA1784;g__UBA11493;s__ 79.90.32     None    None    None    None    taxonomic novelty determined using RED  None    None
```

As you can see, the genome is classified as _d__Bacteria;p__Verrucomicrobiota;c__Lentisphaeria;o__UBA1784;f__UBA1784;g__UBA11493;s__ UBA11493_
but the correct annotation is
_d__Bacteria;p__Lentisphaerae;c__Lentisphaeria;o__Victivallales;f__Victivallaceae;g__Victivallis;s__Victivallis_vadensis_

Could you fix this?

**Comment by dparks1134** [comment]
Hello. GTDB-Tk follows the GTDB taxonomy. The next release of the GTDB, r89, will have taxon names that reflect the new species Victivallis vadensis.

**Comment by fplaza** [comment]
Thanks for the clarification.
I am looking forward to testing this new release.
