### ISSUE TITLE
md5sums for gtdbtk database?

### ISSUE THREAD

**Issue by astrophys** [Ecogenomics/GTDBTk#103]
I'm following the pip instructions, which suggest downloading the data from https://data.ace.uq.edu.au/public/gtdbtk/.  I downloaded the data from https://data.ace.uq.edu.au/public/gtdbtk/release_86/, but there are no hash sums to check if the download was successful.

Could you please provide md5sum (or some other common hash sum) so I can ensure data integrity.  At my institution, I've had difficulty downloading large files in the past.

**Comment by pchaumeil** [comment]
Hello,
Thanks for your Email,
A md5sum file has been added to the gtdbtk repository ( https://data.ace.uq.edu.au/public/gtdbtk/release_86/gtdbtk.r86_v2_data.tar.gz.md5 )

Thanks,
Pierre

**Comment by astrophys** [comment]
Thanks!
