### ISSUE TITLE
phylum name in GTDBTK

### ISSUE THREAD

**Issue by ucassee** [Ecogenomics/GTDBTk#106]
Hi developer！
       I wonder whether the phylum name in GTDBTK is the same as SILVA. I find Chloroflexota and Gemmatimonadota in the  GTDBTK classification. So are these the same as Chloroflexi and Gemmatimonadetes ?
Best regards.

**Comment by dparks1134** [comment]
GTDB-Tk uses the GTDB taxonomy  (http://gtdb.ecogenomic.org/). This taxonomy is very similar, but not identical to SILVA. In many cases the GTDB taxonomy more strictly follows the nomenclatural rules for rank suffixes which is why there is Chloroflexota instead of Chloroflexi.

**Comment by ucassee** [comment]
Hi @dparks1134 ,
     I found  the taxonomy of some bins is a little bit different in gtdbtk.bac120.summary.tsv and gtdbtk.bac120.classification_pplacer.tsv.  I wonder what is the taxonomic differences  between these two file?  Thanks for your help!

**Comment by dparks1134** [comment]
Hello. Please take a look at the information at:
https://github.com/Ecogenomics/GTDBTk

If you are still unclear why these files differ, please let me know so we can clarify the documentation.

**Comment by ucassee** [comment]
Hi @dparks1134 , 
       I feel  sorry for not reading that information carefully. I know the differences between the two file now.
       But I still unclear about the naming rule. Could you give me more information. Because  your phylum names  are really different with silva and ncbi.

**Comment by dparks1134** [comment]
Hello. The phylum names follow a recent proposal to include this rank in the  International Code of Nomenclature of Prokaryotes:
https://www.ncbi.nlm.nih.gov/pubmed/29458499

You can also find information in the GTDB manuscript and references within:
https://www.ncbi.nlm.nih.gov/pubmed/30148503

You might also find the following blog post insightful:
https://help.ezbiocloud.net/bacterial-nomenclature-101-and-how-to-describe-new-species/

**Comment by ucassee** [comment]
Hi @dparks1134 ,
       Thanks for your reply.  
        The naming rule is really chaos now. I hope the proposal will be approved and accepted in  the near future.
