### ISSUE TITLE
Uncaught exception: Failure

### ISSUE THREAD

**Issue by Tahsin-Khan** [Ecogenomics/GTDBTk#113]
Hello,

I am very new to bioinformatics. I have assembled quite a few bins from my metagenomic datasets. I want to classify them using GTDB-Tk. But I have been facing the problem below while placing my genomes into a tree with pplacer.  

"Uncaught exception: Failure("Sequence dp_h_bin_47 doesn't overlap any reference sequences."
Fatal error: exception Failure("Sequence dp_h_bin_47 doesn't overlap any reference sequences.")
Uncaught exception: Sys_error("1_classify/pplacer/pplacer.bac120.json: No such file or directory")
Fatal error: exception Sys_error("1_classify/pplacer/pplacer.bac120.json: No such file or directory")
GTDB-Tk has stopped before finishing
[Errno 2] No such file or directory: '1_classify/gtdbtk.bac120.classify.tree'
('Unexpected error:', <type 'exceptions.IOError'>)

How can I overcome this problem?
Thanks in advance.

**Comment by pchaumeil** [comment]
Hello, 
Could you please provide the version of GTDB-Tk you are using?
This error occurs when at least one of the bin (  in this case dp_h_bin_47 ) does not have any AA in the MSA file. Setting the --min_perc_aa flag to a value greater than 0% should filter out this sequence and finish the analysis.

Regards,
Pierre

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
