### ISSUE TITLE
restart when interrupted mid workflow?

### ISSUE THREAD

**Issue by b-tierney** [Ecogenomics/GTDBTk#118]
Was running the prodigal step classify_wf for a large number of genomes and ran out of space on my harddrive. I'd rather not have to redo the progress I'd already made (had taken a few days) – is there anyway to restart when interrupted?

**Comment by dparks1134** [comment]
Hello. Are you running GTDB-Tk with multiple CPUs/processes? The Prodigal step makes good use of multiple processors. It should only take 15-60 seconds per genome per CPU. So roughly 30 minutes per 1000 genomes if you have 32 CPUs.

**Comment by b-tierney** [comment]
Hi,
Thanks for the response – I am using multithreading, but I'm doing a few hundred thousand  genomes with 16 cores, and I'm just impatient. I just decided to bite the bullet and redo it. You're right it's amazingly fast! Already surpassed where we were before.

Love this software by the way, thanks so much for the amazing work.

**Comment by b-tierney** [comment]
###

**Comment by aaronmussig** [comment]
Hello,
Thanks for your feedback, I agree that this would be very useful to have given the amount of time spent on large inputs. This is something we will look into for a future release.

It may not be ideal, but in the meantime you may wish to run GTDB-Tk using a small subset of your 220K genomes. You will still be able to obtain a taxonomy, however, they will not all be placed into the same tree.

**Comment by b-tierney** [comment]
Thanks! Yeah in the meantime I just did everything in small batches. Really appreciate the help.
