### ISSUE TITLE
ImportError: No module named gtdblib.trimming

### ISSUE THREAD

**Issue by biofuture** [Ecogenomics/GtdbTk#12]
Hi, 

I have installed all the prerequisite packages and softwares and then used pip to install the tgdbtk.  But while I run gtdbtk, it cannot find the gtdblib.trimming.  The lib directory for gtdbtk is list here. What's wrong with my installation?

Thanks for your help.

ls /usr/local/lib/python2.7/dist-packages/gtdbtk -lh
-rw-r--r-- 1 root root  33K Aug 17 06:38 classify.py
-rw-r--r-- 1 root root  23K Oct  7 23:18 classify.pyc
drwxr-sr-x 2 root root 4.0K Oct  7 23:18 config
drwxr-sr-x 2 root root 4.0K Oct  7 23:18 external
-rw-r--r-- 1 root root 1.5K Aug 23 04:22 __init__.py
-rw-r--r-- 1 root root  503 Oct  7 23:18 __init__.pyc
-rw-r--r-- 1 root root 9.4K Aug 23 04:27 main.py
-rw-r--r-- 1 root root 6.4K Oct  7 23:18 main.pyc
-rw-r--r-- 1 root root  25K Aug 17 06:38 markers.py
-rw-r--r-- 1 root root  14K Oct  7 23:18 markers.pyc
-rw-r--r-- 1 root root  34K Aug 23 02:27 relative_distance.py
-rw-r--r-- 1 root root  23K Oct  7 23:18 relative_distance.pyc
-rw-r--r-- 1 root root 5.8K Mar 29  2017 reroot_tree.py
-rw-r--r-- 1 root root 3.8K Oct  7 23:18 reroot_tree.pyc
-rw-r--r-- 1 root root 4.0K Aug 17 06:38 tools.py
-rw-r--r-- 1 root root 4.6K Oct  7 23:18 tools.pyc
-rw-r--r-- 1 root root   24 Aug 23 04:20 VERSION

**Comment by biofuture** [comment]
Thanks for your help.

**Comment by pchaumeil** [comment]
Dear Xiaotao,

Thank you for your Email,

Unfortunately, We are still actively developing GtdbTk so it will not be able for external user for another month or two.

Most of the function are here but they need to be tested.



Also the final Taxonomy used for GtdbTk is still in a curation phase so you will not get our final results for your analysis.



We will post notifications about Gtdbtk releases through our Twitter account (https://twitter.com/ace_uq).



Regards,

Pierre
