### ISSUE TITLE
how to use --outgroup_taxa in de_novo_wf

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#120]
I tried to run the de novo workflow on the bacterial marker set without filtering and I specified "k__Archaea" as the outgroup, but clearly that was not its intended use, given the following errors:

```
[2019-05-07 18:40:06] WARNING: Tree rooting is still under development!
[2019-05-07 18:40:06] INFO: Identifying genomes from the specified outgroup.
[2019-05-07 18:40:10] INFO: Identified 0 outgroup taxa in the tree.
[2019-05-07 18:40:10] INFO: Identified 21264 ingroup taxa in the tree.
[2019-05-07 18:40:10] WARNING: No outgroup taxa identified in the tree.
[2019-05-07 18:40:10] WARNING: Tree was not rerooted.

Controlled exit resulting from an unrecoverable error or warning.
```

If inferring a tree for the entire bacterial kingdom then what should my outgroup taxa be?

In addition, when would I really need to use the de novo workflow?  Will novel species under the classify workflow be given new species names based on the GTDB naming or will it just give me a tree with my user genomes phylogenetically placed on the GTDB tree?

**Comment by dparks1134** [comment]
Hello,

The de novo workflow is still in development so your mileage may vary. In particular, the `decorate ` step has not been implemented yet.

That said, the GTDB-Tk bacterial tree contains only Bacteria so the outgroup should be a bacterial phyla. I generally root on p__Chloroflexota as it is a stable monophyletic group and then just indicate the tree should be treated as unrooted if displaying the tree in publications. A phylum-level outgroup is required when decorating a tree, but as I indicated this isn't implemented yet.

The primary purpose of the GTDB-Tk is certainly the classify workflow. This provides a GTDB-Tk taxonomy string for all query genomes. If a genome is a novel species/genus/family/etc., GTDB-Tk does not propose a taxon name. We leave the fun part to you. :)

**Comment by cheberling** [comment]
Great, thanks!
