### ISSUE TITLE
download file path messed up

### ISSUE THREAD

**Issue by sipesk** [Ecogenomics/GTDBTk#122]
Hello,

I downloaded GTDBTK and messed something up as when I type the command $ gtdbtk -h

the program cannot find itself in my home directory :

python: can't open file '/home/lloydlab/home/lloydlab/GTDBTK-stable/bin/gtdbtk': [Errno 2] No such file or directory

in the file, it expects it to be in /home/lloydlab/home/lloydlab ... 

How do I change this to take out the repetition?

Thanks,
Katie

**Comment by pchaumeil** [comment]
Hello Katie,
I will need a bit more information to understand what is happening here.

How did you install GTDB-Tk ? did you use pip or did you download the package straight from github? Have you modified your .bashrc file to be able to run GTDB-Tk?

Also, where you mention  "in the file, it expects it to be in /home/lloydlab/home/lloydlab ", which file do you mean? 

Thanks, 
Pierre

**Comment by sipesk** [comment]
Hey Pierre,

I have no idea how, but I fixed it and it seems to be working swimmingly !

Cheers,
Katie
________________________________

**Comment by pchaumeil** [comment]
Glad to hear you have resolved the issue. Thank you for letting us know.
