### ISSUE TITLE
questions for de_novo workflow

### ISSUE THREAD

**Issue by eranbio** [Ecogenomics/GTDBTk#123]
I am trying to run the de_novo workflow (gtdbtk version 0.2.2) with my genomes (plus the gtdb genomes). I get the following warnings:
[2019-05-13 12:23:29] WARNING: Tree rooting is still under development!
[2019-05-13 12:23:29] INFO: Identifying genomes from the specified outgroup.
[2019-05-13 12:23:31] INFO: Identified 0 outgroup taxa in the tree.
[2019-05-13 12:23:31] INFO: Identified 17418 ingroup taxa in the tree.
[2019-05-13 12:23:31] WARNING: No outgroup taxa identified in the tree.
[2019-05-13 12:23:31] WARNING: Tree was not rerooted.

I do provide outgroup taxa despite the message. The program is then terminated without rooting and decorating. are the outgroup and decorate steps still under development? 
My ultimate goal is to run de_novo workflow in order to add my private genomes to the tree and then to use the unified new tree (and associated files) as the baseline for future classifications using the classify workflow. Is this basically possible in the current version?

**Comment by pchaumeil** [comment]
Hello,

Which group are you using as an outgroup? Is this group in the GTDB-Tk taxonomy?
The de novo workflow is still in development. In particular, the decorate step has not been implemented yet.

Currently, changing the reference tree for the classify function is not possible without changing all metadata files used to run GTDB-Tk ( masks, msa, species radii, RED value references.....) and provided in the data package.

Regards,
Pierre

**Comment by eranbio** [comment]
Hi Pierre, 
Thanks for answering. The outgroup I am currently using is d__Archaea (which if I understand correctly is in the gtdb tree), while all my added genomes are bacterial.
Best,
Eran

**Comment by pchaumeil** [comment]
Hello Eran,
When using the bac120 flag in the de_novo workflow , the genomes will automatically be added the the bacterial reference MSA and the tree will only contain Bacteria and no Archaea . I suggest rooting the tree with one of the bacterial phylum (i.e. Chloroflexota).

Regards,
Pierre

**Comment by eranbio** [comment]
Thanks Pierre!
