### ISSUE TITLE
How can I use the alternative mask files stored in the 'masks' directory of reference data package?

### ISSUE THREAD

**Issue by ilnamkang** [Ecogenomics/GTDBTk#125]
Hi,

(This issue is related to my previous issue  https://github.com/Ecogenomics/GTDBTk/issues/35)

I'd like to insert my genomes into the GTDB ARB tree, which requires alignment of my genomes that has the same length as genomes in the GTDB ARB file.

Fortunately, it seems that the 'masks' directory of reference data package already have two mask files that can produce alignment compatible with GTDB Arb file. The file names are 'bac120_msa_mask_r86_from_gtdb.txt' and 'ar122_msa_mask_r86_from_gtdb.txt'.

But, I cannot find how to use these mask files, instead of default ones, by applying option(s) in command line. I know I can edit 'config.py' file in the install directory to do this. But, I'd like to get ARB-compatible alignment without editing the 'config.py' file because it requires sudo.

Thanks.

**Comment by pchaumeil** [comment]
Hello,
It is currently not possible to use another mask without modifying the config.py.
We will add this option in the next release of GTDB-Tk

Regards,
Pierre

**Comment by ilnamkang** [comment]
Thank you for a quick reply.

Best regards,
Ilnam
