### ISSUE TITLE
Conda update leads to: No such file or directory: metadata.txt error

### ISSUE THREAD

**Issue by Somebodyatthdoor** [Ecogenomics/GTDBTk#126]
Hi,

I have just updated my gtdb-tk conda package and I am now getting an error when I try and run any gtdb-tk commands. The error is:

"File "/exports/groups/grp/software/anaconda/gtdb2_env/lib/python2.7/site-packages/gtdbtk/config/config.py", line 30, in <module>
    with open(os.path.join(METADATA_DIR, "metadata.txt")) as metadataData:
IOError: [Errno 2] No such file or directory: '/exports/groups/grp/software/anaconda/gtdb2_env/share/gtdbtk-0.2.2/db/metadata/metadata.txt'

Do you have any suggestions for what might be causing this? It did not occur prior to updating the package. I have also tried reinstalling the package and get the same error. 

Thanks

**Comment by pchaumeil** [comment]
Hello,
Is _/exports/groups/grp/software/anaconda/gtdb2_env/share/gtdbtk-0.2.2/db/_ the right path where all GTDB-Tk metadata files are stored?

If no, make sure that the GTDBTK_DATA_PATH variable is pointing to the parent directory of the metadata folder. 
`env | grep GTDB`     
should return:    
`GTDBTK_DATA_PATH=path/to/data/gtdbtk/reference/data/directory/`    
( check https://github.com/Ecogenomics/GTDBTk#pip-installation for more information)

Regards,
Pierre

**Comment by Somebodyatthdoor** [comment]
Hi, thanks for the response.

I think the metadata files should be stored in that location, but they aren't. The only things listed as being present are:

fastani  gtdbtk.r86_v2_data.tar.gz.1

If I run:
env | grep GTDB

It returns:
GTDBTK_DATA_PATH=/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/gtdb2_env/share/gtdbtk-0.2.2/db/

Thanks,
Laura

**Comment by pchaumeil** [comment]
Hello Laura,
Have you managed to resolve your problem by updating the GTDBTK_DATA_PATH variable?

Regards,
Pierre

**Comment by Somebodyatthdoor** [comment]
Hi,

Yes , thanks. It's all fixed.

Cheers,
Laura

**Comment by pchaumeil** [comment]
Perfect!
