### ISSUE TITLE
No species classification due to incongruent assignment in v0.2.1

### ISSUE THREAD

**Issue by alexmsalmeida** [Ecogenomics/GTDBTk#129]
Hi,

Was running the toolkit on a set of genomes and in the case of an E. coli sequence (https://www.patricbrc.org/view/Genome/562.29099) I wasn't able to get a species classification seemingly because of an incongruent assignment between the ANI and the tree placement. However, all the pplacer results are labeled as N/A, so I can't really figure out why this is. Furthermore, I was under the impression that starting from v0.2.1 species assignment would solely rely on the ANI results. Should I just be using the fastani_taxonomy column instead then? Find below the output results for this genome:

| user_genome | classification | fastani_reference | fastani_reference_radius | fastani_taxonomy | fastani_ani | fastani_af | closest_placement_reference | closest_placement_taxonomy | closest_placement_ani | closest_placement_af | classification_method | note | other_related_references(genome_id,species_name,radius,ANI,AF) | aa_percent | red_value | warnings |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Ecoli-sequence | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__ | GCF_000005845.2 | 95.0 | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__Escherichia coli | 97.09 | 0.79 | N/A | N/A | N/A | N/A | ANI/Placement | topological placement and ANI have incongruent species assignments | GCF_002133425.1, s__Escherichia coli_B, 95.0, 96.1, 0.83; GCF_001912385.1, s__Escherichia coli_A, 95.0, 96.06, 0.85; GCF_000407925.1, s__Escherichia sp2, 95.0, 92.59, 0.75; GCF_001660175.1, s__, 95.0, 91.75, 0.75; GCF_000350705.1, s__Escherichia sp1, 95.0, 91.16, 0.74; GCF_000190495.1, s__Escherichia fergusonii, 95.0, 91.14, 0.65; GCF_001549955.1, s__Escherichia albertii, 95.0, 90.13, 0.73 | N/A | N/A | N/A |

Many thanks in advance for your help.

Best,
Alex

**Comment by pchaumeil** [comment]
Hello Alex,
I would recommend updating GTDB-Tk to v0.2.2.
This version fixes few minor issues regarding the classification steps (including the species assignment based on ANI results).

Regards,
Pierre

**Comment by alexmsalmeida** [comment]
Updated to 0.2.2 and that solved the issue. Thanks a lot for the help.

Alex

**Comment by alexmsalmeida** [comment]
Apologies, but I tried running the new GTDBTK v0.3.0 and seem to be getting the same issue for the E.coli genome mentioned above (https://www.patricbrc.org/view/Genome/562.29099). Find below the results. 

| user_genome | classification | fastani_reference | fastani_reference_radius | fastani_taxonomy | fastani_ani | fastani_af | closest_placement_reference | closest_placement_taxonomy | closest_placement_ani | closest_placement_af | classification_method | note | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  --- | --- | 
| Ecoli.genome | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__ | GCF_000026325.1 | 96.94 |	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__Escherichia coli_D | 97.37 | 0.86 | N/A | N/A | N/A | N/A | ANI/Placement |	topological placement and ANI have incongruent species assignments |

The ANI is quite high (97.37%) but I still do not get it assigned at the species level because of an incongruent assignment (but no indication as to why). Should I just take the fastANI classification which assigns it to s__Escherichia coli_D?

Thanks in advance for the help.

Best,
Alex

**Comment by dparks1134** [comment]
Hello Alex. This is a judgement call we are currently leaving to researchers. Based on ANI the genome is highly similar to E. coli_D. However, the maximum-likelihood placement of this genome in the reference tree via pplacer does not agree with this classification. If you wish to use ANI as the defining criteria for circumscribing species than go with E. coli_D. If you believe species must be monophyletic than you need to explore further since monophyly doesn't hold for the ML placement. Of course, the genome may be monophyletic in a de novo tree or a tree inferred with a different model, marker set, genome set, etc.

**Comment by alexmsalmeida** [comment]
Hi Donovan,

Many thanks for the swift reply. Yeah, I think I will go with the ANI classification. The genome is supposed to be an E.coli (all the E.coli genomes I am dealing with are clustering together at 95% ANI and this is one "representative"), so this was sort of my control experiment. Just wanted to make sure there wasn't something wrong with the analysis itself.

Thanks again,
Alex

**Comment by dparks1134** [comment]
Hello Alex. Just wanted to let you know that we released v0.3.1 of GTDB-Tk. This version will report the ANI species classification even when it is not congruent with the pplacer placement. We've made this change since it is inline with how we are defining species in the GTDB and believe it is the classification most user will expect.
