### ISSUE TITLE
Flag to allow genomes to be supplied as called genes

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBTk#13]
It would be good if users could supply genomes as called genes in amino acid space. Basically just a flag (--genes) to indicate the FASTA file contains genes and then Prodigal can be skipped. This isn't critical, but can be useful if you have already called genes and want to make sure these exact genes are being used.

**Comment by danfulop** [comment]
👍 +1

**Comment by jianshu93** [comment]
I agree with this idea. And it looks like not all gene prediction tool behave the same. FragGeneScan could also be used as the prediction step.

https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btab827/6454948?rss=1#

Jianshu
