### ISSUE TITLE
FastANI error: skch::validateInputFiles, Could not open /release86/fastani/database/GCF_000024185.1_genomic.fna.gz

### ISSUE THREAD

**Issue by jasmineliang** [Ecogenomics/GTDBTk#130]
Hello,

I tested my GTDBTk installation by running "gtdbtk test --out_dir test1", and I ran into the error "FastANI has stopped:
ERROR, skch::validateInputFiles, Could not open /sdc/Project/tengwk/liangjl/release86/fastani/database/GCF_000024185.1_genomic.fna.gz". It appears that some genomes used in the deco_fitted.tree file (/release86/pplacer/gtdb_r86_bac120.refpkg) are not in the folder (/release86/fastani/database/), which caused the error. I used the file "gtdbtk.r86_v2_data.tar.gz" and md5 was correct. How to solve this problem? Thanks for your reply!

The logs are listed below:
INFO: GTDB-Tk v0.2.2
INFO: gtdbtk test --out_dir test2
WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
Command:
gtdbtk classify_wf --genome_dir test2/genomes --out_dir test2/output --cpus 1
INFO: GTDB-Tk v0.2.2
INFO: gtdbtk classify_wf --genome_dir test2/genomes --out_dir test2/output --cpus 1
WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
INFO: Identifying markers in 3 genomes with 1 threads.
INFO: Running Prodigal to identify genes.
==> Finished processing 3 of 3 (100.0%) genomes.
INFO: Identifying TIGRFAM protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
INFO: Identifying Pfam protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
INFO: Done.
INFO: Aligning markers in 3 genomes with 1 threads.
INFO: Processing 3 genomes identified as archaeal.
INFO: Read concatenated alignment for 845 GTDB genomes.
INFO: Masking columns of multiple sequence alignment using canonical mask.
INFO: Masked alignment from 32675 to 5024 AA.
INFO: 0 user genomes have amino acids in <10.0% of columns in filtered MSA.
INFO: Creating concatenated alignment for 848 GTDB and user genomes.
INFO: Creating concatenated alignment for 3 user genomes.
INFO: Done.
INFO: Placing 3 archaeal genomes into reference tree with pplacer (be patient).
FastANI has stopped:
ERROR, skch::validateInputFiles, Could not open /sdc/Project/tengwk/liangjl/release86/fastani/database/GCF_000024185.1_genomic.fna.gz
GTDB-Tk has stopped before finishing
Stop!!
('Unexpected error:', <type 'exceptions.ValueError'>)
Traceback (most recent call last):
  File "/sdc/Project/tengwk/gaoshaom/miniconda3/envs/python27/bin/gtdbtk", line 408, in <module>
    gt_parser.parse_options(args)
  File "/sdc/Project/tengwk/gaoshaom/miniconda3/envs/python27/lib/python2.7/site-packages/gtdbtk/main.py", line 401, in parse_options
    self.classify(options)
  File "/sdc/Project/tengwk/gaoshaom/miniconda3/envs/python27/lib/python2.7/site-packages/gtdbtk/main.py", line 296, in classify
    options.debug)
  File "/sdc/Project/tengwk/gaoshaom/miniconda3/envs/python27/lib/python2.7/site-packages/gtdbtk/classify.py", line 365, in run
    raise ValueError("Stop!!")
ValueError: Stop!!
INFO: Test has successfully finished.

**Comment by pchaumeil** [comment]
Hello, 
It seems GCF_000024185.1_genomic.fna.gz is in both gtdbtk.r86_v2_data.tar.gz and gtdbtk.r86_v3_data.tar.gz in [the GTDB-Tk repository](https://data.ace.uq.edu.au/public/gtdbtk/release_86/).

` tar -tvf gtdbtk.r86_v2_data.tar.gz | grep GCF_000024185.1`
returns 
`release86/fastani/database/GCF_000024185.1_genomic.fna.gz
`
There may have been an issue during the extraction of the genomes from the tar.gz file.

Also, I would recommend updating the data to gtdbtk.r86_v3_data.tar.gz.

Regards,
Pierre

**Comment by jasmineliang** [comment]
Hello Pierre,
 I updated the data to gtdbtk.r86_v3_data.tar.gz and it worked. Thanks again.

Regards,
Jasmine
