### ISSUE TITLE
Remove refusal of RS_, GB_, and UBA genome IDs

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/GTDBTk#131]
Currently, the GTDB-Tk will not accept user genomes that start with RS_, GB_, or UBA. This is to ensure that user genomes have unique names relative to the GTDB-Tk reference genomes. It would be better if we just explicitly checked for a conflict, but otherwise accepted any user genome IDs. It is possible and reasonable, that users will have genomes they have called UBAxxx since this is the common ID for these genomes. This approach will also be problematic if we move to a Gxxx type reference ID system.

**Comment by aaronmussig** [comment]
A possible workaround to this would be appending a GTDB-Tk prefix to all reference genomes (e.g. GTDBTKREF_UBA1234, GTDBTKREF_Gxxx) and remove this prefix when outputting results.

Alternatively, if a user genome is found to have a non-unique ID we could ignore it in the pipeline and output a warning.

**Comment by dparks1134** [comment]
My preference would be to create a list of reference GTDB-Tk IDs and check for conflicts with the User genomes. Any conflicts can be reported to the user and the program terminated (i.e. this is an unresolvable error the user must address).

**Comment by pchaumeil** [comment]
Implemented in ec31c86
