### ISSUE TITLE
fastani is not on the system path

### ISSUE THREAD

**Issue by zyyalice** [Ecogenomics/GtdbTk#15]
Hi
I have installed this software toolkit of GTDB-Tk following the direction, but when I ran “gtdbtk classify wf”, it showed error messages as below:

INFO: GTDB-TK v0.0.4b1
INFO: gtdbtk classify_wf --cpus 24 --genome_dir my_genomes --out_dir gtdbtk_output
WARNING: Results are still being validated and taxonomic assigmnts may be incorrect!Use at your own risk!
fastani is not on the system path.
controled exit resulting from an unrecoverable error or warning.

I have tried my best to solve the problem, but this error still exists . Could you give me some suggestions about how I should fix this?

Thanks a lot.
Looking forward to your reply.
Regards,
Alice

**Comment by pchaumeil** [comment]
Hi Alice,
The fastani dependency should be resolved in the new gtdbtk version 0.0.4b2
https://pypi.python.org/pypi/gtdbtk/0.0.4b2

Please update gtdbtk and let me know if the problem persists.

Thanks,
Pierre

**Comment by zyyalice** [comment]
Hi Pierre
thanks for your reply.
I have tried this new gtdbtk version 0.04b2, but the problem still exists.

INFO: GTDB-TK v0.0.4b2
INFO: gtdbtk classify_wf --cpus 24 --genome_dir my_genomes --out_dir gtdbtk_output
WARNING: Results are still being validated and taxonomic assigmnts may be incorrect! Use at your own risk!
fastani is not on the system path.
controlLed exit resulting from an unrecoverable error or warning.

**Comment by pchaumeil** [comment]
Hi Alice, 
I think I have found the issue.
Would you mind trying again with version 0.04b3.

Thanks,
Pierre

**Comment by zyyalice** [comment]
Hi Pierre
I am very glad to tell you, it seems you solved the problem. Well done! Thank you!
but the bad news is it seems there is another problem. The error message is:

[2018-03-08 13:50:52] INFO: GTDB-Tk v0.0.4b3
[2018-03-08 13:50:52] INFO: gtdbtk classify_wf --cpus 24 --genome_dir my_genome --out_dir output
[2018-03-08 13:50:52] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2018-03-08 13:50:52] INFO: Identifying markers in 4 genomes with 24 threads.
[2018-03-08 13:50:52] INFO: Running Prodigal to identify genes.
==> Finished processing 4 of 4 (100.0%) genomes.
[2018-03-08 13:51:26] INFO: Identifying TIGRFAM protein families.
==> Finished processing 4 of 4 (100.0%) genomes.
[2018-03-08 13:51:32] INFO: Identifying Pfam protein families.
Can't locate Moose.pm in @INC (you may need to install the Moose module).
 
But i have already installed the "Moose module", so how should i solve the problem? Thank you~

Thanks,
Alice

**Comment by pchaumeil** [comment]
Hi Alice,
This is more a Perl issue.
Have you installed Moose module as root? 

You need to make sure that the folder where Moose.pm is located is part the @INC variable.
If it's not , you can set the PERL5LIB ( or PERLIB) environment variable the same way you set PATH environment variable. Every directory listed in this variable will be added to @INC.

i.e:
export PERL5LIB=/path/to/moose/directory

Cheers,
Pierre

**Comment by zyyalice** [comment]
Hi Pierre,
After your great, patient and consistent help, i am glad to tell you that it worked out. 
Thank you very much! You are really helpful!

Thank you again,
Alice

**Comment by snayfach** [comment]
I've encountered the same issue. Would you add this to the installation instructions?

Thanks,
Stephen

**Comment by snayfach** [comment]
I just cloned the latest version of the software and got the fastani error:

```
$ gtdbtk classify --genome_dir genomes --align_dir ./ --out_dir ./
[2018-03-15 17:34:21] INFO: GTDB-Tk v0.0.3
[2018-03-15 17:34:21] INFO: gtdbtk classify --genome_dir genomes --align_dir ./ --out_dir ./
[2018-03-15 17:34:21] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
fastani is not on the system path.

Controlled exit resulting from an unrecoverable error or warning.
```

This is because the downloaded binary is called `fastANI` not `fastani`. Renaming the binary solved the issue

**Comment by pchaumeil** [comment]
Hi Stephen,
Thanks for your feedback.
I have added an installation note to inform that Moose and IPC::Run modules are required. 

the fastANI/fastani issue and few other bugs have been fixed in the latest version of gtdbtk (0.0.5) .

Cheers,
Pierre

**Comment by Uzunmasha** [comment]
Hi!
I'm installed the latest release and tried very hard to figure out how to connect fast ANI, but I have the same error:
 INFO: GTDB-Tk v0.1.3
INFO: gtdbtk classify_wf --genome_dir /home/user1/gtdbtk --out_dir /home/user1/gtdbtk/gtdbtk_result/
WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
fastANI is not on the system path.

Controlled exit resulting from an unrecoverable error or warning.

Can you help me solve the problem?
Thanks,
Maria

**Comment by dparks1134** [comment]
Hello Maria. I'd suggest making sure FastANI works independent of GTDB-Tk. If you type "fastANI -h" on your command line does it bring up the help menu for FastANI? If not, than it is not yet on your system path.

**Comment by ssun6** [comment]
Hi, I installed the latest gtdbtk today and had the same issue while FastANI works okay independently on command line. I couldn't figure out what is happening. Any suggestions? Thank you!
Shan
