### ISSUE TITLE
running the identify step: string index out of range

### ISSUE THREAD

**Issue by zhongwang** [Ecogenomics/GTDBTk#156]
Hi,

Zhong Wang from JGI again. I also got a different failure on a different dataset (gtdbtk classify_wf), here are the error message:

[2019-07-09 22:59:41] INFO: Identifying markers in 376 genomes with 16 threads.
[2019-07-09 22:59:41] INFO: Running Prodigal to identify genes.
==> Finished processing 376 of 376 (100.0%) genomes.
[2019-07-09 23:08:43] INFO: Identifying TIGRFAM protein families.
==> Finished processing 376 of 376 (100.0%) genomes.
[2019-07-09 23:11:09] INFO: Identifying Pfam protein families.
==> Finished processing 376 of 376 (100.0%) genomes.
[2019-07-09 23:11:41] ERROR: There was an error while running the identify step: string index out of range

Uncontrolled exit resulting from an unexpected error.

====================================================================================================
EXCEPTION: IndexError
  MESSAGE: string index out of range
____________________________________________________________________________________________________

====================================================================================================

Appreciate your help!
Best,
Zhong

**Comment by dparks1134** [comment]
Hello Zhong,

Can you verify that you are running GTDB-Tk v0.3.0 or later?

We haven't run into this issue. Any chance one or more of your genomes contain a sequence with zero nucleotides? I think for us to debug this you will need to send us your set of genomes. If you can narrow it down to just a subset of genomes (ideally one!) that produces that issue that would be helpful though we can take a look using the entire set if you are able to share it.

Cheers,
Donovan

**Comment by zhongwang** [comment]
Hi Donovan,

I can verify that I am running the latest, v0.3.1. I also double checked all the 370 genome bins, they are at least 200kb, and no illegal characters. 

I will divide the set into small groups and see if I can narrow down.

Thanks,
Zhong

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
