### ISSUE TITLE
pplacer hangs if more than 83 cpu

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [Ecogenomics/GTDBTk#163]
Hello,
Just to say that while running the gtdbtk test, I got pplacer hanging if number of cpu > 83. So just hanging, with around 8 process in S+ state. It's not memory issue. I'm not sure where it come from or if this is reproductible on other installations. Just wanted to let you know.

**Comment by pchaumeil** [comment]
Hello Sebastien,
Thanks for your Email!
We actually did notice a similar behaviour on our server using 96 cpus but could not fix the problem.

We are currently working on reformatting the pplacer step so hopefully this problem won't occur in the future
