### ISSUE TITLE
viewing phylogenetic tree

### ISSUE THREAD

**Issue by jeagull** [Ecogenomics/GTDBTk#165]
Hi, I'm a noob in bioinformatics and gtdbtk.
I have an output file from gtdbtk and I want to create a phylogenetic tree and I heard I can do that from one of the output files but I dont have a clue how. Can somebody illuminate me please? Here is a list of my output:
![スクリーンショット 2019-07-19 12 57 24](https://user-images.githubusercontent.com/13218402/61508427-c14b6880-aa24-11e9-8b16-7b60823eb82c.png)

**Comment by aaronmussig** [comment]
Hi, you can find a description of the output files [here](https://github.com/Ecogenomics/GTDBTk#additional-output-files). By the sounds of it `gtdbtk.ar122.classify.tree` (produced in the classify step) is the file you're after.

**Comment by jeagull** [comment]
thanks, I appreciate it :)
