### ISSUE TITLE
help is not working

### ISSUE THREAD

**Issue by Guiguier** [Ecogenomics/GtdbTk#17]
zhang@thinker:~/miniconda3/lib/python3.6/site-packages/gtdbtk/config$ gtdbtk classify_wf -h
  File "/home/zhang/miniconda3/bin/gtdbtk", line 64
    ''' % version()
      ^
SyntaxError: invalid syntax

**Comment by pchaumeil** [comment]
Hi Guiguier,
Thanks for you email.
GTDB-Tk is based on Python 2.7 and does not support python 3.x .
It will not work with your current setup.

Cheers,
Pierre

**Comment by sipesk** [comment]
Can you advise me on how to setup a virtual env to call on python2.7 instead of 3.# ? I'm having issues being able to use gtdbtk while I still have 3.# on my machine.
