### ISSUE TITLE
Expected file size of gtdbtk_r89_data.tar.gz

### ISSUE THREAD

**Issue by cssulliv** [Ecogenomics/GTDBTk#175]
Hi,

I am currently in the process of installing GTDBTK on our university cluster and managed to install gtdbtk_r89_data.tar.gz (27GB). However, I have not run `tar -xvzf gtdbtk_r89_data.tar.gz` because there is a 50GB limit for each user in their directory. I wanted to know how large the resulting reference files will be if I run `tar -xvzf`?

Best,
C

**Comment by pchaumeil** [comment]
Hello,
When unarchived , the reference directory is still around 27GB. 

Regards,
Pierre

**Comment by dparks1134** [comment]
Issue appear resolved.
