### ISSUE TITLE
Firmicutes

### ISSUE THREAD

**Issue by alienzj** [Ecogenomics/GTDBTk#176]
In GTDB taxonomy database, we can found：
```
p__Firmicutes
p__Firmicutes_A
p__Firmicutes_B
p__Firmicutes_C
```
Does this add a suffix makes sense?

I am not familiar with species classification，but I believe GTDB is all right.
I don't like NCBI taxonomy.

**Comment by dparks1134** [comment]
Hello. 

You can find an explanation of the rational for suffixing higher ranks in the GTDB manuscript:
https://www.ncbi.nlm.nih.gov/pubmed/30148503

We have also added this to the GTDB FAQ:
https://gtdb.ecogenomic.org/faq#family_and_higher_rank_end_with_alpha_suffix

Cheers,
Donovan

**Comment by alienzj** [comment]
Thanks very much~

**Comment by xiao-p-ing** [comment]
> 在GTDB分类数据库中，我们可以找到：
> 
> ```
> p__Firmicutes
> p__Firmicutes_A
> p__Firmicutes_B
> p__Firmicutes_C
> ```
> 
> 这添加后缀有意义吗？
> 
> 我不熟悉物种分类，但我相信GTDB没问题。我不喜欢NCBI分类法。

Hello, can p__Firmicutes_A,p__Firmicutes_B, and p__Firmicutes_C be classified into Firmicutes when the species distribution at the phylum level is counted?Looking forward to your reply.
