### ISSUE TITLE
Unable to visualize .classify.tree 

### ISSUE THREAD

**Issue by rbcan** [Ecogenomics/GTDBTk#177]
Hi there,

I am having troubles to open the *.classify.tree file that is produced by the gtdbtk classify_wf. I tried iToL, Arb and Dendroscope. The version of gtdbtk was 0.2.1 and I asked our IT to update it on the servers, but I this may take a while and I wanted to check if this is actually be the problem. 
In Dendroscope I got an error like this: `java.io.IOException: Expected number at position 93 (got: 'f__SM23-28-2'')`

Do you think it there is an issue with the tree file that was produced? And if so, any ideas how I can fix this?

Thanks in advance!
Rebecca

**Comment by dparks1134** [comment]
Hello. I have used Dendroscope to visualize the GTDB-Tk tree. GTDB-Tk is in active development so it is possible there was an issue with v0.2.1. I would strongly recommend upgrading to the latest version AND latest reference data which is based on GTDB R89.

**Comment by rbcan** [comment]
Thanks a LOT for this fast answer :) with the new version it worked (after ALSO updating Dendroscope). Your tool is amazing, thank you!
