### ISSUE TITLE
Classify workflow questions: genome bins and batchfile

### ISSUE THREAD

**Issue by cssulliv** [Ecogenomics/GTDBTk#178]
Hi!

I have scaffold assemblies from 2 metagenomic samples that were binned/refined using Anvio (v5.5). Sample 1 and 2 have ~50 bins and ~30 bins, respectively, that are saved as .fa files. 

1) Is it advisable to run gtdbtk classify_wf for all those bins at once or would it be better to run them separately?

2) For the batch file is it necessary to have a column header for the 2 columns OR should the first 2 rows start with the very first FASTA file name and genome ID? 

Best,
C

**Comment by dparks1134** [comment]
It is far more computationally efficient to run all the genomes at once and is the recommended way to run GTDB-Tk. The batch file does not have a header line.

**Comment by cssulliv** [comment]
Thank you for the clarification!
