### ISSUE TITLE
How to get gram +/- information

### ISSUE THREAD

**Issue by alienzj** [Ecogenomics/GTDBTk#181]
Hello, Ecogenomics team member,
Can I get gram +/- information using GTDBTK?

Because I use [prokka](https://github.com/tseemann/prokka) to annotate MAG bins, use [signalp](http://www.cbs.dtu.dk/services/SignalP/)  to predict signal peptides from protein,
but the signalp needs the organism where the gene comes from Archaea, or gram+, gram-, or Eukarya.

We know that the protein comes from that bins and knows what species the bins are classified into by GTDBTK, so if we know the species is gram+ or gram-, we can set signalp 
organism parameters correctly.

Is my understanding correct?
Thanks very much~

Best regards~
Jack

**Comment by dparks1134** [comment]
Hello Jack. GTDB-Tk is focused on taxonomic classification as the moment. We have no immediate plans to expand it to provide additional genomic characterizations.

**Comment by alienzj** [comment]
Thanks for your reply :)
