### ISSUE TITLE
Python3 migration

### ISSUE THREAD

**Issue by andersgs** [Ecogenomics/GTDBTk#183]
Hello. 

Any plans to migrate to python3 given python2 is sunsetting?

Thank you.

Anders.

**Comment by tseemann** [comment]
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

**Comment by aaronmussig** [comment]
We don't have a date set in stone, but we will certainly migrate to python3 before the end of the year.

**Comment by tseemann** [comment]
Thanks @aaronmussig !   We'll be in contact on 2nd Jan 2020 :-P

**Comment by andersgs** [comment]
@aaronmussig I have been working on a PR off your python3_dev branch. I am hoping to have something in the next few days that will work with ≥3.6. Are you interested? Or should I stop?

**Comment by aaronmussig** [comment]
@andersgs I've just pushed some changes to python3_dev which update the 0.3.3 code to py3. I believe just testing is required at this stage, however, I would like to know if anything has been missed. Thanks!

**Comment by andersgs** [comment]
@aaronmussig cool... I'll pull it down, and start some testing...

**Comment by andersgs** [comment]
Hi @aaronmussig. Test successfully finished:
```
$ gtdbtk test --out_dir /tmp/agoncalves/gtdb_test --cpus 16
[2019-11-29 07:37:33] INFO: GTDB-Tk v1.0.0
[2019-11-29 07:37:33] INFO: gtdbtk test --out_dir /tmp/agoncalves/gtdb_test --cpus 16
[2019-11-29 07:37:33] INFO: Using GTDB-Tk reference data version r89: /home/agoncalves/gtdbtk/release89
[2019-11-29 07:37:33] INFO: Command: gtdbtk classify_wf --genome_dir /tmp/agoncalves/gtdb_test/genomes --out_dir /tmp/agoncalves/gtdb_test/output --cpus 16
[2019-11-29 07:39:07] INFO: Test has successfully finished.
```

Running python 3.7.5.

Will try to run on a few of our genomes now.

**Comment by andersgs** [comment]
Hi @aaronmussig. I have tested on ~12K isolates now (it took just over 20 hours on a computer with 72 CPUs and 400GB of RAM - 2.3GHz Intel Xeon processors). I gave it 72 CPUs.

The only issue I ran into was when I added a path to the batchfile that did not exist. Currently, there are no checks to see if a file exists and can be read by the user. It would be good to introduce some nicer way of dealing with the issue without crashing out.

On a related note, the docs are a bit confusing about what needs to be downloaded. Currently, it seems there are two things that need to be downloaded. It could be cleaned up a bit to make it easier for the user. Ideally, you would provide a tool to download the latest data and put it someplace for the user, and create the appropriate ENV variable. Something like what NLTK does: https://github.com/nltk/nltk/blob/develop/nltk/downloader.py 

I was chatting to @tseemann about it, and we were wondering why prodigal instead of tblastn?

Otherwise, I think it is really ready for release. 

Nice work!!! Thank you!

**Comment by tseemann** [comment]
Doing prodigal then blastp is a lot faster as it avoids the  6-frame translation blowout. And i guess if the core marker gene isn't found, it means it was probably broken anyway, so tblastn won't help. I wonder if just finding large ORFs would be simpler and give the same result?

**Comment by aaronmussig** [comment]
Hi @andersgs, thanks for running those through and raising the path issue. I'll add a check when the batchfile is parsed for the upcoming release. I'll add #192 to the py3 milestone and do some final testing today. It should be on track for a release this evening/tomorrow morning.
