### ISSUE TITLE
syntax of the commands inside classify

### ISSUE THREAD

**Issue by anatmaoz** [Ecogenomics/GTDBTk#186]
is there any documentation for the identify/align/classify commands? i want to run them separately and not in one time when I run classify.

**Comment by aaronmussig** [comment]
Hi,
You can view the documentation using the CLI:
`gtdbtk identify -h`
`gtdbtk align -h`
`gtdbtk classify -h`

If anything is unclear or if you think it would be better documented on GitHub then let us know so we can make this a suggestion.
