### ISSUE TITLE
Database Permission

### ISSUE THREAD

**Issue by emblab-westlake** [Ecogenomics/GTDBTk#187]
Dear Sir/Madam,

When I tried to download the database, I encountered the following situation:

**Forbidden
You don't have permission to access /public/gtdb/data/releases/ on this server.
Apache/2.2.15 (CentOS) Server at data.ace.uq.edu.au Port 443**

 I'm using this software for data analysis, could you help me?

**Comment by dparks1134** [comment]
Hello. Our servers are down at the moment. We are working to fix this. Hopefully the issue will be resolved in the next day or two.

**Comment by dparks1134** [comment]
Servers are back up.

**Comment by emblab-westlake** [comment]
The database has been downloaded successfully. Thank you very much!
