### ISSUE TITLE
can i specify which tree to work on when running classify?

### ISSUE THREAD

**Issue by anatmaoz** [Ecogenomics/GTDBTk#188]
I would like to run classify on one genome at the time and add to the same tree these genomes.
I mean I would like to run classify_wf on genome1. Let's say that then tree1.tree would be created. On the next step I would like to add genome2 to tree1.tree and create a new tree (tree2.tree) that contain both genomes (genome1 and 2). Is it possible to provide to classify the tree that was created on previous steps? I don't want to run both genomes again since genome1 is already in the tree.
Thanks!

**Comment by pchaumeil** [comment]
Hello,
It is impossible to change the reference tree in the classify workflow.
If you want to compare genome2 to genome1, I would recommend running a _de novo_ tree including those 2 genomes.
Otherwise you should run them all in the same classify step.

Thanks.

**Comment by anatmaoz** [comment]
thank you! Is it possible to change the reference tree in the de novo workflow? I understand in the classify workflow it is impossible but in the de novo too?

**Comment by pchaumeil** [comment]
Hello,
Apologies for the late answer.
It is not possible to change the reference genomes in the de novo workflow either.

However you can run the step "identify" and "align" independently and run the infer step outside of GTDB-Tk with your MSA of interest.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
