### ISSUE TITLE
RED_DIR = os.path.join(GENERIC_PATH, "mrca_red/) is absent in release89 database

### ISSUE THREAD

**Issue by chhaya3101** [Ecogenomics/GTDBTk#189]
This mrca_red directory is not present in release89 database causing error.

EXCEPTION: IOError
  MESSAGE: [Errno 2] No such file or directory: '/home/lcbuser1/release89/mrca_red/gtdbtk_r89_ar122.tsv'

**Comment by pchaumeil** [comment]
Hello,
Please try to re download the GTDB-Tk reference package:
```
wget https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz
```
And verify that the MD5 sum of this downloaded package is identical to the one provided in [gtdbtk_r89_data.tar.gz.md5](https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz.md5).

This package contains the mrca_red directory.

**Comment by chhaya3101** [comment]
Thank you Sir, for your kind favor.

Regards

Chhaya Singh
PhD
Research Associate
School of Life Sciences
University of Hyderabad
India-500046
