### ISSUE TITLE
no module named config.

### ISSUE THREAD

**Issue by caonetto** [Ecogenomics/GtdbTk#19]
Hi,
I think I have installed all the dependecies properly however when trying to run gtdbtk I get the following error:

```
gtdbtk -h
Traceback (most recent call last):
  File "/usr/local/bin/gtdbtk", line 37, in <module>
    from gtdbtk.main import OptionsParser
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 22, in <module>
    from markers import Markers
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gtdbtk/markers.py", line 36, in <module>
    import config.config as Config
ImportError: No module named config
```

Any ideas?

Thanks

**Comment by pchaumeil** [comment]
Hello, 
It looks like the config file cannot be found in the gtdbtk directory.
Did you copy the "config_template.py" file to "config.py" and edit the GENERIC_PATH variable in  "config.py" to point to the directory where the data have been downloaded?

Regards,
Pierre

**Comment by caonetto** [comment]
Hi Pierre,
Thanks for your reply. Strangely I had copied the file to the main gtdbtk directory. Now is fixed.
Thanks!
