### ISSUE TITLE
threshold of red value to classify

### ISSUE THREAD

**Issue by ucassee** [Ecogenomics/GTDBTk#190]
I want to know the default RED setting when classify genome to different taxonomy. For example, what range of RED value support it just belong to a genus but can't confirm its species?
Could you provide me some information about that ?
Thanks in advance~

**Comment by pchaumeil** [comment]
Hello Yingli,
associating a query genome to a species is based on the pplacer placement and ANI values to reference genomes, We do not use the RED value for this step. If a query genome as an ANI value >= 95% and a AF >= 65% with a reference genome it will be classified as the same species. 

If a query genome is placed under a genus node in the tree but cannot be assign to any reference species, it will be considered a new species.

**Comment by ucassee** [comment]
@pchaumeil  Thanks for your reply~
For the following classification
B1T1B5	d__Archaea;p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__UBA57;g__;s__
Why it can be assign to family UBA57, but can't assign to a certain genus ? What are the thresholds in   Phylum, class and order? Are  these assignments all based on ANI thresholds?

**Comment by dparks1134** [comment]
ANI is only used for establishing if a genome belongs to a species. All other assignments are based on the placement of genomes in a reference tree and their relative evolutionary divergence (RED: see https://www.ncbi.nlm.nih.gov/pubmed/30148503). Depending on the placement, the topology may dictate that the genome cannot be assigned to an existing genus (i.e., it is placed above 2 or more existing genera). Alternatively, it may be placed on a branch leading to a single genus and determined to not be part of these genus due to its RED value. Which of this cases has occurred is reported in the `classification_method` column.

**Comment by ucassee** [comment]
@dparks1134  Thanks for your reply~

>  Alternatively, it may be placed on a branch leading to a single genus and determined to not be part of these genus due to its RED value

What is the cut-off RED setting for this step to determined it not be part of these genus.  What are the s cut-off RED settings for other higher ranks?

**Comment by dparks1134** [comment]
There isn't a cut-off per say. A genome is assigned to a given taxon if it brings the RED value for the taxon closer to the median RED for the associated taxonomic rank. You can find the median RED values for each taxonomic rank in the GTDB-Tk metadata in the file `<gtdbtk_data_dir>/metadata/metadata.txt`. Please note that GTDB-Tk classification are intended to be a convenient and relatively fast was to assign initial GTDB assignments to genomes. If your study is directly concern with taxonomic assignments best practices in the field still need to be followed (i.e., inferring de novo trees with different marker sets, infer methods, and assessing tree stability via bootstrapping).

**Comment by ucassee** [comment]
I don't study taxonomic assignments. I do metagenomic research to study the role of extremophiles in environment. The basic goal is to determine MAGs taxon and how many new taxon in my samples? I feel confused about the fixed median RED for taxonomic rank. Do the median RED calculate by all references red in the  tree?  In my opinion, different microorganisms have different evolutionary rates. 
ps:You develop a very useful tool to assign taxon.
