### ISSUE TITLE
GTDB-Tk fails on poor quality genomes

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/GTDBTk#192]
Exceptionally poor quality genomes can fail to produced any identified proteins. This results in subsequent steps failing. Ideally, we should identify these cases and just report a warning that a given number of genomes could not be processed. The identify for these genomes should be written to a file (say "failed_genomes.tsv") with a brief explanation of why they could not be processed (e.g., "no protein sequences identified by Prodigal").

Example errors:

```
Traceback (most recent call last):
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/srv/sw/python/2.7.4/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/sw/gtdbtk/0.3.2/gtdbtk/external/tigrfam_search.py", line 116, in _workerThread
    checksum = sha256(output_hit_file)
  File "/srv/sw/gtdbtk/0.3.2/gtdbtk/tools.py", line 68, in sha256
    with open(input_file, 'rb') as afile:
IOError: [Errno 2] No such file or directory: 'gtdbtk_classify/identify/intermediate_results/marker_genes/GCA_002870245.1/GCA_002870245.1_tigrfam.tsv'
==> Finished processing 66683 of 67867 (98.3%) genomes.
Error: Sequence file gtdbtk_classify/identify/intermediate_results/marker_genes/GCA_000722115.1/GCA_000722115.1_protein.faa is empty or misformatted
```

**Comment by aaronmussig** [comment]
This is now resolved by skipping those genomes. A list of those genomes are now output to a `<prefix>.warnings.log` file.
