### ISSUE TITLE
How to interpret the taxonomy assignment, like "g_"

### ISSUE THREAD

**Issue by Duannai** [Ecogenomics/GTDBTk#193]
Hello,

For the following classification,

>d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__Oscillospiraceae;g__Pseudoflavonifractor;s__

It can be infered as a new speices of genus Pseudoflavonifractor.

> d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__Oscillospiraceae;g__;s__

Could this bin be infered as a new genus of family Oscillospiraceae.

Thanks in advance.

Morton

**Comment by dparks1134** [comment]
Yes!

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
