### ISSUE TITLE
RED description discrepancy between manuscript and GTDB website

### ISSUE THREAD

**Issue by dadahan** [Ecogenomics/GTDBTk#194]
Hi, in the manuscript you write:
> "Our method provides an operational approximation of relative time with extant taxa existing in the present **(RED = 1)**, the last common ancestor occurring at a fixed time in the past **(RED = 0)** and internal nodes being linearly interpolated between these values according to lineage-specific rates of evolution (Fig. 1 and Online Methods). "

and on https://gtdb.ecogenomic.org/stats you write:

> "The following graphs show the relative evolutionary divergence (RED) of taxa at each taxonomic rank from phylum to genus. RED values provide an operational approximation of relative time with extant taxa existing in the present **(RED=0)**, the last common ancestor occurring at a fixed time in the past **(RED=1)**, and internal nodes being linearly interpolated between these values according to lineage-specific rates of evolution. RED intervals for normalizing taxa at taxonomic ranks was operationally defined as the median RED value (indicated by a blue bar) at each rank ±0.1 (indicated by grey bars)."

I've highlighted the mix up in bold. Which is correct?

**Comment by dparks1134** [comment]
Hi. Thanks for bringing this to our attention. The manuscript is correct. We have updated the website.
