### ISSUE TITLE
on version 0.3.2 the --skip_gtdb_refs option does not work

### ISSUE THREAD

**Issue by anatmaoz** [Ecogenomics/GTDBTk#197]
when running
gtdbtk de_novo_wf --genome_dir <my_genomes> --<marker_set> --outgroup_taxon <outgroup> --out_dir <output_dir> ----skip_gtdb_refs
the code crashes with no error. It creates the identity, align and infer directories . but the infer directory reminds only with intermediate_results.
[2019-11-19 08:18:27] WARNING: Tree rooting is still under development!
[2019-11-19 08:18:27] INFO: Identifying genomes from the specified outgroup.
[2019-11-19 08:18:27] INFO: Identified 0 outgroup taxa in the tree.
[2019-11-19 08:18:27] INFO: Identified 5 ingroup taxa in the tree.
[2019-11-19 08:18:27] WARNING: No outgroup taxa identified in the tree.
[2019-11-19 08:18:27] WARNING: Tree was not rerooted.
[2019-11-19 08:18:27] ERROR: Controlled exit resulting from early termination.
--
when i run the same thing without outgroup_taxon it says it is mendatory
thanks!

**Comment by anatmaoz** [comment]
--skip_gtdb_refs and not ----

**Comment by aaronmussig** [comment]
Hello,

The `--custom_taxonomy_file` argument should be included when using `--skip_gtdb_refs` as the re-rooting operation is unable to determine which taxa belong to your outgroup.

The `custom_taxonomy_file` should be a tab-separated value file (with no header), column 1 is the genome id (as called - if you're unsure, simply check the `translation_table_summary` file), e.g.

```
genome_1	d__Archaea;p__Thermoplasmatota;c__Poseidoniia;o__Poseidoniales;f__Poseidoniaceae;g__MGIIa-K1;s__MGIIa-K1 sp002506705
genome_2	d__Archaea;p__Halobacterota;c__Archaeoglobi;o__Archaeoglobales;f__Archaeoglobaceae;g__Archaeoglobus_C;s__Archaeoglobus_C veneficus
```

After re-reading the help arguments for `de_novo_wf` appears that it's a little unclear and we will update them for a future release. 

The root and decorate step of the de-novo workflow are still under development and need further testing. I'd recommend using the un-rooted tree output under `infer/intermediate_results/[prefix].[marker].unrooted.tree` and manually re-rooting.

**Comment by anatmaoz** [comment]
thanks. Can you please send me the location of the translation_table_summary file?

**Comment by aaronmussig** [comment]
You can find that file in the `--out_dir` specified. You can still use the unrooted tree after it fails on the de-novo workflow rooting step, that will have been inferred according to the fasttree parameters.

Alternatively, if you wish to run each of the de-novo workflow steps individually (`identify`, `align`, `infer`) and stop before the root step that will also work.
