### ISSUE TITLE
importing results of align into ARB tree.

### ISSUE THREAD

**Issue by caonetto** [Ecogenomics/GtdbTk#20]
Hi,
I currently don't have access to 90gb of ram to run the whole tree module, however I was able to run identify and align. I have the big GTDB tree loaded into ARB and I was wondering what is the best way to quickly add my aligned sequences into arb. What sort of selected format for the alignment I need to choose?

Thanks for your help.

Cris

**Comment by dparks1134** [comment]
Hi Cris,

The alignments are in protein space. I don't have any direct experience using ARB in this manner though so am not sure of the exact workflow. 

Cheers,
Donovan
