### ISSUE TITLE
Integrate some CheckM features into gtdbtk?

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#200]
There seems to be a lot of redundancy between the steps taken by CheckM and gtdbtk, such as gene finding and tree placement with pplacer.  The metrics from CheckM that I am most interested in are completeness and contamination.  Would it be possible to integrate these features into gtdbtk so that I can just run gtdbtk on a set of genomes and get both sets of output?  This would save a lot of time and computing resources when running on large sets of genomes.

**Comment by dparks1134** [comment]
CheckM and GTDB-Tk currently use different reference trees so avoiding multiple tree placement steps with pplacer isn't possible. The long term plan is for CheckM v2 to use the taxonomic assignments provided by GTDB-Tk as a bases for establishing genome quality estimates. This is still in early development though.

**Comment by cheberling** [comment]
Cool, thanks!
