### ISSUE TITLE
taxonomy issue

### ISSUE THREAD

**Issue by ucassee** [Ecogenomics/GTDBTk#204]
There is  a big difference between GTDBtk  and ncbi taxonomy, especially in  ammonia-oxidizing archaea (Nitrosopumilus). The AOA is consider belong to Thaumarchaeota. But in gtdbtk, it is assigned as Crenarchaeota. I really feel confused. I also want to know whether there is a easy way to transfer the GTDBtk to ncbi taxonomy.
Thanks in advance

**Comment by dparks1134** [comment]
Hi. Questions related to the GTDB taxonomy are best sent to the GTDB Team:
https://gtdb.ecogenomic.org/about

You can get a majority-vote translation from the GTDB to NCBI Taxonomy using the gtdb_to_ncbi_majority_vote.py script:
https://github.com/Ecogenomics/GTDBTk/tree/stable/scripts

This script is not currently officially supported and all results should be manually inspected.
