### ISSUE TITLE
Meaning of branch length in the reported tree

### ISSUE THREAD

**Issue by nigiord** [Ecogenomics/GTDBTk#209]
Hi there and thank you for providing GTDB-Tk,

I've been using the tree reported by GTDB-Tk (`gtdbtk.[bac120/ar122].classify.tree`) to compute a rough pairwise cophenetic (phylogenetic) distance between microbial genomes. I have however a few questions:

- What is the meaning of the branch length in the tree? I initially thought they were between 0 and 1 but a few of them seem to be higher. No success so far looking for this information in the GTDB and pplacer publications.
- Is there a reasonable way to compute distances between genomes classified as Archaea and Bacteria, since they are reported in two separate trees?

Regards,
−Nils

**Comment by dparks1134** [comment]
Hi Nils. The tree is a "standard" phylogenetic tree with branch lengths indicating expected substitutions per site. If you go with the latest paper from the Knight lab (https://www.nature.com/articles/s41467-019-13443-4) the branch length between Bacteria and Archaea is fairly short so you might just be able to ignore it and/or determine a sensible estimate from the Knight reference tree.

**Comment by nigiord** [comment]
Hi @dparks1134 and thank you for your fast answer!
I see, I wasn't sure whether or not these lengths were "standard" and comparable with trees from other studies. I'll probably do as you suggest and find an estimate from the Knight reference tree. Thanks!
−Nils
