### ISSUE TITLE
Try to use gtdb_to_ncbi_majority_vote.py

### ISSUE THREAD

**Issue by minjaekim45** [Ecogenomics/GTDBTk#210]
Hi 
I'm trying to use this script and am wondering where I can find bacterial GTDB metadata file and the archaeal GTDB metadata file?
Thanks!
Minjae Kim

**Comment by dparks1134** [comment]
There are part of the GTDB:
https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/

ar122_metadata.tsv 
bac120_metadata.tsv

Cheers,
Donovan

**Comment by minjaekim45** [comment]
Thanks!

**Comment by minjaekim45** [comment]
I'm sorry to reopen this but I got the following error
[Error] File does not exists: ./gtdbtk.ar122.summary.tsv
I just ran one MAG which belongs to bac and apparently I don't have file for this.
Also, I tried without giving arc metadata and it says required.
Can you help me with this?

**Comment by aaronmussig** [comment]
Hi, the script isn't aware of which domain the MAG belongs to so you will need to download and provide both files. Please post the command you're running and the output if the error still occurs after downloading both metadata files and running it with both `--ar122_metadata_file` and `--bac120_metadata_file`.

**Comment by minjaekim45** [comment]
Thanks for the reply
Here is the whole command line and errors

/account/mkim/Software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py --gtdbtk_output_dir ./ --ar122_metadata_file /account/mkim/Software/GTDBTk/metadata/ar122_metadata.tsv --bac120_metadata_file /account/mkim/Software/GTDBTk/metadata/bac120_metadata.tsv --output_file test --gtdbtk_prefix gtdbtk
gtdb_to_ncbi_majority_vote.py v0.0.2: Translate GTDB to NCBI classification via majority vote.
  by Donovan Parks (donovan.parks@gmail.com)

Read NCBI taxonomy for 143566 genomes.
Identified 24706 GTDB species clusters.
Identified 24176 GTDB species clusters with an NCBI classification.
[Error] File does not exists: ./gtdbtk.ar122.summary.tsv

Controlled exit resulting from an unrecoverable error or warning.

**Comment by aaronmussig** [comment]
Thanks for the feedback, I've updated the script which can be found on the `staging` branch.

Replace the contents of `/account/mkim/Software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py` with https://github.com/Ecogenomics/GTDBTk/blob/staging/scripts/gtdb_to_ncbi_majority_vote.py and it should work.

**Comment by minjaekim45** [comment]
Thanks for the update but it seems not working with same error.
Here I attached the command line and errors
(gtdbtk) [mkim@ncshpc01 output]$ /account/mkim/Software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py --gtdbtk_output_dir ./ --ar122_metadata_file /account/mkim/Software/GTDBTk/metadata/ar122_metadata.tsv  --bac120_metadata_file /account/mkim/Software/GTDBTk/metadata/bac120_metadata.tsv --output_file ./test --gtdbtk_prefix gtdbtk
gtdb_to_ncbi_majority_vote.py v0.0.3: Translate GTDB to NCBI classification via majority vote.
  by Donovan Parks (donovan.parks@gmail.com)

[2019-12-18 08:32:23] INFO: GTDB to NCBI majority vote v0.0.3
[2019-12-18 08:32:23] INFO: gtdb_to_ncbi_majority_vote.py --gtdbtk_output_dir ./ --ar122_metadata_file /account/mkim/Software/GTDBTk/metadata/ar122_metadata.tsv --bac120_metadata_file /account/mkim/Software/GTDBTk/metadata/bac120_metadata.tsv --output_file ./test --gtdbtk_prefix gtdbtk
[2019-12-18 08:32:23] INFO: Processing archaeal metadata file.
[2019-12-18 08:32:23] INFO: Processing bacterial metadata file.
[2019-12-18 08:32:26] INFO: Read NCBI taxonomy for 143,566 genomes.
[2019-12-18 08:32:26] INFO: Identified 24,706 GTDB species clusters.
[2019-12-18 08:32:27] INFO: Identified 24,176 GTDB species clusters with an NCBI classification.
[2019-12-18 08:32:27] ERROR: Summary file does not exist: ./classify/gtdbtk.ar122.summary.tsv
[2019-12-18 08:32:27] ERROR: Controlled exit resulting from an unrecoverable error or warning.

**Comment by aaronmussig** [comment]
The old logic assumes that if the metadata file is provided it must have a summary file in the output directory. I've updated the staging branch with commit 59357e9 to warn if the summary file isn't found, instead of exiting. You can download the same file again and it will resolve it. Alternatively, you can not specify the archaeal metadata file and it will work.

**Comment by minjaekim45** [comment]
It works! 
Thanks

**Comment by aksha19n** [comment]
Hi, I'm getting the following warning message 
[2024-05-13 08:08:25] WARNING: Bacterial GTDB-Tk classification file does not exist.
[2024-05-13 08:08:25] WARNING: Assuming there are no bacterial genomes to reclassify.

I have the gtdbk.bac120.summary.tsv file in the output dir despite which there is an error. The classify workflow was performed on Kbase could that be a reason?
