### ISSUE TITLE
Regarding the interpretation of outcome

### ISSUE THREAD

**Issue by minjaekim45** [Ecogenomics/GTDBTk#212]
Thanks for all help and developing this tool.

I have a result from GTDBtk analysis with my MAGs and need your opinion on the interpretation of the results.

I have 244 MAGs and 216 MAGs showed full classification (name of the species present in the second column), so that I can say that this MAG is the same species with the one in the third column. However, 28 MAGs do not have the name of the species in the second column of the results (i.e., s__) and N/A for 3rd to 7th columns. 
Among these 28 MAGs, some of them showed N/A until the 8~11th columns, while others have some closest species information (most of them showed ani is below 95% but a couple of them showed ani above 95%).
****In this case, can I still say that all of these 28 MAGs are novel species based on GTDBtk classification?**

I can send you a result file if you need.

Thanks in advance

**Comment by dparks1134** [comment]
Hi. Yes, these 28 MAGs represent novel species as defined by the Genome Taxonomy Database (GTDB: https://gtdb.ecogenomic.org/).

**Comment by pchaumeil** [comment]
Ticket closed.
