### ISSUE TITLE
make setting GTDBTK_DATA_PATH optional in bioconda recipe

### ISSUE THREAD

**Issue by ctb** [Ecogenomics/GTDBTk#213]
hi @npavlovikj  @aaronmussig, any objections to me submitting a PR to bioconda so that `gtdbtk.sh` will accept an already-defined GTDBTK_DATA_PATH? I'd like to be able to set it externally (e.g. snakemake) or globally (e.g. in bashrc) and then have the conda environment pick it up.

I was thinking of adding this:

```
[ -z "$GTDBTK_DATA_PATH" ] && VARIABLE="${target}/db/"
export GTDBTK_DATA_PATH
```

but then it might not deactivate properly... thoughts welcome!

**Comment by ctb** [comment]
(ref https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gtdbtk/build.sh)

**Comment by ctb** [comment]
Well, this is much easier!

https://github.com/dib-lab/sourmash-oddify/blob/master/Snakefile#L62

```
GTDBTK_DATA_PATH=... gtdbtk classify_wf  ...
```

**Comment by npavlovikj** [comment]
Happy holidays!

I know I am late to reply, and I am glad to see that @ctb has found a solution in the meantime.

Just to add to the solution - personally, I think the conda recipes should be as general as possible, and any variables should be set/modified on the local system, after the environment is created.
For example, on our University clusters, GTDBTK_DATA_PATH points to a different location in the module file for "gtdbtk", and every time "gtdbtk" is loaded/activated, the variable is set as well. The same can be done by exporting the variable after the environment is activated, or right before the command is executed, same as "sourmash-oddify" is doing.
