### ISSUE TITLE
bins missing in the output

### ISSUE THREAD

**Issue by Kirk3gaard** [Ecogenomics/GTDBTk#218]
Hi

Thanks for a great and easy to use tool!

I have noticed that when I submit 300 bins to GTDBtk I might not get 300 back in the summary file. 
I assume that some of them are filtered by some criteria but not sure which. 

It would be really great if all bins were reported in the summary file and the ones that are currently filtered would just have NA everywhere and maybe a message in the "warnings" column.

Best regards
Rasmus

**Comment by dparks1134** [comment]
Hi Rasmus,

Genomes failing GTDB-Tk filtering are listed in the `*.filtered.tsv` files and filtering is set by `--min_perc_aa`.

Cheers,
Donovan

**Comment by Kirk3gaard** [comment]
Hi Donovan

Thanks for the reply. The log is very useful 👍 

It would still be great if all bins were included in a single summary file. Also archaea and bacteria could go in the same file to present an overview of all bins submitted to gtdbtk.

(It appears that the symbolic links are not parsed properly by the version of MobaXterm that I am using so it complicates the issue further as a download of the symbolic link leads to an incomplete summary file compared to the one inside the classify folder.)

Best regards
Rasmus
