### ISSUE TITLE
Question about GTDB-Tk reference data

### ISSUE THREAD

**Issue by igorspp** [Ecogenomics/GTDBTk#219]
Hi,

First of all many thanks for developing and maintaining such a useful tool!
I have a question, not an issue or bug, but I don't know anywhere else to post this so please forgive me if I'm not at the right place.
In addition to getting the taxonomic classification, I would like to know the similarity between my genomes/MAGs and the GTDB genomes for each of the marker genes used. GTDBtk does not report this, correct?
I was thinking then that I could get this info through BLAST. But I cannot seem to find a file containing the bac120/ar122 proteins for all >140k genomes, only the set of 23,458/1,248 genomes used to infer the taxonomy. Is this data available somewhere by any chance?

Many thanks in advance for the clarification!

Best, 
Igor

**Comment by dparks1134** [comment]
Hi Igor. We don't currently maintain the bac120/ar122 gene sets for all genomes, just the representatives.
