### ISSUE TITLE
name issue of symlinked bacteria rooted tree

### ISSUE THREAD

**Issue by jlli6t** [Ecogenomics/GTDBTk#224]
Hi,

I am using gtdbtkv1.0.2, the de_novo_wf command, with parameter --bac120_ms.

In the output dir, the symlink tree is "test_tree.ar122.rooted.tree -> infer/test_tree.bac120.rooted.tree", which should be "test_tree.bac120.rooted.tree -> infer/test_tree.bac120.rooted.tree".

It seems like a name issue when symlink (main.py, line 485) the rooted tree to the output dir that user specified.

Thanks,
Jie

**Comment by pchaumeil** [comment]
Hello Jie,

Thanks for your email.
The symlink has been fixed in 873ed80 and a new version of GTDB-Tk will be released in a few days time.

Regards,
Pierre

**Comment by jlli6t** [comment]
Hi Pierre, Thank you for such a quick response
