### ISSUE TITLE
Sequence XX doesn't overlap any reference sequences

### ISSUE THREAD

**Issue by michoug** [Ecogenomics/GtdbTk#23]
Hi
Analysing different MAGs with potential plasmids, I get this error :

```
[2018-05-30 12:27:01] INFO: Placing 355 bacterial genomes into reference tree with pplacer (be patient).
Uncaught exception: Failure("Sequence N2F3_MBin.34 doesn't overlap any reference sequences.")
Fatal error: exception Failure("Sequence N2F3_MBin.34 doesn't overlap any reference sequences.")
Uncaught exception: Sys_error("All_out/pplacer/pplacer.bac120.json: No such file or directory")
Fatal error: exception Sys_error("All_out/pplacer/pplacer.bac120.json: No such file or directory")
GTDB-Tk has stopped before finishing
```
Would it be possible to skip the sequence without shutting down the software ?
Cheers
Greg

**Comment by michoug** [comment]
Hi Donovan 
Thanks for your answer.
I resolved the issue by seeing that there was only gaps in the alignment and then manually removing the files. I suppose that it's because none of the 120 genes was found. Would it be possible to check this before the pplacer step and write it somewhere ?
Greg

**Comment by dparks1134** [comment]
Hey Greg. I think it must be something more subtle than that. CheckM will default to using a "universal" set of markers if a genome contains less than 10 unique marker genes (see --unique flag).

**Comment by michoug** [comment]
Hey Donovan, I was not aware that GtdbTk was using checkM ! I didn't find the --unique flag in the GtdbTk script.
Looking at the gtdbtk_bac120_markers_summary file, there are some case when no unique_genes	or number_multiple_genes are found

[gtdbtk_bac120_markers_summary.txt](https://github.com/Ecogenomics/GtdbTk/files/2057371/gtdbtk_bac120_markers_summary.txt)

**Comment by dparks1134** [comment]
Hey Greg. Sorry, too many different programs these days. The GTDB-Tk has the flag "--min_perc_aa". If you set this to something greater than zero does it filter these out for you?

**Comment by michoug** [comment]
Yes it does, here is one of the lines of the log

> [2018-06-01 11:26:43] INFO: 18 user genomes have amino acids in <1.0% of columns in filtered MSA.

**Comment by dparks1134** [comment]
Great. I think we will actually change the default to 50% in the next release.
