### ISSUE TITLE
Chosen of multiple marker genes 

### ISSUE THREAD

**Issue by TarsLi** [Ecogenomics/GTDBTk#230]
Hi,
I noticed that there are some multiple marker genes in my genomes when i used the identify pipeline. My question is how are these multiple marker genes selected? Choose the besthit or neither? I did not find a detailed description of the chosen of mulitple marker genes. Are there any thresholds I can follow? 
If I want to construct the MSA manually, can I directly use the maker gene id given in the tophit file? Thank you!

**Comment by pchaumeil** [comment]
Hello,
Thanks for your question,

In the current version of GTDB-Tk (1.0.2):
When GTDB-Tk detects multiple hits for a specific marker, it selects the best gene based on the bitscore in the tophit file. 

However we are about the release GTDB-Tk v1.0.3: In this version the behaviour will slightly change and ,in the same time, it will fix a issue detected during the multiple hits comparison.
With the coming version, When having multiple hits for a specific marker, GTDB-Tk will compare the gene sequences hitting the marker: If all those sequences are 100% identical, it will select one of the gene to use in the MSA. but if not all sequences are identical, it will not return any match for the MSA.

This logic is similar to the one used in GTDB ( https://www.ncbi.nlm.nih.gov/pubmed/30148503 )
Hope this helps!

**Comment by TarsLi** [comment]
I got it, thanks for the reply!
