### ISSUE TITLE
How to make sure MAGs are included in GTDB?

### ISSUE THREAD

**Issue by caity-s** [Ecogenomics/GTDBTk#232]
Hey Pierre and Donovan,

Our lab has submitted MAGs to ENA in the past, and we have found that one of our favourites is not in release89 - though it was submitted in 07/2018. 

https://www.ncbi.nlm.nih.gov/assembly/GCA_900491745.1/

It is probably because it was submitted incorrectly for Refseq and consequently GTDB to pick up (maybe some difference between the ENA vs NCBI submission process not translating correctly, I am not sure because I didn't submit this MAG). I can see it has associated Assembly information but not a genome page. 

Which data is scraped from NCBI for the GTDB releases (Assembly/Genome via Refseq)? Would it be possible to add that as a brief section to the readme so that people know how they should be submitting to NCBI so their taxonomy can be included in future GTDB releases? This may be more of a question for Refseq, but if you have any ideas they would be appreciated!

Thank you,
Caitlin

**Comment by dparks1134** [comment]
Hi Caitlin. We are looking into this genome. I can confirm it just missed the submission date for GTDB R89 which is based on RefSeq R89 release in July, 2018. However, this genome is also not present in the upcoming GTDB R95 or the staging of GTDB R98 for reasons that are unclear. The genome looks to have been submitted properly, but perhaps it has taken some time for it to move from ENA's genome repository to NCBI's repository? I'll let you know if we are able to uncover a more concrete reason. This genome is indicating as having been submitted in July, 2018. Any chance it was only made public more recently?

**Comment by dparks1134** [comment]
Hi Caitlin. Pierre has tracked down the issue. GCA_900491745.1 has a Taxid of 1592332 which has the NCBI classification of unclassified sequences; metagenomes; ecological metagenomes. Critically, it is not considered to be a bacterial or archaeal genome and the GTDB only considered such genomes. This is likely a problem that stems well outside of the GTDB as many bioinformatic tools only download genomes at NCBI classified as Bacteria or Archaea. Whoever submitted the genome to NCBI will need to contact them and have the taxonomic assignment of this genome update to reflect its true classification.

**Comment by caity-s** [comment]
Hey Donovan, 

Thank you so much for looking into that, I really appreciate it. That makes sense and is an easy fix for us. It will also help us make sure it doesn't happen again when we submit our next batch. Submissions are tricky with all the metadata, bioprojects, biosamples - lots of room for error. Now I know what to look for!

Thanks again,
Caitlin
