### ISSUE TITLE
Meaning of 'AF'

### ISSUE THREAD

**Issue by vinisalazar** [Ecogenomics/GTDBTk#240]
Hi,

Could you please explain what is the meaning of **AF** in the summary file? I went through the documentation, e.g. [this page](https://ecogenomics.github.io/GTDBTk/files/summary.tsv.html) but couldn't find what this abbreviation means.

Pardon me for opening an issue for such a trivial question, but I could not easily find it anywhere (including a Ctrl+F search in the GTDB-Tk paper).

Thank you for any assistance you can provide,

V

**Comment by aaronmussig** [comment]
Hello,

AF is the alignment fraction between a query and reference genome, i.e. the proportion of fragments in the query genome which have been mapped to the reference genome. If you're after additional info you might be able to find it in the [FastANI methods](https://www.nature.com/articles/s41467-018-07641-9#Sec8) section.

Cheers.
