### ISSUE TITLE
Number of processed genomes in the identify directory is unequal to the list of input genomes

### ISSUE THREAD

**Issue by susheelbhanu** [Ecogenomics/GTDBTk#249]
Hey @aaronmussig:

I ran into the same issue again with the 'number of input genomes being unequal'. Funnily enough, when I reran gtdbtk on the same folder, everything finished completely. Attached is the log file:

[slurm-1795353.iris-187-ont_new_basecalled.gtdbtk.out.txt](https://github.com/Ecogenomics/GTDBTk/files/4569863/slurm-1795353.iris-187-ont_new_basecalled.gtdbtk.out.txt)

Also, I'm running gtdbtk in a snakemake pipeline like so:
```
rule gtdbtk:
    input:
           gen=os.path.join(RESULTS_DIR, "Binning/{sample}/dastool_output/{sample}_DASTool_bins")
    threads:config["threads"]
    conda:"../envs/gtdbtk.yaml"
    params:
           outdir=os.path.join(RESULTS_DIR, "Binning/gtdbtk_output/{sample}")
    output:
           gtdbfile=os.path.join(RESULTS_DIR, "Binning/gtdbtk_output/{sample}/gtdbtk.bac120.summary.tsv")
    shell:
            """
            (date &&\
            export GTDBTK_DATA_PATH={config[GTDBTK][DATA]} &&\
            gtdbtk classify_wf --cpus {threads} -x fa --genome_dir {input.gen} --out_dir {params.outdir} &&\
            touch gtdbtk.done &&\
            date) 2> >(tee {log}.stderr) > >(tee {log}.stdout)
            """
```

Since you asked for the bins last time, I've uploaded them here: [error_prone_bins](https://drive.google.com/open?id=1ra5-J1I6-ikpkW7RzaXHJDLTAAH_mCHL) or [alternate_link](https://drive.google.com/open?id=1oUvCz2A5sy20-CHAHVAZtselqABkbiRI)

Sorry about reopening a closed issue and thanks for helping with this!
-Susheel

**Comment by susheelbhanu** [comment]
Update: I deleted the output folder, re-ran it on the same bin folder, and it ran fine the second time around.

**Comment by aaronmussig** [comment]
Hello, thanks for sharing the data but unfortunately I wasn't able to reproduce the error. Specifically, that error is thrown when the align step verifies that an output has been generated for each genome in the identify step. That exception was really only put in place to assert that if someone is manually running the commands individually, they haven't accidentally selected the wrong identify directory.

Looking at your error message it indicates that the following inputs were expected but not present. Given that these weren't in the data shared it's likely that your command was run on a directory which had output already in it (from a different GTDB-Tk run, which probably included those genomes below).
```
bwa_sr_metaspades_hybrid.metabat.23
bwa_sr_metaspades_hybrid.metabat.28
bwa_sr_metaspades_hybrid.metabat.30_sub
bwa_sr_metaspades_hybrid.metabat.32
bwa_sr_metaspades_hybrid.metabat.37
bwa_sr_metaspades_hybrid.metabat.38
bwa_sr_metaspades_hybrid.metabat.45
bwa_sr_metaspades_hybrid.metabat.61
bwa_sr_metaspades_hybrid.metabat.8
maxbin_output.011
maxbin_output.022
maxbin_output.043_sub
```

**Comment by susheelbhanu** [comment]
Sure, thanks @aaronmussig. I've run it since on other data and so far haven't run into this issue again. Thanks for the help!
