### ISSUE TITLE
Discrepancies in ftp 

### ISSUE THREAD

**Issue by adityabandla** [Ecogenomics/GTDBTk#250]
The first & third files referred to here are the same but with different descriptions https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/FILE_DESCRIPTIONS

Also for most of the individual genes, the protein & gene count are < 23, 458, whereas the MSA for that gene consists of 23, 458 genes. 

EDIT: The second part is clear, didn't notice the missing gene's had empty alignments as well

**Comment by dparks1134** [comment]
Hi. Thank you for bringing this to our attention. I have modified the FILE_DESCRIPTIONS file to remove this redundancy and better organize the listed files. It is expected that some genomes will be missing a given marker gene so the gene count will typically be <23,458 in the individual gene files. In the MSA files, missing genes are indicated by a series of dashes so the count is always 23,458.
