### ISSUE TITLE
pplacer exits with error because --mmap-file argument added twice

### ISSUE THREAD

**Issue by aekazakov** [Ecogenomics/GTDBTk#254]
If classify is started with --scratch_dir argument set, pplacer "--mmap-file" argument is added twice :
https://github.com/Ecogenomics/GTDBTk/blob/26f31e4c26f19ea45edeac25e1953a7142ad8906/gtdbtk/classify.py#L127
            pplacer_mmap_file = ' --mmap-file {}'.format(
                os.path.join(scratch_dir, prefix + ".pplacer.scratch"))
https://github.com/Ecogenomics/GTDBTk/blob/26f31e4c26f19ea45edeac25e1953a7142ad8906/gtdbtk/external/pplacer.py#L138
            args.append('--mmap-file')

**Comment by aaronmussig** [comment]
Hello, thanks for raising this. It will be resolved in the next release (1.2.0).

**Comment by aaronmussig** [comment]
This release is now available if you wish to update your environment and try again.
