### ISSUE TITLE
[Question] GTDB-Tk tree's topology is incongruent with ANI values

### ISSUE THREAD

**Issue by apcamargo** [Ecogenomics/GTDBTk#260]
Hey all!

I used GTDB-Tk to classify hundreds of MAGs that I'm working with and I then started to inspect subtrees of the families that were greatly expanded by my genomes. I've noticed that at least for one family (`f__GCA-2861595`) the topology of the tree is incongruent with the ANI values I got from pairwise comparisons with fastANI.

```
/----------------------------------------- GB_GCA_001443545.1 (outgroup from f__Acidimicrobiaceae) 
|
|                                  /------ GB_GCA_002861595.1
|                           /------+
|                    /------+      \------ MAG_1
+                    |      |
|             /------+      \------------- MAG_2
|             |      |
|      /------+      \-------------------- MAG_3
|      |      |
\------+      \--------------------------- MAG_4
       |
       \---------------------------------- MAG_5
```

- MAGs 1 to 5 were assigned to the `f__GCA-2861595` family but were not assigned to any genus, meaning that they are significantly distinct from `GB_GCA_002861595.1` (which belongs to the `g__GCA-2861595` genus).
- Accordingly, MAGs 1 to 5 have pairwise ANI within the 96%–98% range.
- `GB_GCA_002861595.1` and `MAG_1` are forming a monophyletic group which would suggest that they are more closely related to each other than to the other MAGs. However, the ANI between `GB_GCA_002861595.1` and `MAG_1` is around 75% (close to the range where ANI is no longer reliable)

I'm aware that the ANI doesn't necessarily reflect the evolutionary history, but the `within-MAGs` and `between-MAGs-and-GB_GCA_002861595.1` ANIs are different enough to make me suspicious of the tree. I'd expect that my MAGs would be placed within a monophyletic clade corresponding to a new genus of `f__GCA-2861595`.

What may be the issue here? Are subtrees extracted from GTDB-Tk's output reliable enough to be used in downstream analysis?

Thanks!

**Comment by dparks1134** [comment]
GTDB-Tk places genomes into its reference tree using pplacer, a maximum-likelihood method for establishing the position of new genomes in a reference tree. Critically, this is not a _de novo_ tree so your 5 MAGs do not "know" of each other. I do not recommend using this pplacer tree as a substitute for a _de novo_ tree inferred following best practices. GTDB-Tk aims to give you a reliable taxonomic assignment relative to the establish GTDB taxonomy. Currently, GTDB-Tk doesn't indicate if your MAGs should form 1, 2, ..., or 5 distinct genera within `f__GCA-2861595`.

**Comment by apcamargo** [comment]
Got it! Can I use the MSA file to reconstruct the tree myself with `gtdbtk infer` (or FastTree/IQTree)? Should I be aware of any particular detail?

**Comment by dparks1134** [comment]
You can use the MSA. It is designed for domain-level tree inference. If you are working on a particular lineage, it may not be the most appropriate choice of genes. If your tree is small enough I'd recommended IQ-Tree over FastTree.

**Comment by apcamargo** [comment]
for individual families I'm identifying single copy orthologs with OrthoFinder and using IQTree to reconstruct the phylogeny. I'm considering using GTDB-Tk MSA for higher ranks using either FastTree or IQTree's `--fast` mode.

Thank you for your answers, Donovan!

**Comment by dparks1134** [comment]
Best of luck with your research.
