### ISSUE TITLE
Problem about Downloading the GTDB-Tk database

### ISSUE THREAD

**Issue by meganzhang657** [Ecogenomics/GTDBTk#265]
I get an error when I the command "download-db.sh" and the error is as follows：
HTTP request sent, awaiting response... 404 Not Found
2020-07-20 10:38:19 ERROR 404: Not Found.

**Comment by meganzhang657** [comment]
I found that the gtdbtk_data.tar.gz is under /public/gtdb/data/releases/latest/auxillary_files not the /public/gtdb/data/releases/latest/

**Comment by aaronmussig** [comment]
Thanks for mentioning this, I've fixed this in https://github.com/bioconda/bioconda-recipes/pull/23252
Once that has merged and the conda recipe has updated you should be able to automatically use the script.

Until then, the package can still be manually downloaded and extracted. You just need to set the path in the `path_to_conda_env/etc/conda/activate.d/gtdbtk.sh` script.
