### ISSUE TITLE
Chitinispirillia classes in phylum Fibrobacteres present in GTDB but not in AnnoTree

### ISSUE THREAD

**Issue by Jigyasa3** [Ecogenomics/GTDBTk#266]
Hey!

Sorry for a very specific question about bacterial phylum Fibrobacteres. I am examining marker genes for class Chitinispirillia from Annotree (http://annotree.uwaterloo.ca/app/) which has been classified as a separate class since https://www.frontiersin.org/articles/10.3389/fmicb.2016.00407/full was published. But Annotree doesn't include this class. GTDB's "bac120_metadata_r89.tsv" file includes this class, but I cannot find any marker gene associated with this class in Annotree. Am I missing something or the taxonomy of phyla Fibrobacteres in Annotree is based on the old classification system?

Looking forward to your reply!

**Comment by aaronmussig** [comment]
Hello,

As of writing this, annotree is using the R89 taxonomy. I've looked through the R89 metadata file and Chitinispirillia does appear, however, it only appears in the NCBI taxonomy. The GTDB taxonomy is c__Chitinivibrionia which will appear in annotree. If you have any taxonomy related questions I'd recommend getting in touch via the [GTDB contact](https://gtdb.ecogenomic.org/about#5) page as it will reach the curation team.

You may find some more insight by comparing the history for these ranks:
* [p__Fibrobacteres](https://gtdb.ecogenomic.org/taxon_history/?from=R80&to=NCBI&query=p__Fibrobacteres) 
* [c__Chitinispirillia](https://gtdb.ecogenomic.org/taxon_history/?from=R80&to=NCBI&query=c__Chitinispirillia)
