### ISSUE TITLE
No genomes found in directory:

### ISSUE THREAD

**Issue by Timmywang1** [Ecogenomics/GTDBTk#268]
hello, 
 Why didn't I find the genome when I ran it！！！

(gtdbtk) [binhaow@login db]$ gtdbtk classify_wf --genome_dir /share/home/binhaow/metagenomedata3/plants --out_dir 
/share/home/binhaow/metagenomedata3/GTDB-Tk3
[2020-07-27 14:37:16] INFO: GTDB-Tk v1.3.0
[2020-07-27 14:37:16] INFO: gtdbtk classify_wf --genome_dir /share/home/binhaow/metagenomedata3/plants --out_dir /share/home/binhaow/metagenomedata3/GTDB-Tk3
[2020-07-27 14:37:16] INFO: Using GTDB-Tk reference data version r89: /share/home/binhaow/release89
[2020-07-27 14:37:16] WARNING: You are not using the reference data intended for this release: r95
[2020-07-27 14:37:16] ERROR: No genomes found in directory: /share/home/binhaow/metagenomedata3/plants. Check the --extension flag used to identify genomes.

**genomes in direction** /share/home/binhaow/metagenomedata3/plants   as follows:

[binhaow@login plants]$ ll
total 4076
-rw-rw-r-- 1 binhaow binhaow  989338 Jul 27 14:51 bin.10.fa.gz
-rw-rw-r-- 1 binhaow binhaow  506592 Jul 27 14:51 bin.11.fa.gz
-rw-rw-r-- 1 binhaow binhaow  766799 Jul 27 14:51 bin.12.fa.gz
-rw-rw-r-- 1 binhaow binhaow 1041591 Jul 27 14:51 bin.13.fa.gz
-rw-rw-r-- 1 binhaow binhaow  856647 Jul 27 14:51 bin.1.fa.gz

**Comment by aaronmussig** [comment]
By default, GTDB-Tk looks for files with the extension with `fna`. You have gzipped genomes so you need to use `--extension gz`

Note that you're using the R89 reference data so I'd strongly recommend downloading the R95 reference data.

**Comment by Timmywang1** [comment]
Thanks for your suggestions! how to downloading the R95 reference data? which website/links？

**Comment by aaronmussig** [comment]
1. Download this file [gtdbtk_r95_data.tar.gz](https://data.ace.uq.edu.au/public/gtdb/data/releases/release95/95.0/auxillary_files/gtdbtk_r95_data.tar.gz)
2. Extract the archive.
3. Set the environment variable `GTDBTK_DATA_PATH` to point to that directory. If you're using conda then you will need to set it in the `activate.d/gtdbtk.sh` file as shown [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#saving-environment-variables)
