### ISSUE TITLE
download-db.sh references outdated database location

### ISSUE THREAD

**Issue by krwaring** [Ecogenomics/GTDBTk#269]
Hello,
Line 6 in bin/download-db.sh:

> wget https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz

references a broken link. The correct link appears to be: 

> wget https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by aaronmussig** [comment]
Hello,

The `download-db.sh` script has been updated in #265. Create a new conda environment and install the latest version of the GTDB-Tk conda package into it, e.g. `conda create -n gtdbtk-1.3.0 -c bioconda gtdbtk=1.3.0`.

Alternatively, update the file and manually set the file path yourself to the desired version [here](https://data.ace.uq.edu.au/public/gtdb/data/releases/)
