### ISSUE TITLE
GTDB to report Checkm results

### ISSUE THREAD

**Issue by Kirk3gaard** [Ecogenomics/GTDBTk#272]
Hi

Thanks for yet another great tool. I have been thinking about whether gtdb could have a --report-checkm option? It seems that a lot of the processes running in gtdb-tk and checkm overlap (prodigal, pplacer etc) and it would be cool to have both the gtdb classification + completeness, contamination etc metrics without running both tools. 

Best regards
Rasmus

**Comment by dparks1134** [comment]
At the moment, the overlap is limited to the gene calling with Prodigal as GTDB-Tk and CheckM use different backend reference trees with pplacer.
