### ISSUE TITLE
Pplacer error (ValueError) on last step: not a memory issue?

### ISSUE THREAD

**Issue by brookeweigel** [Ecogenomics/GTDBTk#275]
## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)
gtdbtk 0.3.2 py27_1 bioconda

## Server information
Running on the University of Chicago's Midway2 server, with 250 GB of memory so this shouldn't be the problem
#SBATCH --partition=bigmem2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=250G
#SBATCH --time=35:00:00

## Debugging information
- [x] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

Hello! I am having an issue with the final step of the classify code, with pplacer. 

This is the code that I am running, after successfully running infer & align:
## Submit the classify code
gtdbtk classify --batchfile /project2/cpfister/nereoblade/emily_assemblies/Nereo_MAG_paths_2.txt --align_dir /project2/cpfister/nereoblade/emily_assemblies/12_GTDB_classify/align_output/ --out_dir /project2/cpfister/nereoblade/emily_assemblies/12_GTDB_classify/classify_output

# Here is the gtdbtk.log output:
[2020-09-12 13:40:44] INFO: GTDB-Tk v0.3.2
[2020-09-12 13:40:44] INFO: gtdbtk classify --batchfile /project2/cpfister/nereoblade/emily_assemblies/Nereo_MAG_paths_2.txt --align_dir /project2/cpfister/nereoblade/emily_assemblies/12_GTDB_classify/align_output/ --out_dir /project2/cpfister/nereoblade/emily_assemblies/12_GTDB_classify/classify_output
[2020-09-12 13:40:44] INFO: Using GTDB-Tk reference data version r95: /project2/cpfister/genome_taxonomy_database/release95/
[2020-09-12 13:40:44] INFO: Placing 84 bacterial genomes into reference tree with pplacer (be patient).
[2020-09-12 14:45:42] INFO: Calculating average nucleotide identity using FastANI.
[2020-09-12 14:45:46] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: ValueError
  MESSAGE: Stop!!
________________________________________________________________________________

Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 610, in parse_options
    self.classify(options)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 415, in classify
    options.debug)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 446, in run
    raise ValueError("Stop!!")
ValueError: Stop!!
================================================================================

## Allocating memory for internal nodes... done. & Caching likelihood information on reference tree... done.

[brookeweigel@midway2-login2 pplacer]$ cat pplacer.bac120.out
Running pplacer v1.1.alpha19-0-g807f6f3 analysis on /project2/cpfister/nereoblade/emily_assemblies/12_GTDB_classify/align_output/align/gtdbtk.bac120.user_msa.fasta...
Didn't find any reference sequences in given alignment file. Using supplied reference alignment.
Pre-masking sequences... sequence length cut from 5040 to 5040.
Determining figs... figs disabled.
Allocating memory for internal nodes... done.
Caching likelihood information on reference tree... done.
Pulling exponents... done.
Preparing the edges for baseball... done.
working on g2_MAG_00024 (1/84)...
working on g2_MAG_00023 (2/84)...
working on g2_Bin_00049 (3/84)...
working on g2_MAG_00001 (4/84)...
working on g2_MAG_00016 (5/84)...
working on g2_MAG_00025 (6/84)...
working on g4_MAG_00003 (7/84)...
working on g2_MAG_00005 (8/84)...
working on g2_MAG_00034 (9/84)...
working on g3_MAG_00023 (10/84)...
working on g2_MAG_00013 (11/84)...
working on g3_MAG_00015 (12/84)...
working on g2_MAG_00030 (13/84)...
working on g1_MAG_00010 (14/84)...
working on g2_MAG_00002 (15/84)...
working on g3_MAG_00004 (16/84)...
working on g3_MAG_00024 (17/84)...
working on g2_MAG_00012 (18/84)...
working on g2_MAG_00006 (19/84)...
working on g3_MAG_00018 (20/84)...
working on g2_MAG_00027 (21/84)...
working on g3_MAG_00012 (22/84)...
working on g2_MAG_00007 (23/84)...
working on g2_MAG_00017 (24/84)...
working on g1_MAG_00013 (25/84)...
working on g2_MAG_00036 (26/84)...
working on g4_MAG_00002 (27/84)...
working on g2_MAG_00037 (28/84)...
working on g2_MAG_00018 (29/84)...
working on g3_MAG_00016 (30/84)...
working on g3_MAG_00010 (31/84)...
working on g3_MAG_00021 (32/84)...
working on g2_Bin_00040 (33/84)...
working on g3_MAG_00019 (34/84)...
working on g3_MAG_00006 (35/84)...
working on g3_MAG_00014 (36/84)...
working on g2_MAG_00003 (37/84)...
working on g3_MAG_00005 (38/84)...
working on g2_MAG_00033 (39/84)...
working on g3_MAG_00008 (40/84)...
working on g2_MAG_00038 (41/84)...
working on g3_MAG_00020 (42/84)...
working on g1_MAG_00011 (43/84)...
working on g2_MAG_00004 (44/84)...
working on g2_Bin_00044 (45/84)...
working on g2_MAG_00021 (46/84)...
working on g2_MAG_00028 (47/84)...
working on g3_MAG_00011 (48/84)...
working on g3_MAG_00022 (49/84)...
working on g3_MAG_00001 (50/84)...
working on g4_MAG_00001 (51/84)...
working on g4_MAG_00004 (52/84)...
working on g1_MAG_00002 (53/84)...
working on g2_MAG_00015 (54/84)...
working on g3_MAG_00025 (55/84)...
working on g1_MAG_00004 (56/84)...
working on g2_MAG_00019 (57/84)...
working on g3_MAG_00007 (58/84)...
working on g1_MAG_00007 (59/84)...
working on g3_MAG_00003 (60/84)...
working on g3_MAG_00002 (61/84)...
working on g2_MAG_00031 (62/84)...
working on g3_MAG_00009 (63/84)...
working on g2_MAG_00009 (64/84)...
working on g2_Bin_00039 (65/84)...
working on g1_MAG_00005 (66/84)...
working on g2_MAG_00014 (67/84)...
working on g3_MAG_00017 (68/84)...
working on g2_MAG_00010 (69/84)...
working on g2_MAG_00026 (70/84)...
working on g2_MAG_00011 (71/84)...
working on g1_MAG_00003 (72/84)...
working on g2_MAG_00020 (73/84)...
working on g2_MAG_00035 (74/84)...
working on g1_MAG_00009 (75/84)...
working on g2_Bin_00051 (76/84)...
working on g2_MAG_00029 (77/84)...
working on g1_MAG_00006 (78/84)...
working on g2_MAG_00008 (79/84)...
working on g1_MAG_00012 (80/84)...
working on g2_MAG_00032 (81/84)...
working on g3_MAG_00013 (82/84)...
working on g1_MAG_00008 (83/84)...
working on g2_MAG_00022 (84/84)...

## See:
(gtdbtk) [brookeweigel@midway2-login2 intermediate_results]$ cat gtdbtk.bac120.classification_pplacer.tsv
g2_MAG_00035	d__Bacteria;p__Cyanobacteria;c__Cyanobacteriia;o__Cyanobacteriales;f__Cyanobacteriaceae;g__;s__
g2_Bin_00040	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Cellvibrionaceae;g__;s__
g2_MAG_00021	d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__HTCC2089;g__;s__

## But the main results file only has headings, with no ANI or other info:

(gtdbtk) [brookeweigel@midway2-login2 classify]$ cat gtdbtk.bac120.summary.tsv
user_genome	classification	fastani_reference	fastani_reference_radius	fastani_taxonomy	fastani_ani	fastani_af	closest_placement_reference	closest_placement_taxonomy	closest_placement_ani	closest_placement_af	pplacer_taxonomy	classification_method	note	other_related_references(genome_id,species_name,radius,ANI,AF)	aa_percent	translation_table	red_value	warnings
(gtdbtk) [brookeweigel@midway2-login2 classify]$ 

## After looking into my sbatch script logfile, here is the error:
[brookeweigel@midway2-login2 12_GTDB_classify]$ cat GTDB_classify.err
Process Process-2:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 1072, in _fastaniWorker
    userleaf, potential_nodes, genomes)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 1307, in _calculate_fastani_distance
    raise error
ValueError: FastANI has stopped:
ERROR, skch::validateInputFiles, Could not open 10_BINNING_SUMMARY/g1_MAGs_final/bin_by_bin/g1_MAG_00009/g1_MAG_00009-contigs.fa

## Any help figuring out what is going wrong at the last step would be really appreciated! Thank you so much 👍 
-Brooke

**Comment by pchaumeil** [comment]
Hello Brooke,
I would recommend updating GTDB-Tk to the latest version (1.3.0) and rerun the command. There was some issues regarding the parsing of a batchfile in version 0.3.2. 
Running the most up-to-date version may solve your problem.

Regards,
Pierre

**Comment by brookeweigel** [comment]
Thank you! I will try updating to GTDB-Tk (1.3.0), and see if that helps.
