### ISSUE TITLE
The GTDB-Tk reference data does not exist or is corrupted

### ISSUE THREAD

**Issue by bfrancescol** [Ecogenomics/GTDBTk#278]
Dear GTDB Team,

I have installed GTDB-Tk via conda, exported everything to my path, activated normally the gtdbtk environment, downloaded the latest version (gtdbtk_r95_data.tar.gz) and unarchived the database file (it creates a release95 file), following step-by-step the installation guidelines. Then, after I unarchived the database file, I tried to run the "gtdbtk check_install" and got the following message:

================================================================================
                                     ERROR                                      
________________________________________________________________________________

           The GTDB-Tk reference data does not exist or is corrupted.           
GTDBTK_DATA_PATH=/home/bfroliveira/miniconda3/envs/gtdbtk/share/gtdbtk-0.3.2/db/

   Please compare the checksum to those provided in the download repository.    
          https://github.com/Ecogenomics/GTDBTk#gtdb-tk-reference-data          
================================================================================

Can you please help me that in this issue? I have already downloaded again the reference database (the download process was always concluded with success and the database in its entirety -33GB - appears in the system), unarchived (creation of the release 95 file and again this process went just well)  and the same message is appearing... 

Thanks again and congratulations on the excellent tool, I am looking forward to using it!

Bruno Francesco.

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [X ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by marineLZ** [comment]
Dear bfrancescol ，
I have met the same problem. But, when i restart the server，this problem was solved. Maybe  the configuration file including GTDBTK_DATA_PATH need to be updated. 
Hope this helps!

Lei Zhou

**Comment by aaronmussig** [comment]
Hello,

This issue is due to the reference data being incompatible with the version of GTDB-Tk. To use R95 you will need to use GTDB-Tk version 1.3.0 or greater.

**Comment by bfrancescol** [comment]
Thanks for your replies. I will try to reinstall following your recommendations and let you know if it has worked!
Regards,
Bruno.

**Comment by CarolineOhrman** [comment]
I Installed gtdbtk though conda today and also got this issue. Tested to restart session and I use 1.3.0 so it should be compatible. If I look in the GTDBTK_DATA_PATH /data/users/carodl/miniconda3/envs/gtdbtk/share/gtdbtk-1.3.0/db/ i do not have anything but a empty file named .empty

```_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
capnproto                 0.6.1                hfc679d8_1    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
dendropy                  4.5.1              pyh3252c3a_0    bioconda
fastani                   1.32                 he1c1bb9_0    bioconda
fasttree                  2.1.10               h516909a_4    bioconda
gsl                       2.6                  h294904e_0    conda-forge
gtdbtk                    1.3.0                      py_2    bioconda
hmmer                     3.1b2                         3    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.9.0                2_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
mash                      2.2.2                ha61e061_2    bioconda
ncurses                   6.2                  he1b5a44_2    conda-forge
numpy                     1.19.2           py38hf89b668_1    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pplacer                   1.1.alpha19                   1    bioconda
prodigal                  2.6.3                h516909a_2    bioconda
python                    3.8.6           h852b56e_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by aaronmussig** [comment]
As the reference data is so large, it isn't bundled in the conda install. You can download it manually [as described here](https://ecogenomics.github.io/GTDBTk/installing/bioconda.html), or automatically download it using a [bundled script](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gtdbtk/download-db.sh) in the conda package:  `download-db.sh`

I'll update the GTDB-Tk docs to include the automatic method later today.

**Comment by kimnegrette3** [comment]
Hi! is R95 compatible with gtdbtk 1.4.0 installed with conda? Because I am trying to run the classify workflow and I got the same error 
"The GTDB-Tk reference data does not exist or is corrupted."
Thank you in advance for your help!

**Comment by ntromas** [comment]
Hi, I have a similar issue with gtdbtk-1.4.1 (installed with conda and then I used download-db.sh)

The GTDB-Tk reference data does not exist or is corrupted.           
GTDBTK_DATA_PATH=/home/nico/miniconda3/envs/gtdbtk/share/gtdbtk-1.4.1/db/

Thanks for the help!

**Comment by emrobe** [comment]
Hey guys. Usually this Error stems from incompatible db releases <=> GTDB-Tk releases. Here's the table from GitHub.io GTDBTk:

TDB Release | Minimum version | Maximum version
-- | -- | --
R202 | 1.5.0 | N/A
R95 | 1.3.0 | 1.4.2
R89 | 0.3.0 | 0.1.2
R86.2 | 0.2.1 | 0.2.2
R86 | 0.1.0 | 0.1.6
R83 | 0.0.6 | 0.0.7

**Comment by Longyulin22** [comment]
I couldn't find the location of gtdbtk.sh, so I couldn't properly set the database path.
