### ISSUE TITLE
[Documentation] Update recommended FastANI version in the documentation

### ISSUE THREAD

**Issue by apcamargo** [Ecogenomics/GTDBTk#279]
Hi!

The documentation [recommends installing FastANI >= 1.2](https://ecogenomics.github.io/GTDBTk/faq.html?highlight=deterministic). However, the results provided by this version were still not deterministic (https://github.com/ParBLiSS/FastANI/issues/67) and this was fixed just on version (1.3.1). Also, version 1.3.2 fixed an issue that caused `--minFraction` to not work well on fragmented genomes (https://github.com/ParBLiSS/FastANI/issues/70).

**Comment by aaronmussig** [comment]
Hello, this has been updated. However, the docker build will not be updated until the next release.
https://github.com/Ecogenomics/GTDBTk/commit/c4428806d591c9b7ff04b88b845dfebab1153ffa
https://github.com/bioconda/bioconda-recipes/pull/24691
