### ISSUE TITLE
fastANI is not on the system path

### ISSUE THREAD

**Issue by fabgenomics** [Ecogenomics/GTDBTk#280]
Hi,
I have an issue running gtdbtk v 1.3.0. I have the error fastANI is not on the system path.
When I run fastANI -h in the same terminal it works. Also fastANI -v gives me version 1.32
Thank you in advance

## Environment
- [ ] Installed via pip (include the output of `pip list`)
Package                       Version            
----------------------------- -------------------
args                          0.1.0              
artic                         1.1.3              
asn1crypto                    0.24.0             
attrs                         19.1.0             
backcall                      0.2.0              
backports-abc                 0.5                
backports.functools-lru-cache 1.5                
biopython                     1.77               
bleach                        3.1.5              
certifi                       2019.11.28         
cffi                          1.12.3             
chardet                       3.0.4              
click                         7.1.2              
clint                         0.5.1              
coloredlogs                   14.0               
colormath                     3.0.0              
conda                         4.8.1              
conda-package-handling        1.6.0              
cryptography                  2.7                
cycler                        0.10.0             
Cython                        0.29.21            
decorator                     4.4.0              
defusedxml                    0.6.0              
DendroPy                      4.4.0              
entrypoints                   0.3                
fast5-research                1.2.20             
flye                          2.8.1              
future                        0.18.2             
gtdbtk                        1.3.0              
h5py                          2.9.0              
humanfriendly                 8.2                
idna                          2.8                
importlib-metadata            1.7.0              
iniconfig                     1.0.1              
ipykernel                     5.3.1              
ipython                       7.16.1             
ipython-genutils              0.2.0              
jedi                          0.17.1             
Jinja2                        2.10.1             
joblib                        0.16.0             
joypy                         0.1.10             
jsonschema                    3.0.1              
jupyter-client                6.1.5              
jupyter-core                  4.6.3              
kiwisolver                    1.1.0              
linecache2                    1.0.0              
lzstring                      1.0.4              
Markdown                      3.2.2              
MarkupSafe                    1.1.1              
matplotlib                    3.1.0              
mistune                       0.8.4              
mkl-fft                       1.0.10             
mkl-random                    1.0.2              
multiqc                       1.9                
NanoFilt                      2.5.0              
nanoget                       1.8.0              
nanomath                      0.23.1             
NanoPlot                      1.25.0             
nanoplotter                   1.10.0             
NanoStat                      1.1.2              
nbconvert                     5.6.1              
nbformat                      4.4.0              
networkx                      2.3                
notebook                      6.0.3              
numpy                         1.17.1             
packaging                     20.4               
pandas                        0.25.1             
pandocfilters                 1.4.2              
parasail                      1.2                
parso                         0.7.0              
patsy                         0.5.1              
pauvre                        0.1.86             
pexpect                       4.8.0              
pickleshare                   0.7.5              
Pillow                        7.2.0              
pip                           19.3.1             
plotly                        4.1.0              
pluggy                        0.13.1             
primalscheme                  1.3.1              
primer3-py                    0.6.1              
progress                      1.5                
progressbar2                  3.51.4             
prometheus-client             0.8.0              
prompt-toolkit                3.0.5              
ptyprocess                    0.6.0              
py                            1.9.0              
pycoQC                        2.5.0.23           
pycosat                       0.6.3              
pycparser                     2.19               
pyfastaq                      3.17.0             
Pygments                      2.6.1              
pyOpenSSL                     19.0.0             
pyparsing                     2.2.2              
pyrsistent                    0.15.2             
pysam                         0.15.3             
PySocks                       1.7.0              
pytest                        6.1.0              
python-dateutil               2.7.3              
python-utils                  2.4.0              
pytz                          2018.5             
PyVCF                         0.6.8              
PyYAML                        5.3.1              
pyzmq                         19.0.1             
reportlab                     3.5.44             
requests                      2.22.0             
retrying                      1.3.3              
ruamel-yaml                   0.15.71            
scikit-learn                  0.23.1             
scipy                         1.3.1              
seaborn                       0.9.0              
Send2Trash                    1.5.0              
setuptools                    44.0.0.post20200106
simplejson                    3.17.0             
singledispatch                3.4.0.3            
six                           1.12.0             
spectra                       0.0.11             
statsmodels                   0.9.0              
terminado                     0.8.3              
testpath                      0.4.4              
threadpoolctl                 2.1.0              
toml                          0.10.1             
tornado                       6.0.2              
tqdm                          4.35.0             
traceback2                    1.4.0              
traitlets                     4.3.2              
unittest2                     1.1.0              
urllib3                       1.24.3             
wcwidth                       0.2.5              
webencodings                  0.5.1              
wheel                         0.33.6             
zipp                          3.1.0

## Server information
- CPU: `Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz`
- RAM: `MemTotal:       32840520 kB`
- OS: `NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`

## Debugging information
- [ ] `[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/5347504/gtdbtk.log)

**Comment by pchaumeil** [comment]
Hello,

I looks like an environment issue, Could you please provide us more information about your server?
Ideally we would need the output of the following commands:

>>  python -c "import os; print(os.environ)"
>>  env
>> which fastANI
Also, are you running GTDB-Tk via a screen or a queuing system?

Thanks,
Pierre

**Comment by fabgenomics** [comment]
Hi, thk for the help.
I'm not on a server, sorry but on a local machine.
Here are both files for the first two commands
[env.txt](https://github.com/Ecogenomics/GTDBTk/files/5353250/env.txt)
[os.env.txt](https://github.com/Ecogenomics/GTDBTk/files/5353251/os.env.txt)
The command which fastANI gives nothing, strange because fastANI -h works !
Thk,
Fabien

**Comment by pchaumeil** [comment]
Hello Fabien,

My suggestion would be to replace the ' \~/programmes/FastANI' and ' \~/programmes/FastANI/fastANI' values in your path with the full paths to fastANI (i.e. /home/linux/programmes/fastANI ).
In the current architecture, Python does not know that '\~' is representing your HOME directory.
This should fix the `which fastANI` command too.

Cheers,
Pierre

**Comment by fabgenomics** [comment]
Hi Pierre,
Thk you very much for solving my problem. It was the "~" in the PATH.
"gtdbtk test" ran without error.
I'll try with my dataset now and let you know.
Best,
Fabien
