### ISSUE TITLE
problem with conda install on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by benopi** [Ecogenomics/GTDBTk#282]
Dear GTDB Team,

After installing  Anaconda3-2020.07-Linux-x86_64 on ubuntu 18.04 LTS 
the standard installation through conda fails without any usable error message
``
conda create -n gtdbtk-1.3.0 -c bioconda gtdbtk=1.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                              

UnsatisfiableError: 
``
Ben Polman

**Comment by aaronmussig** [comment]
Hi Ben,

I was able to replicate this issue, I suspect that this is a fresh install of Anaconda and you've not yet added any third-party channels. When the GTDB-Tk recipe looks for packages it expects to be able to read them from the `conda-forge` and `bioconda` channels in that order (although you specified bioconda manually).

Below are the commands I used to add those channels. Alternatively, you manually specify them each time you run the command as: `conda create -n gtdbtk-1.3.0 -c conda-forge -c bioconda gtdbtk=1.3.0`

```
(base) root@95432e83cca3:/# conda create -n gtdbtk-1.3.0 -c bioconda gtdbtk=1.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

(base) root@95432e83cca3:/# conda config --show-sources

(base) root@95432e83cca3:/# conda config --add channels bioconda
(base) root@95432e83cca3:/# conda config --add channels conda-forge
(base) root@95432e83cca3:/# conda config --show-sources
==> /root/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults

(base) root@95432e83cca3:/# conda create -n gtdbtk-1.3.0 -c bioconda gtdbtk=1.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/anaconda3/envs/gtdbtk-1.3.0

  added / updated specs:
    - gtdbtk=1.3.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    boost-1.70.0               |   py38h9de70de_1         355 KB  conda-forge
    ... etc
```

I'll update the docs to account for fresh installs.

Thanks,
Aaron

**Comment by benopi** [comment]
Thanks Aaron, this fixes my problem
