### ISSUE TITLE
FastANI with multithreading

### ISSUE THREAD

**Issue by fengyuchengdu** [Ecogenomics/GTDBTk#283]
I noticed that step of FastANI did not use multiple cpus even if I set --cpus 32 in the command.
Is there a reason why we shouldn't keep cpu to 1? thanks

**Comment by dparks1134** [comment]
Hi. The multiprocessing happens at the level of GTDB-Tk. That is, if you indicate 32 CPUs, then GTDB-Tk spawns 32 processes and each of these run FastANI on a single input genome using a single CPU.

**Comment by fengyuchengdu** [comment]
Well, it seems that setting 32 cpus globally didn't work as expected. I've got >5000 genomes in this session and the screen stuck at "[2020-10-24 04:49:26] INFO: Calculating average nucleotide identity using FastANI.“ for over 24h, during which much fewer threads were working. 
![image](https://user-images.githubusercontent.com/17246742/97098213-39d3b700-16b5-11eb-9ac8-b324147f82c4.png)

**Comment by aaronmussig** [comment]
Thanks for raising this as it's identified a block of code that can be optimised. Briefly, a couple of DendroPy methods needed to be re-written.

I've opened a pull request (#284) that will make this step almost instant. This will be a part of the next release, which I expect will be ready at the end of this week or next week.
