### ISSUE TITLE
AF value

### ISSUE THREAD

**Issue by Biofarmer** [Ecogenomics/GTDBTk#289]
Hi, I am using gtdb-tk/1.3.0 (fastANI 1.32). May I ask what the default value of AF (alignment fraction)? and can we change it?

Thanks
Shaopu

**Comment by aaronmussig** [comment]
Hi,

The default value is `0.65`, this can be found here: https://github.com/Ecogenomics/GTDBTk/blob/b7caa8cb2d964ff13f0f15a0f4b3ae86d084f9c5/gtdbtk/config/config.py#L178

To override it for `classify` and `classify_wf` that file must be changed, `ani_rep` allows it to be specified manually. I will update the CLI to allow this in a future version.
