### ISSUE TITLE
Example dataset

### ISSUE THREAD

**Issue by Anto007** [Ecogenomics/GTDBTk#29]
Could you please make available an example dataset with the relevant output files so as to get an idea of how the final .tsv looks like? Thanks!

**Comment by pchaumeil** [comment]
The command 
`gtdbtk test --out_dir <path>
`
will apply the classify workflow (classify_wf) to three archaeal genomes. It will create two folders in the output directory, the result directory and the genomes directory which is used as input to GTDB-Tk.
