### ISSUE TITLE
trim_msa python script

### ISSUE THREAD

**Issue by lcottret** [Ecogenomics/GTDBTk#290]
Hi, 
I would like to use the trim_msa python program which is here : 
https://github.com/Ecogenomics/GTDBTk/blob/master/gtdbtk/trim_msa.py

But it does not correspond to the program included in the gtdbk when we install it : https://ecogenomics.github.io/GTDBTk/commands/trim_msa.html .

How can I do to use the python program corresponding to the first link ? I clone the git repository but when I launch python3 gtdbtk/trim_msa.py , it returns this error : 
Traceback (most recent call last):
  File "gtdbtk/trim_msa.py", line 33, in <module>
    import argparse
  File "/home/lcottret/workspaces/Phylogeny/GTDBTk/gtdbtk/argparse.py", line 4, in <module>
    from gtdbtk.biolib_lite.custom_help_formatter import CustomHelpFormatter
  File "/home/lcottret/.local/lib/python3.6/site-packages/gtdbtk/biolib_lite/custom_help_formatter.py", line 30, in <module>
    class ChangeTempAction(argparse.Action):

Any idea ?

Regards,
Ludo Cottret

**Comment by lcottret** [comment]
It's ok : it seems that there is a conflict between argparse.py and the python module argparse...

**Comment by aaronmussig** [comment]
Strange, I'll update it to cli.py to prevent any future conflicts.
