### ISSUE TITLE
Extracting trimmed alignments for specific markers

### ISSUE THREAD

**Issue by wwood** [Ecogenomics/GTDBTk#305]
Hi,

A feature request this is, I suppose. 

I'd like to get trimmed alignments for a subset of markers included in the GTDBtk set. Is it possible to output the trimmed alignments for each marker in individual files. I can get the untrimmed sequences in individual files using `gtdbtk align --skip_trimming` and could process those outside GTDBtk, but was wondering whether it might be possible from within?

Thanks, ben

**Comment by aaronmussig** [comment]
Hi Ben,

GTDB-Tk can't do that specifically but we can look at adding this in the future. If it helps, you can get the untrimmed alignments in individual files for each marker by running `gtdbtk align --debug`, it will output them to `./align/intermediate_files/markers/*.faa`.  Perhaps the `trim_msa` command also needs to be updated to allow you to use the subsampling method used in `gtdbtk/trim_msa.py` when not using the canonical mask.

**Comment by wwood** [comment]
Alrighty, thanks Aaron.
