### ISSUE TITLE
gtdbtk identify not progressing

### ISSUE THREAD

**Issue by Naima16** [Ecogenomics/GTDBTk#308]
Hi
I am trying to run the following command to assign taxonomy to a set of MAGs (on the cluster ): 
gtdbtk identify --genome_dir  /home/naima17/scratch/cholera_nov2020/complete_only_MAGs/dereplicated_genomes  --out_dir /home/naima17/scratch/cholera_nov2020/GTDBK/gtdbtk_id  -x fa --cpus 32

but the process stops at Identifying TIGRFAM protein families (no error message was generated but no progress since 5 days).

from gtdbtk.log :
[2021-02-12 14:05:00] INFO: Using GTDB-Tk reference data version r89: /home/naima17/scratch/gtdbtk_db/release89
[2021-02-12 14:05:00] INFO: Identifying markers in 1088 genomes with 32 threads.
[2021-02-12 14:05:00] INFO: Running Prodigal V2.6.3 to identify genes.
[2021-02-12 14:12:51] INFO: Identifying TIGRFAM protein families.

I am suspecting an out of memory issue but in this case usually the job stops with an error message,
any help will be very appreciated
best
Naïma

**Comment by aaronmussig** [comment]
Hi Naïma, you should be seeing a progress bar streamed to stdout (not the log file) that indicates the progress (i.e. `gtdbtk identify --genome_dir /home/naima17/scratch/cholera_nov2020/complete_only_MAGs/dereplicated_genomes --out_dir /home/naima17/scratch/cholera_nov2020/GTDBK/gtdbtk_id -x fa --cpus 32 > progress_here.log`). If I recall correctly some performance improvements were made to the `identify` command in recent versions that speed up progress. 

If you don't need to use R89, then I would recommend updating to the most recent version of GTDB-Tk, using R95 and see how that goes.

**Comment by Naima16** [comment]
Thanks Aaron

The issue was with the cluster, my job was killed at the end !!
Do you think I can download only the database v95 without re-installing gtdb ??

Best

**Comment by Naima16** [comment]
Sorry Aaron, I mean can we just update 89 to 95, or we have to install the 95 from the start ?

**Comment by aaronmussig** [comment]
Hi Naïma, sorry about the late reply - you will need to download a version of GTDB-Tk that supports R95 and also download the R95 package. You can see which versions are supported here: https://ecogenomics.github.io/GTDBTk/installing/index.html#gtdb-tk-reference-data
