### ISSUE TITLE
Is the file generated using --scratch_dir with pplacer temporary?

### ISSUE THREAD

**Issue by dportik** [Ecogenomics/GTDBTk#309]
Hello,
Hopefully this is a simple question with a straightforward answer. The usage of `--scratch_dir` with pplacer in `classify_wf` creates a large file `NAME.pplacer.scratch` (>100GB). Is this file automatically removed after the steps complete or must it be removed manually?

Thanks!

**Comment by moritzbuck** [comment]
As far as I experienced, yes.
