### ISSUE TITLE
error in config_template.py with release86?

### ISSUE THREAD

**Issue by johanneswerner** [Ecogenomics/GTDBTk#31]
I think there might be an error with the config_template (line 74): 

```python
# MSA file names
CONCAT_BAC120 = MSA_FOLDER + "gtdb_r83_bac120.faa"
CONCAT_AR122 = MSA_FOLDER + "gtdb_r83_ar122.faa"
```

I quickly checked the file `config_template.py`, there are other sections as well where there is r83 in the config template.

**Comment by pchaumeil** [comment]
Hello Johannes,

The config_template.py file has been updated and should now been based on R86.

Regards,
Pierre

**Comment by johanneswerner** [comment]
Hi Pierre, 
thank you for the quick fix. I am running/testing it on my data now.
Kind regards
Johannes

**Comment by johanneswerner** [comment]
Thank you again, everything runs smoothly.
