### ISSUE TITLE
Invalid example in GTDB-Tk documentation

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/GTDBTk#310]
The `de_novo_wf` documentation uses `p__Nanobacteria` as an example, but this is no longer a valid GTDB taxon. It would be good to change this to `p__Undinarchaeota`.

https://ecogenomics.github.io/GTDBTk/commands/de_novo_wf.html#example

**Comment by pchaumeil** [comment]
Documentation has been updated.
