### ISSUE TITLE
Inferring GTDB-Tk results 

### ISSUE THREAD

**Issue by razz1618** [Ecogenomics/GTDBTk#321]
Hi,
I used classify_wf for assigning taxonomy to 127 bacterial MAGs. I am confused in understanding the results as this is the first time I am using GTDB-Tk. I have gone through the documentation but could not resolve my query.

**1) Why there are N/A values in FastANI columns will this be a problem in using the assigned classification for that particular genome?**

**2) Does taxonomic novelty determined using RED means the nome might be a novel taxa?**
**3)For some of my genomes I got a warning as "Genome not assigned to closest species as it falls outside its pre-defined ANI radius". Is there anything I can do to improve the taxonomy so, that I can get species-level identification?

Here is an example of my results-

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/conda_tmp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/conda_tmp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

user_genome | classification | fastani_reference | fastani_reference_radius | fastani_taxonomy | fastani_ani | fastani_af | closest_placement_reference | closest_placement_radius | classification_method | note | other_related_references(genome_id,species_name,radius,ANI,AF) | msa_percent | translation_table | red_value | warnings
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SN_MAG_00001-contigs | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Alteromonadaceae;g__Idiomarina;s__Idiomarina   abyssalis | GCF_900116625.1 | 95 | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Enterobacterales;f__Alteromonadaceae;g__Idiomarina;s__Idiomarina   abyssalis | 97.74 | 0.93 | GCF_900116625.1 | 95 | taxonomic classification defined by topology and ANI | topological placement and ANI have congruent species assignments | GCF_003987255.1, s__Idiomarina ramblicola, 95.0, 86.06, 0.79;   GCF_000008465.1, s__Idiomarina loihiensis, 95.0, 84.52, 0.74;   GCF_900100855.1, s__Idiomarina zobellii, 95.0, 81.28, 0.48; GCF_003987095.1,   s__Idiomarina piscisalsi, 95.0, 81.14, 0.48; GCF_002808045.1, s__Idiomarina   sp002808045, 95.0, 80.76, 0.47; GCF_002211765.1, s__Idiomarina piscisalsi_A,   95.0, 80.7, 0.47; GCF_004362895.1, s__Idiomarina sp002729675, 95.0, 79.85,   0.23; GCF_003987275.1, s__Idiomarina seosinensis, 95.0, 79.74, 0.23;   GCF_001870515.1, s__Idiomarina sp001870515, 95.0, 79.13, 0.15;   GCF_000152885.1, s__Idiomarina baltica, 95.0, 78.94, 0.13; GCF_003987475.1,   s__Idiomarina tyrosinivorans, 95.0, 78.77, 0.13; GCF_003226255.1,   s__Idiomarina fontislapidosi, 95.0, 78.66, 0.14; GCF_003987185.1,   s__Idiomarina aquatica, 95.0, 78.62, 0.23; GCA_002685255.1, s__Idiomarina   sp002685255, 95.0, 78.11, 0.13; GCF_000299895.1, s__Idiomarina xiamenensis,   95.0, 78.06, 0.09 | 98.51 | 11 | N/A | N/A
SN_MAG_00002-contigs | d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Stappiaceae;g__Roseibium;s__ | N/A | N/A | N/A | N/A | N/A | N/A | N/A | taxonomic classification defined by topology and ANI | N/A | GCF_001404515.1, s__Roseibium album, 95.0, 82.19, 0.69; GCF_000521215.1,   s__Roseibium sp000521215, 95.0, 82.06, 0.7; GCF_000158095.2, s__Roseibium   alexandrii, 95.0, 79.6, 0.27; GCF_001999245.1, s__Roseibium aggregatum_A,   95.0, 79.35, 0.35; GCF_002237595.1, s__Roseibium sp002237595, 95.0, 79.21,   0.42; GCF_000168975.1, s__Roseibium aggregatum, 95.0, 79.09, 0.36;   GCF_008107695.1, s__Roseibium sp008107695, 95.0, 79.06, 0.34;   GCF_003075075.1, s__Roseibium sp003075075, 95.0, 78.84, 0.39;   GCF_002906165.1, s__Roseibium marinum, 95.0, 78.83, 0.34; GCF_009363435.1,   s__Roseibium sp009363435, 95.0, 78.71, 0.29; GCF_001624695.1, s__Roseibium   sp001624695, 95.0, 78.68, 0.34; GCF_008107755.1, s__Roseibium sp008107755,   95.0, 78.65, 0.32; GCF_006517275.1, s__Roseibium sp006517275, 95.0, 78.3,   0.24; GCF_001404055.1, s__Roseibium album_A, 95.0, 78.28, 0.28;   GCA_001890945.1, s__Roseibium sp001890945, 95.0, 78.17, 0.28;   GCF_009711415.1, s__Roseibium denhamense, 95.0, 78.16, 0.29; GCF_008477545.1,   s__Roseibium sp008477545, 95.0, 77.85, 0.24; GCF_008711325.1, s__Roseibium   sediminis, 95.0, 77.85, 0.22; GCF_900142725.1, s__Roseibium suaedae, 95.0,   77.8, 0.21; GCF_009650605.1, s__Roseibium sp009650605, 95.0, 77.78, 0.19;   GCF_007830545.1, s__Roseibium hamelinense, 95.0, 77.61, 0.17;   GCF_008711285.1, s__Roseibium aquae, 95.0, 77.6, 0.19; GCF_000148725.1,   s__Roseibium sp000148725, 95.0, 77.51, 0.15; GCA_013373445.1, s__Roseibium   sp013373445, 95.0, 76.83, 0.13 | 97.66 | 11 | 0.987402 | Genome not assigned to closest species as it falls outside its   pre-defined ANI radius
SN_MAG_00003-contigs | d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Rhizobiaceae;g__Georhizobium;s__Georhizobium   profundi | GCF_003952725.1 | 95 | d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Rhizobiaceae;g__Georhizobium;s__Georhizobium   profundi | 96.48 | 0.89 | GCF_003952725.1 | 95 | taxonomic classification defined by topology and ANI | topological placement and ANI have congruent species assignments | GCF_902498825.1, s__Georhizobium sp902498825, 95.0, 89.29, 0.82;   GCF_002750855.1, s__Georhizobium haloflavum, 95.0, 79.34, 0.41 | 98.23 | 11 | N/A | N/A
SN_MAG_00004-contigs | d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Caulobacterales;f__Hyphomonadaceae;g__Hyphomonas;s__ | N/A | N/A | N/A | N/A | N/A | N/A | N/A | taxonomic novelty determined using RED | N/A | N/A | 95.61 | 11 | 0.928427 | N/A

</body>

</html>

**Comment by dparks1134** [comment]
Hi,

N/A values indicate that your genome was not assigned to a GTDB species. This is indicated by your genomes having an unspecified species assignment (i.e. "s__"). However, you can consult how similar your genome is to GTDB species in the "other_related_references" column. The SN_MAG_00004-contigs genomes was sufficiently novel that no ANI calculations were actually performed. In this case, your genome was placed outside the genus Hyphomonas, but ultimately assigned to this genus based on RED. According to GTDB-Tk your genome is a novel species. The SN_MAG_00002-contigs genome was placed within the genus Roseibium and ANI calculated to all Roseibium species. It was not found to be similar to any of these species so is also considered a novel species by GTDB-Tk. 

Cheers,
Donovan

**Comment by razz1618** [comment]
Thanks for the quick and clear response.:relaxed:
