### ISSUE TITLE
Error while running sqm2tables.py

### ISSUE THREAD

**Issue by chandnisidhu** [Ecogenomics/GTDBTk#322]
Hi,

I am getting the following error while running sqm2tables.py. 

`  File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 214, in <module>
    main(parse_args())
  File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 70, in main
    args.trusted_functions, args.ignore_unclassified, customMethods, data_dir)
  File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 227, in parse_orf_table
    orfs['tpm'] = tpm(orfs)
  File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 153, in tpm
    fun_avgLengths['Unmapped'] = sum(funDict['lengths'].values()) / sum(funDict['copies'].values()) # Just use the avg length of all functions for this.
ZeroDivisionError: division by zero
`

Thank you in advance!

Chandni

**Comment by dparks1134** [comment]
Hi. This comment should be directed to the SqueezMeta developers.

**Comment by chandnisidhu** [comment]
Oops! I didn't notice that. I am sorry for the spam.
