### ISSUE TITLE
similar bacteria genomes presented as diverged on the tree, how to interprete?

### ISSUE THREAD

**Issue by xfengnefx** [Ecogenomics/GTDBTk#323]
Hi and thanks for the great tool,

This a question more on the result interpretation side, I believe GTDB-Tk worked as intended. 

I ran GTDB-Tk 1.3.0 with companion data release 95 as `GTDBTK_DATA_PATH=/work/bin_db/GTDB-Tk/release95/ gtdbtk classify_wf --genome_dir ./in --out_dir ./ -x fa --prefix gtdbout --cpus 32 --pplacer_cpus 32 --scratch_dir /work/tmp`. Input folder contained ~700 metagenome bins (outputs from multiple assemblers each assembling a same sample, so there are redundancy), all of which were at least 50% checkM complete, QS>50 and contain no more than 10 contigs. 

Since branch length of the phylogeny tree is an approximation of substitutions per site rate, I expected bin pairs that have low sequence divergence to also have low total branch length toward their common ancestor, e.g. if a and b has a divergence of 0.01% (measured by for example mash), then in the tree they probably share the immediate parent node as the nearest common ancestor, and each has a very short branch length, something like 0.00001.

Checking on the final tree, I found many pairs confirming this expection, but also some pairs indicating otherwise. For instance, sequence M (2335521bp) and H (2335304bp), the mash sequence divergence between them was 0.00014, and minimap2 (-c -xasm5 seqH.fa seqM.fa) reported around 0.1% sequence divergence. The alignment:
```
seqM 2335521 406169 1389217 - seqH 2335304 1319545 2302594 982991 983054 60 NM:i:63 ms:i:981541 AS:i:981541 nn:i:0 tp:A:P cm:i:98175 s1:i:982954 s2:i:5723 de:f:0.0001 zd:i:3 rl:i:0 cg:Z:986M1I20128M1I133933M1I42623M1D38013M1D225247M1D135M1I6164M1D168227M1D174619M1D172800M1I168M
seqM 2335521 1389305 2207025 - seqH 2335304 501740 1319457 817692 817723 60 NM:i:31 ms:i:816896 AS:i:816896 nn:i:0 tp:A:P cm:i:81640 s1:i:817402 s2:i:5723 de:f:0.0000 zd:i:3 rl:i:0 cg:Z:99521M1D38368M1I92249M1I100389M1I52371M1D143786M1D21703M1I200998M1I3541M1I64788M
seqM 2335521 0 373247 - seqH 2335304 0 373240 373207 373249 60 NM:i:42 ms:i:372195 AS:i:372195 nn:i:0 tp:A:P cm:i:37307 s1:i:372661 s2:i:755 de:f:0.0001 rl:i:0 cg:Z:23277M1D42159M1I158467M1I56M1I288M1I45M1I198M2I77M1I975M1I113062M1D34634M
seqM 2335521 2207307 2335521 - seqH 2335304 373241 501462 128201 128222 60 NM:i:21 ms:i:127595 AS:i:127595 nn:i:0 tp:A:P cm:i:12789 s1:i:128047 s2:i:5723 de:f:0.0002 zd:i:1 rl:i:0 cg:Z:81651M1D803M1D717M1D89M1D3310M1D41084M1I354M1D35M1D83M1D87M
seqM 2335521 373247 387992 - seqH 2335304 2320558 2335304 14726 14747 60 NM:i:21 ms:i:14258 AS:i:14258 nn:i:0 tp:A:P cm:i:1460 s1:i:14617 s2:i:5723 de:f:0.0014 zd:i:2 rl:i:0 cg:Z:2089M1D417M1D223M1I12015M
seqM 2335521 388399 390826 - seqH 2335304 2317583 2320024 2398 2441 60 NM:i:43 ms:i:1688 AS:i:1688 nn:i:0 tp:A:P cm:i:189 s1:i:1892 s2:i:5723 de:f:0.0132 zd:i:3 rl:i:0 cg:Z:141M1D321M12D1528M1D437M
seqM 2335521 393072 395367 - seqH 2335304 2313206 2315502 2253 2296 60 NM:i:43 ms:i:1413 AS:i:1413 nn:i:0 tp:A:P cm:i:158 s1:i:1582 s2:i:5723 de:f:0.0187 zd:i:3 rl:i:0 cg:Z:1934M1D361M
seqM 2335521 391575 392970 - seqH 2335304 2315665 2317179 1386 1514 60 NM:i:128 ms:i:1156 AS:i:974 nn:i:0 tp:A:P cm:i:129 s1:i:1292 s2:i:5723 de:f:0.0079 zd:i:3 rl:i:0 cg:Z:89M118D210M1D1096M
seqM 2335521 397943 399817 - seqH 2335304 2308863 2310735 1844 1876 60 NM:i:32 ms:i:1098 AS:i:1098 nn:i:0 tp:A:P cm:i:124 s1:i:1242 s2:i:5723 de:f:0.0171 zd:i:3 rl:i:0 cg:Z:201M1I34M1I187M1I475M1D322M1D115M1I536M
seqM 2335521 400715 402825 - seqH 2335304 2306180 2308297 2075 2118 60 NM:i:43 ms:i:1051 AS:i:1051 nn:i:0 tp:A:P cm:i:139 s1:i:1392 s2:i:5723 de:f:0.0203 zd:i:3 rl:i:0 cg:Z:261M1D165M1D345M1D174M1D199M1D98M1D155M1D46M1D172M1I494M
seqM 2335521 403652 406098 - seqH 2335304 2302665 2305190 2376 2552 60 NM:i:176 ms:i:872 AS:i:959 nn:i:0 tp:A:P cm:i:169 s1:i:1692 s2:i:5723 de:f:0.0214 zd:i:3 rl:i:0 cg:Z:39M1I155M1I1042M13I38M8D122M96D2M11I208M1D204M1I170M1D439M
seqM 2335521 395445 396576 - seqH 2335304 2311960 2313092 1098 1132 60 NM:i:34 ms:i:555 AS:i:429 nn:i:0 tp:A:P cm:i:77 s1:i:771 s2:i:5723 de:f:0.0300 zd:i:3 rl:i:0 cg:Z:393M1D738M
seqM 2335521 396607 397542 - seqH 2335304 2311003 2311929 899 937 60 NM:i:38 ms:i:394 AS:i:229 nn:i:0 tp:A:P cm:i:47 s1:i:471 s2:i:5723 de:f:0.0312 zd:i:3 rl:i:0 cg:Z:23M2D11M9I34M1I346M1I510M
```
While in the tree, the placement looked like:
```
...
  <clade>
    <branch_length>0.034093</branch_length>
    <clade>
      <branch_length>1.19603E-4</branch_length>
      <clade>
        <branch_length>4.82801E-4</branch_length>
        <clade>
          <branch_length>0.0575237</branch_length>
          <clade>
            <name>GB_GCA_003150135.1</name>
            <branch_length>0.157621</branch_length>
          </clade>
          <clade>
            <name>somethingelse1</name>
            <branch_length>0.120604</branch_length>
          </clade>
        </clade>
        <clade>
          <name>seq_H</name>
          <branch_length>0.216695</branch_length>
        </clade>
      </clade>
      <clade>
        <name>seq_M</name>
        <branch_length>0.217179</branch_length>
      </clade>
    </clade>
    <clade>
      <name>somethingelse2</name>
      <branch_length>0.216329</branch_length>
    </clade>
  </clade>
...
```
The branch length of 0.21 looks like they are different species. I briefly checked the reference tree and found that in the same genus, the reference assemblies (i.e. leaf nodes named *GC[AF]_*) usually have branch lengths of 0.01~0.1, so 0.2 would fall to the higher end, suggesting them to be two quite difference species, which is a different take comparing to the sequence divergence's suggestion. 

In this particualr case, I would tend to trust sequence divergence more, since it's whole genome alignment, but I expected to utilize GTDB-Tk's phylogeny placement to resolve bin duplications for the less complete bins, where alignment results can be ambiguous to interprete.

I think my question is, is the above case an artifact on sequence divergence approach's or GTDB-Tk approach's side? Is it a good idea to use the phylogeny tree to dereplicate bins / estimate bin similarity in general? 

Thanks!

**Comment by dparks1134** [comment]
Hi. Does GTDB-Tk place M and H in the same species? This would be determined using FastANI values in GTDB-Tk assuming the two genomes are placed in the same genus. The branch length issue could be an artifact of contamination or missing data. That is, the tree is based on only 122 genes while Mash and FastANI are based on a comparison of the entire genome.

**Comment by xfengnefx** [comment]
Hi thanks for the reply!
In the run.bac120.summary.tsv file, taxonomy wasn't annotated to species level, but they share the closest referecen assembly. Lines are:
```
seqH d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__  N/A     N/A     N/A     N/A     N/A     GCA_003150135.1 95.0    d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__CAG-448 sp003150135       76.66   0.04    d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__  taxonomic classification defined by topology and ANI    N/A     GCA_000433415.1, s__CAG-448 sp000433415, 95.0, 76.61, 0.04; GCA_002315325.1, s__CAG-448 sp002315325, 95.0, 76.11, 0.03  94.23   11      0.9245900228904004      N/A

seqM     d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__  N/A     N/A     N/A     N/A     N/A     GCA_003150135.1 95.0    d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__CAG-448 sp003150135       76.56   0.04    d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Oscillospirales;f__CAG-272;g__CAG-448;s__  taxonomic classification defined by topology and ANI    N/A     GCA_000433415.1, s__CAG-448 sp000433415, 95.0, 76.72, 0.04; GCA_002315325.1, s__CAG-448 sp002315325, 95.0, 76.19, 0.03  94.92   11      0.9244207971908666      N/A
```
Would the family/genus names being numbered (e.g. the CAG-448) rather than "named" (the more classical taxonomy?) imply more chances of artifacts?

**Comment by dparks1134** [comment]
GTDB-Tk isn't able to resolve if two genomes belong to the same novel species. Your analysis would suggest these genomes do belong to the same species though I would verify this with FastANI or some other ANI tool. Mash is a rough approximation to ANI. These genomes being assigned to g__CAG-448 indicate they are in a novel genus likely comprised on only MAGs. This could present some issues in so far as many of these genomes may be only partial and have some level of contamination.

**Comment by xfengnefx** [comment]
Thank you very much for the explanation!
