### ISSUE TITLE
File not found: release202/markers/pfam/individual_hmms/PF01868.11.hmm

### ISSUE THREAD

**Issue by Anna-pro** [Ecogenomics/GTDBTk#325]
## Environment
- [ . ] Installed via pip (include the output of `pip list`)

- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo` 
- Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz 40
- RAM: `grep "^MemTotal" /proc/meminfo` 
- 196396848 kB
- OS: `cat /etc/os-release` 
- NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

## Debugging information
- [ .] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

I tried to run it with several different genomes, but it is always end up with the error, that file PF01868.11.hmm is not found in the last released reference data. Is there a way how I can loaded separately? I used --force function, but it didn't help to go through this error.

> [2021-06-18 13:45:24] INFO: Identifying markers in 27 genomes with 8 threads.
[2021-06-18 13:45:24] TASK: Running Prodigal V2.6.2 to identify genes.
^M==> Processed 0/27 genomes (0%) |               | [?genome/s, ETA ?]^M==> Processed 1/27 genomes (4%) |▌              | [ 3.04s/genome, ETA 01:19]^M==> Processed 2/27 genomes (7%) |█              | [ 3.18s/genome, ETA$
^M[2021-06-18 13:46:03] TASK: Identifying TIGRFAM protein families.
^M==> Processed 0/27 genomes (0%) |               | [?genome/s, ETA ?]^M==> Processed 1/27 genomes (4%) |▌              | [ 2.81s/genome, ETA 01:13]^M==> Processed 2/27 genomes (7%) |█              | [ 2.57s/genome, ETA$
^M[2021-06-18 13:46:19] TASK: Identifying Pfam protein families.
^M==> Processed 0/27 genomes (0%) |               | [?genome/s, ETA ?]^M==> Processed 1/27 genomes (4%) |▌              | [ 2.65genome/s, ETA 00:09]^M==> Processed 4/27 genomes (15%) |██▏            | [ 2.91genome/s, ET$
^M^M==> Processed 0/27 genomes (0%) |               | [?genome/s, ETA ?]^M==> Processed 5/27 genomes (19%) |██▊            | [40.39genome/s, ETA 00:00]^M==> Processed 10/27 genomes (37%) |█████▌         | [40.50genome/s$
[2021-06-18 13:46:21] TASK: Summarising identified marker genes.
[2021-06-18 13:46:22] INFO: Completed 27 genomes in 0.60 seconds (45.13 genomes/second).
[2021-06-18 13:46:22] INFO: Done.
[2021-06-18 13:46:22] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: '/path/to/gtdb/release202/markers/pfam/individual_hmms/PF01868.11.hmm'

**Comment by RahiPraveen** [comment]
I am also getting similar error while processing 54 genomes:
 ERROR: Input file does not exist: /tmp/tmpl4th9zaugtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_GCF_013283645.1.gff
Process Process-3:1:1:
Traceback (most recent call last):
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 313, in __init__
    check_file_exists(filename)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/common.py", line 96, in check_file_exists
    raise BioLibFileNotFound('Input file does not exist: ' + input_file)
gtdbtk.biolib_lite.exceptions.BioLibFileNotFound: Input file does not exist: /tmp/tmpl4th9zaugtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_GCF_013283645.1.gff

**Comment by RahiPraveen** [comment]
gtdbtk.biolib_lite.exceptions.BioLibFileNotFound: Input file does not exist: /tmp/tmpu5ref0kbgtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_G283645.1.gff
Process Process-3:
Traceback (most recent call last):
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 141, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 107, in _run_prodigal
    raise Exception("An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
==> Processed 52/54 genomes (96%) |██████████████▍| [87.36genome/s, ETA 00:00][2021-06-19 17:22:08] ERROR: Controlled exit resulting from an unrecoe error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal.

**Comment by aaronmussig** [comment]
Hi @Anna-pro your error is caused by using a GTDB-Tk version which is not written for Release 202 (i.e. < 1.5.0). The `PF01868.11.hmm` was updated to `PF01868.17.hmm` in R202.

@RahiPraveen I've created issue #327 and I'll look at it there.

**Comment by Anna-pro** [comment]
Hi @aaronmussig , thank you for your comment, I've re-installed it and seems that it is working now.
