### ISSUE TITLE
EXCEPTION: ValueError   MESSAGE: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by kimseonw** [Ecogenomics/GTDBTk#326]
Hello.
gtdbtk classify_wf exited with error, not enough values to unpack (expected 2, got 1).
May I know the meaning of this error and how to solve it?
Thanks much.
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/6679590/gtdbtk.log)

**Comment by aaronmussig** [comment]
Hello,
Thank you for providing the log, are you able to provide the file `/data/output1000bp/identify/gtdbtk.translation_table_summary.tsv` please?
Thanks!

**Comment by kimseonw** [comment]
Thank you for your response. Please find the attached file.

*Thanks and regards,*
*Seon Woo Kim*

**Comment by aaronmussig** [comment]
GitHub removed the attachment when replying via e-mail, can you please upload it directly to GitHub when you get a chance? Thanks

**Comment by kimseonw** [comment]
Thanks much again. Sorry for any inconveniences. I just change the extension to attach here. Thank you!!
[gtdbtk.translation_table_summary.txt](https://github.com/Ecogenomics/GTDBTk/files/6683511/gtdbtk.translation_table_summary.txt)

**Comment by aaronmussig** [comment]
Thanks for providing the file, unfortunately it's as I expected - one of the names is blank. 

I would like to compare the list of input genomes to those in the translation table file to find out which name disappeared.

Are you able to provide a list of input files ( `ls -l /data/genomes`?) thanks for working with me on this.

**Comment by kimseonw** [comment]
I thank you!. Please find the attachment.
[GenomeList.txt](https://github.com/Ecogenomics/GTDBTk/files/6686508/GenomeList.txt)

**Comment by aaronmussig** [comment]
There's something strange going on with the genome list, the directory listing contains `3,119` genomes, but GTDB-Tk has found `3,120` genomes. 

Based on your command, GTDB-Tk will look for all files that end in `.fasta` in the directory `/data/genomes` and check to make sure they exist. If it's reporting `3,120` then surely there is a hidden file in that directory.

A couple of follow up questions:
* Does the file `/data/genomes/.fasta` exist?
* Does `ls -la /data/genomes` produce the same output as `ls -l /data/genomes`

Thanks!

**Comment by kimseonw** [comment]
Hi Aaron,
Thank you very much for your help! I found hidden .fasta file which I don't know about.
I sincerely appreciate your huge help!!
Thanks!!

**Comment by aaronmussig** [comment]
Great news! I'll add a check in version 1.5.1 that deals with this case, thanks!
