### ISSUE TITLE
md5sum check

### ISSUE THREAD

**Issue by caris1988** [Ecogenomics/GTDBTk#329]
Hello, can anyone show me the md5sum value of the file gtdbtk_r202_data.tar.gz?
I downloaded this file but failed to decompress it (tar: Unexpected EOF in archive). 

Thank you!

**Comment by aaronmussig** [comment]
Hi, you should expect it to be `4986526c2b935fd4dcc2e604c0322517`

**Comment by caris1988** [comment]
Thank you so much. Now I have got the complete file. Hope it can run successfully:)
