### ISSUE TITLE
Interpretation of the results

### ISSUE THREAD

**Issue by zhssakura** [Ecogenomics/GTDBTk#33]
Hi @dparks1134 ,

In the file ‘gtdbtk.ar122.summary.tsv’, the red values are as following:

**user_genome			classification_method		red_value
D6_st10_Refined_2	RED					0.922680053818
B06_st5_Refined_1	RED					0.922131231105
H8_st7_Refined_2		RED					0.921282265825
H13_st5_Refined_3	RED					0.921264499811**

And I also found this info in the file of 'gtdbtk.ar122.red_dictionary.tsv’:
Phylum	0.227534847987
Class	0.35320600176
Order	0.553905413445
Family	0.732652342427
Genus	0.910973866402

Does that mean, these four genomes (D6, B06, H8 and H13) belong to the same genus, however can not sure if they belong to the same species?

Thank you very much!

**Comment by dparks1134** [comment]
What was the taxonomy assigned to each of these genomes by the GTDB-Tk?

**Comment by zhssakura** [comment]
In 'gtdbtk.ar122.classification.tsv' they were:
D6_st10_Refined_2	d__Archaea;p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae;g__Nitrosopumilus
B06_st5_Refined_1	d__Archaea;p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae;g__Nitrosopumilus
H8_st7_Refined_2	d__Archaea;p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae;g__Nitrosopumilus
H13_st5_Refined_3	d__Archaea;p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae;g__Nitrosopumilus

In 'gtdbtk.ar122.classification_pplacer.tsv' they were:
D6_st10_Refined_2	p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae
B06_st5_Refined_1	p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae
H8_st7_Refined_2	p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae
H13_st5_Refined_3	p__Crenarchaeota;c__Nitrososphaeria;o__Nitrososphaerales;f__Nitrosopumilaceae

Thanks!

**Comment by dparks1134** [comment]
The recommended classification is the one given in 'gtdbtk.ar122.classification.tsv'. So, yes, I would say they all belong to the same genus.
