### ISSUE TITLE
Split the genome set

### ISSUE THREAD

**Issue by Biofarmer** [Ecogenomics/GTDBTk#334]
Hi,

I am using gtdb-tk/1.5.0, with gtdbtk classify_wf function. I just wonder is there any difference between running all genomes at once compared to splitting them as several parts. For example, there are 5000 genomes, and the taxonomic annotation of 5000 genome running all at the same time is same or different compared to if I run two times with 2500 and 2500 separately?

Many thanks
Wang

**Comment by dparks1134** [comment]
Hi. GTDB-Tk is not perfectly deterministic due to the genome placement performed by pplacer. Otherwise, the results should not depend on the genomes being run together or in batches.

**Comment by Biofarmer** [comment]
Hi, so what's your suggestion for running around 5000 genomes, together or in batches? thanks, Wang

**Comment by dparks1134** [comment]
Together will be faster since the reference tree will only need to be loaded once. The risk that if something goes wrong (e.g. badly formatted genome that causes GTDB-Tk to crash) you will lose all work. GTDB-Tk doesn't support restarting a partial run at this point so there is some benefit to batching the genomes to guard against such issues.

**Comment by Biofarmer** [comment]
Hi, many thanks for fast reply. so my current understanding is that due to the genome placement performed by pplacer, the annotation results will be slightly different even running the same set of genomes with two times, right? In order to avoid the risk you mentioned, it is better to run the large set of genomes in batches.

**Comment by dparks1134** [comment]
The heuristic nature of pplacer exists regardless of how you process the genomes (i.e. placement may vary slightly even if placing a single genome). If your system and input data is rock solid, run them all at once. If there is a chance GTDB-Tk may crash (i.e. run out of memory, encounter ill-formatted data in your input set), run in batches.

**Comment by Biofarmer** [comment]
Thanks a million for very useful advice.

**Comment by Biofarmer** [comment]
Hello, 
I have updated the version of gtdb-tk to 2.4.0, with gtdbtk classify_wf function. May I again ask whether there will be any differences between running all genomes at once compared to splitting them as several parts and running in batches?
Many thanks
Wang
