### ISSUE TITLE
>50% gaps/ambiguity in MSA

### ISSUE THREAD

**Issue by TianyiChang** [Ecogenomics/GTDBTk#338]
Hi there

I used GTDB-tk (v1.4) to generate MSA and then used it to construct a phylogenetic tree. However, IQ-tree reported that some of the sequences have >50% gaps/ambiguity. As I found GTDB-tk already trimmed the MSA, I wonder if you know what caused this problem, also, do you think it is better to trim the MSA generated by GTDB-tk with other tools (e.g., TrimAL and Gblocks)?

Thank you,
Tianyi

**Comment by aaronmussig** [comment]
Hello, I believe that this issue is more suited to the GTDB forum, if you would like to create a thread there: https://forum.gtdb.ecogenomic.org/c/gtdb-tk/6

Thanks,
Aaron
