### ISSUE TITLE
FastANI fatal error at end of GTDBTk classify_wf

### ISSUE THREAD

**Issue by mshamash** [Ecogenomics/GTDBTk#344]
## Environment
- Using a Singularity container, as part of the nf-core/mag Nextflow workflow, with GTDBtk v1.5.0 from here: https://depot.galaxyproject.org/singularity/gtdbtk:1.5.0--pyhdfd78af_0
- Using R202 of the GTDB taxonomy
- fastANI v1.32

## Server information
- CPU (from within singularity container): `Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz`
- RAM: `200GB` (using scratch; same errors with 260GB RAM from other tests I've done)
- OS: `Debian GNU/Linux 10 (buster)`

## Debugging information
I have attached stderr and stdout, which is what is easily available to me from the Nextflow provided outputs. If the genomes are necessary, I can compile and upload them here.

The GTDBTk command executed is:
`gtdbtk classify_wf --extension fa --genome_dir bins --prefix "gtdbtk.SPAdes-group-P004230" --out_dir "${PWD}" --cpus 10 --pplacer_cpus 10 --scratch_dir pplacer_tmp --min_perc_aa 10 --min_af 0.65`

I've used GTDBTk 1.5.0 before with GTDB R202 without issue. This is the first time I'm trying it within a Singularity container, and as part of a Nextflow workflow, and despite having enough RAM/scratch, something seems to happen during the FastANI step which cases a fatal error.

Briefly, the fatal error looks something like this, and repeats itself many times over:

```
Process-59:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/gtdbtk/external/fastani.py", line 224, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/usr/local/lib/python3.8/site-packages/gtdbtk/external/fastani.py", line 285, in run_proc
    raise GTDBTkExit('FastANI returned a non-zero exit code.')
gtdbtk.exceptions.GTDBTkExit: FastANI returned a non-zero exit code.
==> Processed 2008/2998 comparisons (67%) |██████████     | [16.36comparison/s, ETA 01:00]Process 
```

[stderr.txt](https://github.com/Ecogenomics/GTDBTk/files/7112480/stderr.txt)
[stdout.txt](https://github.com/Ecogenomics/GTDBTk/files/7112481/stdout.txt)

**Comment by mshamash** [comment]
I've done some more debugging/tests:

Using the sample data from here (https://ecogenomics.github.io/GTDBTk/examples/classify_wf.html), the classify_wf command works fine and successfully classifies the 2 test bins - all from within the Singularity container, same exact job specs and classify_wf parameters.

However the datasets I'm testing with still fail. A core dump file is generated, and the gtdbtk log file has the same contents as the files I included above.

**Comment by pchaumeil** [comment]
Hi,
Is the command `fastANI --minFraction 0 -q bins/MEGAHIT-group-T000461.13.fa -r /project/def-cor' generated by GTDB-Tk?
the -r flag of fastANI should point to a fasta file ( path to either a reference genome or a user genome).
Does '/project/def-cor' is the beginning of a full path with a special character in it?
This can be the reason why GTDB-Tk is crashing.

**Comment by mshamash** [comment]
Hi,

I believe that the gdb output was truncated for some reason. That last part after the -r flag is indeed the beginning of a path to some file in our lab's shared project directory. I have not used gdb much historically, so perhaps there is a way to get more info from the core dump than I listed above.

**Comment by pchaumeil** [comment]
ok, 
could you please provide the 'MEGAHIT-group-T000461.13.fa' and the reference genome used for the comparison ( i.e. the -r target file)?

**Comment by mshamash** [comment]
Here is the bin file. As for the reference `GCF_003363715.1_genomic.fna.gz` , it looks like it is a zero byte file, as in empty... I am not sure how/why this happened, but it kinda makes me think that there was an issue with the singularity container binding the file paths for GTDB-tk database. I will look into this tomorrow and get back to you here

Bin file (zipped): [MEGAHIT-group-T000461.13.fa.zip](https://github.com/Ecogenomics/GTDBTk/files/7140466/MEGAHIT-group-T000461.13.fa.zip)

By the way, I found the full path after the -r flag, it is likely this (which is a valid file on our project space): `/project/def-corinnem/mshamash/test/database/fastani/database/GCF/003/363/715/GCF_003363715.1_genomic.fna.gz`

For reference, GTDB-Tk end of log file:

```
[2021-09-07 20:20:33] ERROR: STDERR:
>>>>>>>>>>>>>>>>>>
Reference = [/project/def-corinnem/mshamash/test/database/fastani/database/GCF/003/363/715/GCF_003363715.1_genomic.fna.gz]
Query = [bins/MEGAHIT-group-T000461.13.fa]
Kmer size = 16
Fragment length = 3000
Threads = 1
ANI output file = /tmp/gtdbtk_fastani_tmpeo_nrlep/output.txt
>>>>>>>>>>>>>>>>>>
INFO [thread 0], skch::main, Count of threads executing parallel_for : 1
INFO [thread 0], skch::Sketch::build, window size for minimizer sampling  = 24
INFO [thread 0], skch::Sketch::build, minimizers picked from reference = 0
INFO [thread 0], skch::Sketch::index, unique minimizers = 0
INFO [thread 0], skch::Sketch::computeFreqHist, Frequency histogram of minimizers = (0, 0) ... 
[2021-09-07 20:20:34] ERROR: FastANI returned a non-zero exit code.
[2021-09-07 20:20:34] ERROR: Controlled exit resulting from an unrecoverable error or warning.
```

**Comment by pchaumeil** [comment]
It seems, for some reason, that the reference genome is an empty file.

```
>fastANI --minFraction 0 -q MEGAHIT-group-T000461.13.fa -r /release202/fastani/database/GCF/003/363/715/GCF_003363715.1_genomic.fna.gz -o test.o
>>>>>>>>>>>>>>>>>>
Reference = [release202/fastani/database/GCF/003/363/715/GCF_003363715.1_genomic.fna.gz]
Query = [MEGAHIT-group-T000461.13.fa]
Kmer size = 16
Fragment length = 3000
Threads = 1
ANI output file = test.o
>>>>>>>>>>>>>>>>>>
INFO [thread 0], skch::main, Count of threads executing parallel_for : 1
INFO [thread 0], skch::Sketch::build, window size for minimizer sampling  = 24
INFO [thread 0], skch::Sketch::build, minimizers picked from reference = 407791
INFO [thread 0], skch::Sketch::index, unique minimizers = 399470
INFO [thread 0], skch::Sketch::computeFreqHist, Frequency histogram of minimizers = (1, 395230) ... (86, 1)
INFO [thread 0], skch::Sketch::computeFreqHist, consider all minimizers during lookup.
INFO [thread 0], skch::main, Time spent sketching the reference : 0.334531 sec
INFO [thread 0], skch::main, Time spent mapping fragments in query #1 : 0.482664 sec
INFO [thread 0], skch::main, Time spent post mapping : 0.000110588 sec
INFO [thread 0], skch::main, ready to exit the loop
INFO, skch::main, parallel_for execution finished
```
works well an generate an output but 

```
$ touch GCF_003363715.1_genomic_empty.fna.gz
$ fastANI --minFraction 0 -q MEGAHIT-group-T000461.13.fa -r GCF_003363715.1_genomic_empty.fna.gz -o test.o
>>>>>>>>>>>>>>>>>>
Reference = [GCF_003363715.1_genomic_empty.fna.gz]
Query = [MEGAHIT-group-T000461.13.fa]
Kmer size = 16
Fragment length = 3000
Threads = 1
ANI output file = test.o
>>>>>>>>>>>>>>>>>>
INFO [thread 0], skch::main, Count of threads executing parallel_for : 1
INFO [thread 0], skch::Sketch::build, window size for minimizer sampling  = 24
INFO [thread 0], skch::Sketch::build, minimizers picked from reference = 0
INFO [thread 0], skch::Sketch::index, unique minimizers = 0
INFO [thread 0], skch::Sketch::computeFreqHist, Frequency histogram of minimizers = (0, 0) ... Segmentation fault
```
generates the same type of error as the one your experience. (minimizers picked from reference = 0)

**Comment by mshamash** [comment]
Hi,

Thank you for trying it out on your end! I looked closer at my setup, and the singularity directory bindings were working correctly. Rather, it looks like the GTDB R202 database didn't decompress properly, and that the 0-byte file size was a consequence of this. Not sure if others also had the issue. `gtdbtk check_install` caught the problem:

```
[2021-09-10 12:17:07] INFO:          |-- fastani          HASH MISMATCH c63ce2f6f1b3e967da89940e35a7696bad4e6946
[2021-09-10 12:17:08] INFO:          |-- mrca_red         OK
[2021-09-10 12:17:08] ERROR: Unexpected files were seen, or the reference package is corrupt.
[2021-09-10 12:17:08] ERROR: Controlled exit resulting from an unrecoverable error or warning.
```

I re-extracted the DB, ran `gtdbtk check_install` which passed, and sure enough my bins (including the one above) ran perfectly this time.

Lesson learned! Always run `gtdbtk check_install` before proceeding with analysis! Perhaps I'll recommend this be added to the nf-core/mag pipeline, so the DB is always checked before proceeding further and potentially wasting time and resources.

Appreciate your time and efforts, thanks!
