### ISSUE TITLE
Conflicting version information

### ISSUE THREAD

**Issue by biolene** [Ecogenomics/GTDBTk#347]
I would not call this a real issue, but I installed the latest release of GTDB-Tk from this source code:
https://github.com/Ecogenomics/GTDBTk/archive/refs/tags/1.6.0.tar.gz 
If I then run gtdbtk -v, it reports that the version of the software is 1.5.1. This was probably just forgotten to modify? Still it's a bit confusing, and I also want to be sure that the source code is not in fact by mistake that of version 1.5.1?

Apart from that, cudos for the very nice tool!

**Comment by aaronmussig** [comment]
Hello,

Was this part of an upgrade from `1.5.1` -> `1.6.0`? If that's the case then it may have not been uninstalled correctly.

Does `python -m pip install -U gtdbtk` say that the requirement is already satisfied?

I tried it out in a new Docker container and it seemed to report the right version

```shell
> docker run -v /Users/aaron/Desktop/release202:/refdata -it python:3.8 /bin/bash
> export GTDBTK_DATA_PATH=/refdata
> wget https://github.com/Ecogenomics/GTDBTk/archive/refs/tags/1.6.0.tar.gz
...
2021-09-13 22:40:44 (5.27 MB/s) - ‘1.6.0.tar.gz’ saved [9841799]
> tar -xf 1.6.0.tar.gz
> cd GTDBTk-1.6.0/
> pip install .
Processing /GTDBTk-1.6.0
...
> gtdbtk -v
gtdbtk: version 1.6.0 Copyright 2017 Pierre-Alain Chaumeil, Aaron Mussig and Donovan Parks
```

**Comment by biolene** [comment]
Hi Aaron

You are right, it was indeed a problem with a previous version that still stuck around, sorry about that.
