### ISSUE TITLE
Hmmsearch - Incorrect number of command line arguments error

### ISSUE THREAD

**Issue by pdemaayer** [Ecogenomics/GTDBTk#351]
Good day! 

I have installed GTDB-tk v 1.6.0, but it keeps crashing at the second step, hmmsearch with the following error message:

(base) pieter@BEAST:~/Software$ gtdbtk classify_wf --genome_dir ./Achromo/ --extension fasta --out_dir Aclass/ --cpus 64
[2021-09-27 09:05:56] INFO: GTDB-Tk v1.6.0
[2021-09-27 09:05:56] INFO: gtdbtk classify_wf --genome_dir ./Achromo/ --extension fasta --out_dir Aclass/ --cpus 64
[2021-09-27 09:05:56] INFO: Using GTDB-Tk reference data version r202: /media/pieter/TOSHIBA EXT/GTDB-tk/release202/
[2021-09-27 09:05:56] INFO: Identifying markers in 1 genomes with 64 threads.
[2021-09-27 09:05:56] TASK: Running Prodigal V2.6.3 to identify genes.
[2021-09-27 09:05:56] INFO: Completed 1 genome in 0.08 seconds (12.87 genomes/second).
[2021-09-27 09:05:56] WARNING: Prodigal skipped 1 genome due to pre-existing data, see warnings.log
[2021-09-27 09:05:56] TASK: Identifying TIGRFAM protein families.
==> Processed 0/1 genomes (0%) |               | [?genome/s, ETA ?]Incorrect number of command line arguments.
Usage: hmmsearch [options] <hmmfile> <seqdb>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

Process Process-67:
Traceback (most recent call last):
  File "/home/pieter/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pieter/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/gtdbtk/external/tigrfam_search.py", line 134, in _workerThread
    checksum = sha256(out_file)
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/gtdbtk/tools.py", line 153, in sha256
    with open(input_file, 'rb') as afile:
FileNotFoundError: [Errno 2] No such file or directory: 'Aclass/identify/intermediate_results/marker_genes/TYPE_Achromobacter_aegrifaciens_LMG_26852_GCA_902859735.1_LMG_26852_genomic/TYPE_Achromobacter_aegrifaciens_LMG_26852_GCA_902859735.1_LMG_26852_genomic_tigrfam.tsv'
[2021-09-27 09:05:57] ERROR: An error was encountered while running hmmsearch.
[2021-09-27 09:05:57] ERROR: Controlled exit resulting from an unrecoverable error or warning.

My hmmsearch version is provided here:

(base) pieter@BEAST:~/Software$ hmmsearch -h
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmsearch [options] <hmmfile> <seqdb>

I've tried running it with hmmsearch v 3.3.1 but to no avail. 

Your help would be much appreciated. 

Thanks and regards
Pieter

**Comment by Caiyulu-818** [comment]
I also meet this problem  ERROR: An error was encountered while running hmmsearch.

**Comment by aaronmussig** [comment]
Thanks for reporting this issue, this will be fixed in the next version of GTDB-Tk. 

The TIGRFAM pipeline was not handling the spaces in the reference data path correctly. Feel free to try again without spaces in the reference data path, or wait for the next version.

**Comment by Caiyulu-818** [comment]
> Good day!
> 
> I have installed GTDB-tk v 1.6.0, but it keeps crashing at the second step, hmmsearch with the following error message:
> 
> (base) pieter@BEAST:~/Software$ gtdbtk classify_wf --genome_dir ./Achromo/ --extension fasta --out_dir Aclass/ --cpus 64 [2021-09-27 09:05:56] INFO: GTDB-Tk v1.6.0 [2021-09-27 09:05:56] INFO: gtdbtk classify_wf --genome_dir ./Achromo/ --extension fasta --out_dir Aclass/ --cpus 64 [2021-09-27 09:05:56] INFO: Using GTDB-Tk reference data version r202: /media/pieter/TOSHIBA EXT/GTDB-tk/release202/ [2021-09-27 09:05:56] INFO: Identifying markers in 1 genomes with 64 threads. [2021-09-27 09:05:56] TASK: Running Prodigal V2.6.3 to identify genes. [2021-09-27 09:05:56] INFO: Completed 1 genome in 0.08 seconds (12.87 genomes/second). [2021-09-27 09:05:56] WARNING: Prodigal skipped 1 genome due to pre-existing data, see warnings.log [2021-09-27 09:05:56] TASK: Identifying TIGRFAM protein families. ==> Processed 0/1 genomes (0%) | | [?genome/s, ETA ?]Incorrect number of command line arguments. Usage: hmmsearch [options]
> 
> where most common options are: -h : show brief help on version and usage
> 
> To see more help on available options, do hmmsearch -h
> 
> Process Process-67: Traceback (most recent call last): File "/home/pieter/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/home/pieter/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/pieter/anaconda3/lib/python3.8/site-packages/gtdbtk/external/tigrfam_search.py", line 134, in _workerThread checksum = sha256(out_file) File "/home/pieter/anaconda3/lib/python3.8/site-packages/gtdbtk/tools.py", line 153, in sha256 with open(input_file, 'rb') as afile: FileNotFoundError: [Errno 2] No such file or directory: 'Aclass/identify/intermediate_results/marker_genes/TYPE_Achromobacter_aegrifaciens_LMG_26852_GCA_902859735.1_LMG_26852_genomic/TYPE_Achromobacter_aegrifaciens_LMG_26852_GCA_902859735.1_LMG_26852_genomic_tigrfam.tsv' [2021-09-27 09:05:57] ERROR: An error was encountered while running hmmsearch. [2021-09-27 09:05:57] ERROR: Controlled exit resulting from an unrecoverable error or warning.
> 
> My hmmsearch version is provided here:
> 
> (base) pieter@BEAST:~/Software$ hmmsearch -h
> 
> # hmmsearch :: search profile(s) against a sequence database
> # HMMER 3.1b2 (February 2015); http://hmmer.org/
> # Copyright (C) 2015 Howard Hughes Medical Institute.
> # Freely distributed under the GNU General Public License (GPLv3).
> # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> Usage: hmmsearch [options]
> 
> I've tried running it with hmmsearch v 3.3.1 but to no avail.
> 
> Your help would be much appreciated.
> 
> Thanks and regards Pieter

hello, have you solved this error?
