### ISSUE TITLE
Reference database throws error

### ISSUE THREAD

**Issue by Unaimend** [Ecogenomics/GTDBTk#353]
## Environment

- [x ] Using a conda environment (include the output of `conda list && conda list --revisions`)

Downloading of the reference database does not work, also the --no-check-certificate flag did not help

```
(gtdbme) [sukem127@caucluster2 ~]$ download-db.sh  --no-check-certificate
Downloading the GTDB-Tk database to /work_beegfs/sukem127/yes/envs/gtdbme/share/gtdbtk-1.6.0/db/...
--2021-10-07 13:34:09--  https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz
Resolving data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)... 203.101.230.53
Connecting to data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)|203.101.230.53|:443... connected.
ERROR: cannot verify data.gtdb.ecogenomic.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
```

**Comment by Unaimend** [comment]
As a quick fix I downloaded `gtdb_genomes_reps.tar.gz` from `https://data.gtdb.ecogenomic.org/releases/latest/genomic_files_reps/` but and put into my `db` directory( GTDBTK_DATA_PATH=/work_beegfs/sukem127/yes/envs/gtdbme/share/gtdbtk-1.6.0/db/ `
But I still get the error `The GTDB-Tk reference data does not exist or is corrupted`.
Also the link below does not lead to any checksum
https://github.com/Ecogenomics/GTDBTk#gtdb-tk-reference-data

**Comment by aaronmussig** [comment]
Hi,

The reference data file is the 47GB file `gtdbtk_data.tar.gz` found under [auxillary_files](https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/auxillary_files/). 

Please try downloading that file and setting your environment variable to the extracted archive path. If you want to set the variable each time the conda environment is activated then modify your activate.d file as per step 3 of [GTDBTk/installing/bioconda.html](https://ecogenomics.github.io/GTDBTk/installing/bioconda.html#step-3-download-and-alias-the-gtdb-tk-reference-data)

**Comment by Unaimend** [comment]
Thank you very much for your extensive help
