### ISSUE TITLE
Strange classification for those no close replacement genomes are found but only based on RED and/or topology

### ISSUE THREAD

**Issue by jianshu93** [Ecogenomics/GTDBTk#359]
Dear GTDB-tk team,

I am experiencing something very interesting to explore and want to know your comments on this:

For some genomes that are relatively new, when no close placement genomes can be found, taxonomy are only determined by topology and/or RED (see excel file):

[example_gtdbtk.xlsx](https://github.com/Ecogenomics/GTDBTk/files/7546101/example_gtdbtk.xlsx)

their classification can be strange. I use a brute-force AAI search (it takes months) and found the best AAI hit in the database and then compare AAI (blastp) with RED values (also msa identity, but it does not correlate at all):

![Rplot12](https://user-images.githubusercontent.com/38149286/141982688-0f7e4ab6-4a36-4a4c-a5ca-cd4a2426aeb9.jpg)

If you look at those classified by topology and/or RED (forget ANI because those are already classified by ANI, only a few of them), even those found to be classified at the family level can have high AAI, like 68% to 72%. And those found to be classified as family can also be so low AAI, like 45% and smaller, which I believe should be at least a new order or something. Some very low AAI value can also be classified to genus level. Those results confuses me a lot and made me think whether the RED idea (treeOTU idea is never published) is better compare to full genome AAI idea (slow for now but will be very fast soon), which has been published and cited for 700+ times, TreeOTU is only about 6 citation.

Any idea/comment on this.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
The treeOTU idea is designed for amplicon (same 16S region), but our concatenated universal gene tree is dependent on domain specific tree (universal gene set could also be very different for the same query with different universal gene in the genome due to trimming). Have you tested with the same genome, with another losing half the the universal gene (everything else is exactly the same), is gtdbtk robust to variation of universal gene set in the genome? The full genome AAI is very robust to those genes and very stable even loss more than 1/2 of the universal gene.

Jianshu

**Comment by dparks1134** [comment]
Hi Jianshu,

RED is designed to take into account different rates of evolution unlike using 16S rRNA identity or AAI. As such, RED is not expected to correlate with these measures and indeed we have also observed that the correlation is relatively low. You can find our argument for using RED to establish ranks in the main GTDB manuscript: nature.com/articles/nbt.4229.

Cheers,
Donovan

**Comment by jianshu93** [comment]
Hello Donovan,

Thanks for the clarification. I am well aware of the RED idea, where tree branch length/tip position are considered. My question again is, universal gene binned from metagenomic contig (for MAGs) can be subjected to error, because they are universal so more conservative (think about 16S, very difficult to bin), reads mapping coverage could be overestimated and thus misbinned or not binned. So a classification method robust to changes of very conservative universal genes (they also change the tree topology and RED values), will show more stable classification results. A small try after removing 20% of the universal gene for a 98% completeness MAG changed its classification, which AAI based method do not. Will this be something interesting to discuss/attention?

Thanks,

Jianshu

**Comment by phugenholtz** [comment]
Hi Jianshu

This is definitely an interesting research space and others such as Kostas Konstantinidis favour an AAI based classification over a RED based method applied to a phylogenetic tree.

We favour the latter because AAI is not an explicit phylogenetic approach, it’s similarity based so does not necessarily indicate common ancestry, particularly for more distant relationships.

Re your comment about mis-binning of conserved universal genes, this does not happen often for single copy genes. 16S is an exception because it’s often in multiple copies resulting in repeat collapse and misbinning.

Bw, Phil
