### ISSUE TITLE
No genomes found in directory: path contain bins with fasta format  --extension flag used identify genomes

### ISSUE THREAD

**Issue by alexximalayaunlv** [Ecogenomics/GTDBTk#36]
Hi, I encountered a problem. It seems the software can't find the genomes. It confused me. Do anyone have idea what's wrong with that? Thanks!

**Comment by alexximalayaunlv** [comment]
Hi, thank you for your response. I attached the figure below.
![bin in fasta format](https://user-images.githubusercontent.com/43215426/45445723-02524e00-b699-11e8-8ccc-c3d5ee783c1b.png)
![command used](https://user-images.githubusercontent.com/43215426/45445730-08e0c580-b699-11e8-8fda-c79ff6df336b.png)

**Comment by alexximalayaunlv** [comment]
Hi, the problem solved with the command bleow:gtdbtk classify_wf --cpus 24 --genome_dir ./test --extension fasta --out_dir gtdbtk_output. Thanks for your help!

**Comment by cssulliv** [comment]
Hi,

I also got the same error even after implementing a `--extension fasta flag`. My genomes are .fa files but were refined bins generated from Anvio(v5.5). Within each bin the sequences were divided into splits (20,000 bp length) meaning there are multiple headers denoting those splits (see image). I wanted to know if I will still able to utilize gtdbtk using those bins even though the sequences are split in each bin? 


<img width="714" alt="Screen Shot 2019-08-08 at 1 15 50 PM" src="https://user-images.githubusercontent.com/41393799/62743597-b742d700-b9de-11e9-9a6c-c83b08162160.png">

**Comment by dparks1134** [comment]
Hello. If you bins end with `.fa` you need to pass the flag `--extension fa`. I would **not** recommend using bins were the sequences have been split into 20 kb chunks. GTDB-Tk needs to be able to call genes and the accuracy of this will be compromised by breaking contigs into short fragments.

**Comment by cssulliv** [comment]
Hi!

 I just ran the command on our server and it worked! Thank you! This is a preliminary analysis to see quickly which microbes are in the community. With Anvio I'll be able to remove splits that do not belong and after much refinement will have non-segmented bins. Mahalo nui loa for your help :)
