### ISSUE TITLE
Previously annotated genomes

### ISSUE THREAD

**Issue by kpenn88** [Ecogenomics/GTDBTk#362]
Am I missing something, how do I used GTDB with already annotated genomes that have faa and gbk files previously generated. 

GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum:

GTDB forum:
https://forum.gtdb.ecogenomic.org/

**Comment by pchaumeil** [comment]
We have reopened #13 to reimplement it.
In the next release of GTDB-Tk you should be able to skip already annotated genomes.
