### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by GinaISP** [Ecogenomics/GTDBTk#367]
Hi, I started do use GTDB-TK, I wrote this command line:

gtdbtk decorate --input_tree alberi nano.tree --output_tree alberi_gtdk

usage: gtdbtk
           {de_novo_wf,classify_wf,identify,align,infer,classify,root,decorate,infer_ranks,ani_rep,test,trim_msa,export_msa,check_install}
              ...
gtdbtk: error: unrecognized arguments: nano.tree

How can I resolve?

Thanks

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by pchaumeil** [comment]
Hi,

`gtdbtk decorate --input_tree alberi nano.tree --output_tree alberi_gtdk` gives 2 input files instead of one  **alberi** and **nano.tree** . The command requires only one input file so you will need to remove **nano.tree**
