### ISSUE TITLE
reference data for gtdb-Tk

### ISSUE THREAD

**Issue by parulbaranwal** [Ecogenomics/GTDBTk#368]
Hello, 

I used the following cmd

conda create -n gtdbtk
conda activate gtdbtk
conda install -c bioconda gtdbtk
download-db.sh

Then it showed 

> Downloading the GTDB-Tk database to /home/utad/pbaranw/.conda/envs/gtdbtk/share/gtdbtk-0.3.2/db/...
> --2022-03-16 18:28:36--  https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz
> Resolving data.ace.uq.edu.au (data.ace.uq.edu.au)... 130.102.99.4
> Connecting to data.ace.uq.edu.au (data.ace.uq.edu.au)|130.102.99.4|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2022-03-16 18:28:38 ERROR 404: Not Found.
> 
> tar (child): /home/utad/pbaranw/.conda/envs/gtdbtk/share/gtdbtk-0.3.2/db//gtdbtk_r89_data.tar.gz: Cannot open: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> rm: cannot remove '/home/utad/pbaranw/.conda/envs/gtdbtk/share/gtdbtk-0.3.2/db//gtdbtk_r89_data.tar.gz': No such file or directory
> GTDB-Tk database has been successfully downloaded.

(gtdbtk) pbaranw@enggpz1p23:~/parul/taxonomy$ /home/utad/pbaranw/.conda/envs/gtdbtk/etc/conda/activate.d/gtdbtk.sh
bash: /home/utad/pbaranw/.conda/envs/gtdbtk/etc/conda/activate.d/gtdbtk.sh: Permission denied

I am unable to set the gtdb-tk reference path. Any help highly appreciated.

Thanks

**Comment by pchaumeil** [comment]
Hello,
R89 is not the latest release anymore, this is why this link is broken.
I would recommend using the latest version of GTDB-Tk to run your analysis.

However, if you need the Tk package R89, you can find it here : 
https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz
