### ISSUE TITLE
`classify_wf` tree output - few MAGs missing

### ISSUE THREAD

**Issue by crusher083** [Ecogenomics/GTDBTk#372]
Hi, 

Thank you for the development and 
I build a tree using `classify_wf` command.
Then I'd like to prune all other entries except MAGs from my study, therefore I used `ete3` library and next commands: 
`t = PhyloTree("gtdb_classify_wf_output/gtdbtk.bac120.classify.tree", format=1, quoted_node_names=True)`
When I tried to prune, few MAGs were absent from the bacterial tree, but were classified as Bacteria, namely `['G69147_bin.2', 'G78706_bin.13', 'G69181_bin.4'] `.
What could be the reason for such behaviour?

**Comment by crusher083** [comment]
My log shows, that 3 MAGs weren't classified indeed.
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/8404206/gtdbtk.log)

**Comment by pchaumeil** [comment]
Hello,

We recently received a similar issue from another user ( please see ticket #356 ).
It seems pplacer drops genomes during the placement steps.
If you try to re-run the missing genomes my guess is that they will run through pplacer and GTDB-Tk without issue.

the next version of GTDB-Tk will return a warning for this situation.

Thanks,
Pierre

**Comment by crusher083** [comment]
Thanks for the answer!
