### ISSUE TITLE
How can I get the bac/ar120.classification.tsv?

### ISSUE THREAD

**Issue by alexximalayaunlv** [Ecogenomics/GTDBTk#38]
Hi, I used the code below. But I only got following files: 1.gtdbtk_ar122_markers_summary.tsv 2.gtdbtk_bac120_markers_summary.tsv  3.gtdbtk.log  4.marker_genes. Where can I find the detailed information of the species. Thanks!
![code](https://user-images.githubusercontent.com/43215426/45457397-c0d39a00-b6bc-11e8-91aa-8f45fefd20e1.png)

**Comment by alexximalayaunlv** [comment]
I tried it again. And find their are errors. Do anyone know what's the problem? Thanks!
![new1](https://user-images.githubusercontent.com/43215426/45459688-7dcaf400-b6c7-11e8-9879-0a4153f463cd.png)
![new2](https://user-images.githubusercontent.com/43215426/45459689-7dcaf400-b6c7-11e8-92b0-c04c418522f8.png)

**Comment by pchaumeil** [comment]
Hi,
It looks like one of your sequence, ( Sequence Hedlund.71.filtered ) in your user MSA file is empty ( it's  a string of '-' ) so pplacer cannot place it in the reference tree.

you can filtered out those empty sequences using --min_perc_aa 10 ( as an example) .

Cheers,
Pierre

**Comment by alexximalayaunlv** [comment]
Hi Pierre, thank you for your response. I remove those low quality bins and then run the command again. But there is still some confusing problems as showed below/Users/alex/Desktop/Screen Shot 2018-09-13 at 1.56.55 pm.png. Thanks for your help!

**Comment by alexximalayaunlv** [comment]
Hi Pierre, thank you for your response. After removing those low quality bins, I still encountered following question. Thanks for your help!
<img width="1273" alt="screen shot 2018-09-13 at 1 56 55 pm" src="https://user-images.githubusercontent.com/43215426/45470181-4b6cd580-b75f-11e8-95f9-df5ba94b53fa.png">

**Comment by pchaumeil** [comment]
Hi,
Could you please try to run the pplacer command that is crashing without piping the output to pplacer.bac120.out and return the error genrated by pplacer?

**Comment by alexximalayaunlv** [comment]
Hi Pierre, I found the direction is not correct. Please see the figure below.
<img width="1273" alt="screen shot 2018-09-13 at 2 54 32 pm" src="https://user-images.githubusercontent.com/43215426/45471967-5aef1d00-b765-11e8-94b5-91102d35d244.png">

**Comment by pchaumeil** [comment]
Hi,
You are in the "tmp" directory to run the pplacer command so the relative path the gtdbtk_output is not recognised.
You should run the same command in your .../filtered/bins/ directory

**Comment by alexximalayaunlv** [comment]
Hi, the problem fixed when I enlarged the memory. Although there are some warnings, but the results seem okay to me. Thank you.
