### ISSUE TITLE
gtdb_to_ncbi_majority_vote is broken with the new divide-and-conquer strategy

### ISSUE THREAD

**Issue by fplaza** [Ecogenomics/GTDBTk#380]
Hi,

gtdb_to_ncbi_majority_vote.py does not work with the new divide-and-conquer strategy.
The scripts expects one file (gtdbtk.bac120.classify.tree) which is now split in many chunks.

Could you fix this?

Thanks,
Florian

## Environment
gtdbtk version 2.0.0 installed with conda
gtdb_to_ncbi_majority_vote.py v0.0.3

**Comment by dparks1134** [comment]
Hi Florian,

We are working on this, but the implementation has become complicated with the new GTDB-Tk v2 methodology. Hopefully we will have something in the next week or so.

Cheers,
Donovan

**Comment by dparks1134** [comment]
Hi,

The script has been update to work with the divide-and-conquer approach. You can get the script now in the master branch. Otherwise, it will be part of the next GTDB-Tk release.

Cheers,
Donovan
