### ISSUE TITLE
Parsing summary output

### ISSUE THREAD

**Issue by lfenske-93** [Ecogenomics/GTDBTk#382]
Does anyone know a good way to extract only genus and species from the `gtdbtk.bac120.summary.tsv` for each file?

It would be possible to use `_` as a separator, but with names like _Pseudomonas_E parafulva_A_ it becomes difficult.
Would it be possible to consider using other separators for the last level of classification in order to make parsing easier?

**Comment by pchaumeil** [comment]
You can parse the `gtdbtk.bac120.summary.tsv` using **awk**:

`awk -F  "\t" '{ sub(/.*;s__/, "s__", $2); print $1 "\t" $2 }' gtdbtk.bac120.summary.tsv > parsed_summary.tsv` should return a tab delimited file ( parsed_summary.tsv ) listing only the genome id and the species name from the `gtdbtk.bac120.summary.tsv` file

**Comment by pchaumeil** [comment]
Glad to hear we have resolved the issue. Thank you for letting us know.
