### ISSUE TITLE
gtdbtk v2.0.0 does not produce the same results with and without --full_tree option

### ISSUE THREAD

**Issue by fplaza** [Ecogenomics/GTDBTk#383]
Hi,

I previously annotated some MAGs with gtdbtk v1.7.0 (gtdb r202). These MAGs were annotated at least at family level.
[gtdbtk_r202.bac120.summary.txt](https://github.com/Ecogenomics/GTDBTk/files/8482011/gtdbtk_r202.bac120.summary.txt)

Then, I annotated the same MAGs with gtdbtk v2.0.0 (gtdb r207). To my surprise, the MAGs were only annotated at the order level (Oscillospirales). For all these MAGs, gtdbtk produced the same warning message (Genome has conflicting families between trees, reverse to backbone tree classification.)
[gtdbtk_divide_to_conquer_r207.bac120.summary.txt](https://github.com/Ecogenomics/GTDBTk/files/8482027/gtdbtk_divide_to_conquer_r207.bac120.summary.txt)

Interestingly,  this issue is solved by activating the '--full_tree' option.
[gtdbtk_full_tree_r207.bac120.summary.txt](https://github.com/Ecogenomics/GTDBTk/files/8482051/gtdbtk_full_tree_r207.bac120.summary.txt)

This suggests that the divide to conquer strategy does not work properly in some cases.

**Comment by dparks1134** [comment]
Hi Florian,

Thank you for bringing this to our attention. This is very concerning. Can you send us these MAGs so we can investigate in detail? You can email them to donovan.parks [at] gmail.com.

Thanks,
Donovan

**Comment by pchaumeil** [comment]
Hi Florian,
Thanks for your feedback,
Could you also send the `gtdbtk_divide_to_conquer_r207.bac120.conflict.tsv` located in the classify directory? 

Thanks

**Comment by fplaza** [comment]
Hi Pierre, 

I guess you have already reproduced the bug but here is the file:
[gtdbtk_divide_to_conquer_r207.bac120.conflict.txt](https://github.com/Ecogenomics/GTDBTk/files/8487581/gtdbtk_divide_to_conquer_r207.bac120.conflict.txt)

**Comment by fplaza** [comment]
Hi @dparks1134, 
there is a typo in the updated README (--full-tree instead of --full_tree)

Florian

**Comment by dparks1134** [comment]
Thanks Florian.

**Comment by snayfach** [comment]
Any rough idea when the bug might be fixed? It's a bit tricky to find a system with enough RAM to run with the full tree mode.

**Comment by dparks1134** [comment]
Hi,

Issues has been resolved. Ultimately, just a minor hiccup. We are now just doing a bit more sanity checking. We expect to have an updated version out by the end of next week (May 6).

Cheers,
Donovan

**Comment by snayfach** [comment]
Nearly there with the new release?

**Comment by dparks1134** [comment]
Clearly not going to make the May 6 deadline. :)

I'm hoping next week. 

You can always run the "full tree" version if you have the computational resources.

**Comment by dparks1134** [comment]
GTDB-Tk v2.1.0 has been release and address the issue identified with the divide-and-conquer approach. The divide-and-conquer approach was validate against ~16,000 GEM MAGs to establish that it nearly always (99.93% of the time) gives the same results as the full tree. We are preparing a manuscript with the details.

**Comment by zwets** [comment]
@dparks1134 and @pchaumeil thanks for the new release and the quick fixes. Downloading the r207_v2 database now. Would you mind rerunning the md5sum over the download archive? The MD5SUM file doesn't have the the new database yet. Cheers, Marco

**Comment by aaronmussig** [comment]
Hi @zwets thanks for pointing that out! I've updated the MD5SUM file with the hash `df468d63265e8096d8ca01244cb95f30`
