### ISSUE TITLE
dwonload script doesn't overwrite existing database 

### ISSUE THREAD

**Issue by SilasK** [Ecogenomics/GTDBTk#384]
download script doesn't overwrite existing database and creates a

gtdbtk_r202_data.tar.gz.1

More details: 
https://github.com/metagenome-atlas/atlas/issues/509

**Comment by pchaumeil** [comment]
Hello,
We have updated the download-db.sh script to overwrite the existing package if it exists.

**Comment by SilasK** [comment]
Great. @pchaumeil Could you also ask to look at #398 
Would it be possible to create a minor release or a re-release of the same version, so that the new script ends up in the conda package? 

Thank you
