### ISSUE TITLE
multiple outgroup

### ISSUE THREAD

**Issue by GinaISP** [Ecogenomics/GTDBTk#385]
GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum, or contact the GTDB team directly instead:

GTDB forum:
https://forum.gtdb.ecogenomic.org/

GTDB contact:
https://gtdb.ecogenomic.org/about#5

Hi, is it possible to set a multiple outgroup using de_novo_wf line? I tried using:
gtdbtk de_novo_wf --genome_dir genomes/ --outgroup_taxon p__Undinarchaeota p__Asgardarchaeota etc--archaea --out_dir de_novo_wf --cpus 16

but an error message occurs about outgroup. if possible, what is the correct command line?
Thanks

Gina

**Comment by pchaumeil** [comment]
Hello, 
GTDB-TK requires a single rank (phylum) as outgroup, it is not possible to have multiple outgroup in the de_novo_wf.

**Comment by dparks1134** [comment]
Hi Gina,

GTDB-Tk requires the tree to have a sensible rooting in order to decorate it with the GTDB taxonomy information. However, you can always reroot the tree as you see fit in any tree viewer program later. 

Cheers,
Donovan
