### ISSUE TITLE
Adjust PPLACER_MIN_RAM_BAC/ARC parameters when the divide to conquer strategy is enabled

### ISSUE THREAD

**Issue by fplaza** [Ecogenomics/GTDBTk#387]
Hi,

On a server with 100 Gb of RAM, GTDBTk prints a warning message about RAM consumption of pplacer even if the divide to conquer strategy is enabled.

I think the PPLACER_MIN_RAM_BAC/ARC parameters should be ajusted when the --full_tree flag is off.

Best,
Florian

**Comment by dparks1134** [comment]
Agreed. We've noted this.

@pchaumeil, can we make sure this fix is in place for the next release. Thanks.

**Comment by pchaumeil** [comment]
Thanks for the feedback , We have updated the code and this warning message will be based on the approach you are running ( full_tree or split_tree ).

**Comment by pchaumeil** [comment]
Updated in [v2.1.0](https://github.com/Ecogenomics/GTDBTk/commit/185cebc9d5e986d8de8133773004d6940a4d8f4f)
