### ISSUE TITLE
Making the Sankey fig based on the "gtdbtk.bac120.summary.tsv"  generated  by"GTDB-Tk class_wf"

### ISSUE THREAD

**Issue by B-1991-ing** [Ecogenomics/GTDBTk#389]
Dear GTDB-Tk support team, 

I am trying to make a sankey figure using **the R package - Pavian**, which is based on the "gtdbtk.bac120.summary.tsv" generated  by"GTDB-Tk class_wf". But, the "GTDB-Tk class_wf" -generated results don't like classifiers such as Kraken, KrakenUniq, Kraken 2, Centrifuge and MetaPhlAn have report files for each genome or each sample, which is necessary for making the sankey figure. 

So, could you add one report file or column corresponding to each genome or bin in the file - "gtdbtk.bac120.summary.tsv".  My question may be same as **GTDB to report Checkm results #272**, as I want to make same sankey figure as their paper to give a better visualization of our GTDB-Tk classification results.

**The sankey figure (Singleton et al 2021)**
<img width="854" alt="Screenshot 2022-04-28 at 13 02 47" src="https://user-images.githubusercontent.com/54441633/165738492-af4a6bbd-984b-45bf-8175-e7f5dc934c06.png">

**The Pavian upload page**
<img width="1049" alt="Screenshot 2022-04-28 at 13 09 53" src="https://user-images.githubusercontent.com/54441633/165739612-1911e689-a7ca-4d9c-a7f6-731b11ae13e8.png">

**The Pavian required format**
<img width="1076" alt="Screenshot 2022-04-28 at 13 18 47" src="https://user-images.githubusercontent.com/54441633/165741031-01e44bfb-555b-48e4-8ca0-b441b84e0fd1.png">

Thank you very much.

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear GTDB-Tk support team,

**Update**
For the "gtdbtk.bac120.summary.tsv", which can't be directly uploaded to the R pacekage - pavian. So, people need to extract the information from the table "gtdbtk.bac120.summary.tsv", then create the required format to upload.

**Some example format on pavian**
[SRS011152.profile.txt](https://github.com/Ecogenomics/GTDBTk/files/8598709/SRS011152.profile.txt)
[PT6-RNA.report.txt](https://github.com/Ecogenomics/GTDBTk/files/8598710/PT6-RNA.report.txt)

Best,

Bing

**Comment by dparks1134** [comment]
Hi Bing,

We are making some modifications to the GTDB-Tk summary files in v2.1.0. These may address some of your concerns. However, the overall format will not change substantially. You will likely need to modify the output yourself if you have specific downstream requirements. 

Cheers,
Donovan

**Comment by B-1991-ing** [comment]
Hi Donovan, 

Thank you very much for your reply. And thank you for the quick updating on the GTDB-Tk database version.

And, I will email our HPC support team to ask help on installing the newest version of the GTDB-Tk database.

Best,

Bing
