### ISSUE TITLE
Unsure with choosing which outgroup when making de_novo_tree using "GTDB-Tk gtdbtk de_novo_wf"

### ISSUE THREAD

**Issue by B-1991-ing** [Ecogenomics/GTDBTk#390]
Dear GTDB-Tk support team,

I am trying to make one phylogenetic bacterial genome tree based on the concatenated alignment of 120 single-copy marker gene proteins using **GTDB-Tk gtdbtk de_novo_wf** command line. But, I am not sure that **which outgroup should I set** for this mandatory parameter? 
<img width="557" alt="Screenshot 2022-04-28 at 22 13 38" src="https://user-images.githubusercontent.com/54441633/165837828-ca25e62c-8e15-4591-a444-8689e65eb8e9.png">

One another small question: could you tell **the outgroup used** when making the tree from this unrooted tree (Singleton et al 2021)? As it was also made by GTDB-Tk.
<img width="952" alt="Screenshot 2022-04-28 at 22 21 17" src="https://user-images.githubusercontent.com/54441633/165838939-ec5abf18-adfa-4b16-8ed9-806d111001ee.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear GTDB-Tk support team,

**Update**
For deciding the "--outgroup_taxon", I finally used the " p__Chloroflexota", as I looked through some related questions and answers posted, eg., **how to use --outgroup_taxa in de_novo_wf #120**. 

**Command line**
gtdbtk de_novo_wf --genome_dir ${filtered_output_dir} **--outgroup_taxon p__Chloroflexota** --bacteria --custom_taxonomy_file ${custom_taxonomy_file} --out_dir ${out_dir} --extension fa --cpus 32

Best,

Bing

**Comment by dparks1134** [comment]
Hi Bing,

The correct rooting for the bacterial tree is currently an area of active research. As such, we do not impose a specific rooting and allow the use to use any phylum they see fit. This rooting on a phylum is required for downstream steps in the de novo workflow (namely, decorating it with the GTDB taxonomy). However, the tree should be treated as unroot for most purposes.

Cheers,
Donovan

**Comment by B-1991-ing** [comment]
Hi Donovan,

Thank you very much for your detailed explanation on choosing the tree root. 

Best,

Bing
