### ISSUE TITLE
INFO: FastTree version: (version unavailable)

### ISSUE THREAD

**Issue by B-1991-ing** [Ecogenomics/GTDBTk#391]
Dear GTDB-Tk support team,

I ran the gtdbtk de_novo_wf command lines three times with **fasttree/2.1.11 and fasttree/2.1.10**. But, "**INFO: FastTree version: (version unavailable)**" always occurred in my log file as shown below. Does it mean that the **FastTree** didn't work and affect my results? Also, I got some WARNING, are they just normal warning without having big impact on my tree result?

**Command lines**
module load tools
module load ngs
module load hmmer/3.3.2
module load prodigal/2.6.3
module load gtdbtk/2.0.0 
module load fasttree/2.1.11
module load mash/2.3
module load fastani/1.33
gtdbtk de_novo_wf --genome_dir ${filtered_output_dir} --outgroup_taxon p__Chloroflexota --bacteria --custom_taxonomy_file ${custom_taxonomy_file} --out_dir ${out_dir} --extension fa --cpus 32

 **INFO and WARNING**
**[2022-04-30 20:18:30] INFO: FastTree version: (version unavailable)**
[2022-04-30 20:27:50] WARNING: There are 26 taxa with multiple placements of equal quality.
[2022-04-30 20:27:50] WARNING: These were resolved by placing the label at the most terminal position.
[2022-04-30 20:27:50] WARNING: Ideally, taxonomic assignment of all genomes should be established before tree decoration.

**gtdbtk.log**
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/8598666/gtdbtk.log)

Best,

Bing

**Comment by pchaumeil** [comment]
Hello,

**FastTree version: (version unavailable)** is not a critical error, it only means GTDB-Tk is unable to parse the FastTree output to get the version of the software ( This can happen is the output slightly changes).

The **warnings** GTDB-Tk generates indicate that the de-novo tree inferred by Tk has a different topology and Tk had some conflict when trying to find best placement for each taxon ( in this case 26 taxa). This happens during the decorate step. 
The decorate step is similar to the one used in Phylorank [(Phylorank documentation)](https://github.com/dparks1134/PhyloRank#decorating-a-tree).Like Phylorank , GTDB-Tk creates a <output_tree>-table file listing all taxa and their F-measures to detect any incongruency between the taxonomy and tree topology.
If there is any, the final taxonomy file may list genomes with less( or more) than the standard 7 ranks used in GTDB

**Comment by B-1991-ing** [comment]
Thank you very much for your reply. 

For the conflict when trying to find best placement for each taxon ( in this case 26 taxa), we just need to know it and we can't or don't need to correct it, as Tk already put the 26 taxa somewhere in the tree?

Best,

Bing

**Comment by dparks1134** [comment]
Hi,

Regarding the "multiple placements of equal quality" warning, this indicates that GTDB-Tk was able to identify multiple, equally-good internal nodes to put a taxon label. GTDB-Tk defaults to selecting the internal node that is closest to the leaf nodes. No additional action is required on your part.

Cheers,
Donovan
