### ISSUE TITLE
single copy fasta

### ISSUE THREAD

**Issue by sannareddyk** [Ecogenomics/GTDBTk#392]
Dear team,
I am writing to ask if there is an option to write single copy fasta in the newest version of GTDBTk, v2
I can't find an option ( --write_single_copy_genes) in the **identify pipeline** in the newest version.

Thanks for your help.
Keerthi

**Comment by pchaumeil** [comment]
Hi,
`--write_single_copy_genes` will be available for the '`classify_wf`' command and '`de_novo_wf`' commands in the next version of GTDB-Tk.

**Comment by pchaumeil** [comment]
Available in [v2.1.0](https://github.com/Ecogenomics/GTDBTk/commit/185cebc9d5e986d8de8133773004d6940a4d8f4f)
