### ISSUE TITLE
Mollicutes classification

### ISSUE THREAD

**Issue by avera1988** [Ecogenomics/GTDBTk#394]
Hi,

I have been using GTDB-Tk to classify some MAGs obtained from fish gut environment, some of these MAGs are Mycoplasma or other Mollicutes bacteria. When GTDB-Tk is used it indicates indeed that the MAG is Mycoplasma, but the Phylum and Class were assigned as ```p__Firmicutes;c__Bacilli```  eg:

```
 Bml.final.contigs.megahit.900.fasta.Metabat2.5  d__Bacteria;p__Firmicutes;c__Bacilli;o__Mycoplasmatales;f__Mycoplasmoidaceae;g__Mycoplasma_L;s__        N/A     N/A     N/A     N/A     N/AGCA_904501665.1  95.0    d__Bacteria;p__Firmicutes;c__Bacilli;o__Mycoplasmatales;f__Mycoplasmoidaceae;g__Mycoplasma_L;s__Mycoplasma_L sp904501665        77.99   0.16    d__Bacteria;p__Firmicutes;c__Bacilli;o__Mycoplasmatales;f__Mycoplasmoidaceae;g__Mycoplasma_L;s__    taxonomic classification defined by topology and ANI    N/A     GCA_009884515.1, s__Mycoplasma_L liparidae, 95.0, 77.1, 0.19        75.34   4       0.9161349247116175      N/A
```
However, Mycoplasma belongs to the Tenericutes phylum class Mollicutes.

I ran the GTDBTK with a RefSeq genome of Mycoplasma genitallum GCF_000027325.1 and it says the same p_Firmicutes and c_Bacilli again 

I wonder why GTDBTK is assigning members of the Tenericutes as Firmicutes Bacilli?

Hope you can help me to understand this.

Thank you!

Arturo.

**Comment by dparks1134** [comment]
Hi Arturo,

GTDB-Tk uses the GTDB Taxonomy where Mycoplasma has been reclassified to be within the Bacilli:
https://gtdb.ecogenomic.org/tree?r=f__Mycoplasmataceae

You can find information about the GTDB at the GTDB website (https://gtdb.ecogenomic.org/) or in the GTDB publications:
https://gtdb.ecogenomic.org/about

Cheers,
Donovan

**Comment by avera1988** [comment]
HI Donovan,

Thank you for the clarification. I will check the documentation.

Best!

Arturo.
