### ISSUE TITLE
Number of classified reads

### ISSUE THREAD

**Issue by natchaphon602** [Ecogenomics/GTDBTk#395]
I would like to ask that how we suppose to know how much reads or percentage of reads were classified? I would like to compare it to other analysis method.

**Comment by dparks1134** [comment]
Hi,

GTDB-Tk classifies genomes (MAGs, SAGs, or isolates) and not individual reads. 

Cheers,
Donovan

**Comment by natchaphon602** [comment]
So, if GTDB-Tk classifies entire genome, can it represent as classifies
entire reads (Number of reads of each MAGs)?

**Comment by dparks1134** [comment]
GTDB-Tk doesn't know how many reads in a metagenome were used to construct a given MAG. If you have this information, you could infer how many reads are accounted for by the MAGs classified by GTDB-Tk.

**Comment by natchaphon602** [comment]
I have calculated number of reads from BAM file which are produced from
MetaBAT2 in binning step. Is it mean that the number of classified reads is
equal to the number of MAG reads?

**Comment by aaronmussig** [comment]
There are a few different answers depending on what you're trying to achieve

Broadly, you would need to:
1. Find out what markers were used to infer the GTDB-Tk classification (i.e. what markers were present out of the AR53/BAC120 marker set for your MAG).
2. Find the coordinates for those markers on each contig.
4. Find the coordinates of each read that contributed to that that region of the contig.

This is a pretty involved process and it's outside the scope of GTDB-Tk, but you may be able to work something out if you re-use existing GTDB-Tk code, but none of this is easy to get at. You will need to write your own scripts to do this.
