### ISSUE TITLE
Difference between R207_v1 and R207_v2?

### ISSUE THREAD

**Issue by Anto007** [Ecogenomics/GTDBTk#396]
I was wondering if you could let me know if there are a lot of differences in terms of taxonomy between `R207_v1` and `R207_v2`? I have already got my taxonomy results from classifying my hundreds of MAGs on `GTDB-Tk v2.0.0` (I used the `--full-tree` flag)  using the `R207_v1`. Now that `R207_v2` is available with `GTDB-Tk v2.1.0`, I would like to know if my taxonomy results from using `R207_v1` is going to be wildly different from the ones that could be generated from running `GTDB-Tk v2.1.0` on the latest `R207_v2`?

**Comment by pchaumeil** [comment]
Hi,
`R207_v1` and `R207_v2` are based on the same underlying taxonomy (Release 07-RS207) and you will get the same results running the `gtdbtk classify_wf --full_tree` with `GTDB-Tk v2.0.0`(using `R207_v1`) or `GTDB-Tk v2.1.0`(using `R207_v2`).
The update between the two versions was for the divide-and-conquer approach. This approach was validated against ~16K MAGs to establish that it nearly always (99.93% of the time) gives the same results as the -`-full tree`. We are preparing a manuscript with the details.

**Comment by Anto007** [comment]
Thank you very much for your kind clarification.
