### ISSUE TITLE
The `download-db.sh` script is insensitive to the environmental variable `GTDBTK_DATA_PATH`

### ISSUE THREAD

**Issue by SilasK** [Ecogenomics/GTDBTk#398]
The `download-db.sh` script is insensitive to the environmental variable `GTDBTK_DATA_PATH``

```
export GTDBTK_DATA_PATH=/my/path
echo $GTDBTK_DATA_PATH
$ /my/path

download-db.sh
Downloading the GTDB-Tk database to /.../conda_envs/myenv/share/gtdbtk-2.1.0/db/...
```

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by pchaumeil** [comment]
Script has been rewritten
