### ISSUE TITLE
GTDB-Tk v0.1.1 does not generate *.bac120.classification.tsv file 

### ISSUE THREAD

**Issue by ilnamkang** [Ecogenomics/GTDBTk#40]
GTDB-Tk v0.1.1 seems to not generate a main output file (*.bac120.classification.tsv).

I've used GTDB-Tk v0.0.7 for the last several months. The program worked very nicely and I always got output files as explained in the manual.

Recently, I upgraded GTDB-Tk from v0.0.7 to v0.1.1 by "pip install gtdbtk --upgrade", and also updated the reference data from R83 to R86.

After upgrading to v0.1.1, I tried analyzing some of my genomes that had already been analyzed by v0.0.7, just for comparison. But, GTDB-Tk v0.1.1 seems to not generate a main output file (*.bac120.classification.tsv) and also the fastani result file (*.bac120.fastani_results.tsv). The other output files are generated without any problem. 

I attach the log files from v0.0.7 and v0.1.1. There were no errors for both versions.

What can I do to get a main output file from v0.1.1? 

Thanks.

[gtdbtk_v0.0.7.log](https://github.com/Ecogenomics/GTDBTk/files/2377583/gtdbtk_v0.0.7.log)
[gtdbtk_v0.1.1.log](https://github.com/Ecogenomics/GTDBTk/files/2377584/gtdbtk_v0.1.1.log)

**Comment by pchaumeil** [comment]
Hi, 
.bac120.classification.tsv  and .bac120.fastani_results.tsv have been merged to .bac120.summary.tsv .
This new summary files has the following information:

user_genome	
classification	
fastani_reference	
fastani_taxonomy	
fastani_ani	
fastani_af	
closest_placement_reference	
closest_placement_taxonomy	
closest_placement_ani	
closest_placement_af	
classification_method	
note	other_related_references(genome_id,species_name,ANI,AF)

I will update the Manual to reflect the changes between 0.0.7 and 0.1.1.

Cheers,
Pierre

**Comment by ilnamkang** [comment]
Thanks a lot.
