### ISSUE TITLE
Inconsistent pplacer paths in config.py

### ISSUE THREAD

**Issue by ryanmelnyk** [Ecogenomics/GTDBTk#400]
Hello. I'm updating my genome taxonomy pipeline to R207/v2.1.0 and I'm eager to test out the new class/order level splits. However, I receive the following error when pplacer is first launched during GTDBtk classify_wf:
`==> Step 1 of 9: Starting pplacer.Uncaught exception: Sys_error("db/split/class_level/pplacer/db/split/class_level/pplacer/gtdbtk.package.1.refpkg: No such file or directory")`

My GTDBTK data path is simply "db" but it looks like there are two paths prepended. Looking at the `gtdbtk/config/config.py` file this seems to be an inconsistency where `CLASS_LEVEL_PPLACER_REF_PKG` and `CLASS_LEVEL_PPLACER_DIR` are both defined as full paths both containing folder hierarchy prefixes but when launching pplacer in classify.py these paths are joined together.

Seems like line 50 in config.py should look like line 48 and just contain the basename of the ref_pkg.

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [X] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
deployed via AWS Batch

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by pchaumeil** [comment]
Hi, 
Thanks for your feedback, We are working on a patch for version 2.1.0 and this will fix this issue.
In the meantime, you can use the full path to the `db` directory instead of only 'db':
use
`export GTDBTK_DATA_PATH=/full/path/to/db`
instead of 
`export GTDBTK_DATA_PATH=db`
This should fix the issue for now.

**Comment by pchaumeil** [comment]
Fixed in 2.1.1

**Comment by ZarulHanifah** [comment]
Sorry, I am using 2.1.1 but still got this problem. I am using release207. Log file is attached. I installed GTDBtk using conda, did it just today.

Thank you.

[log.log](https://github.com/Ecogenomics/GTDBTk/files/9120131/log.log)

**Comment by ZarulHanifah** [comment]
The important part of the error message was:

```
[2022-07-15 20:21:28] INFO: pplacer version: v1.1.alpha19-0-g807f6f3
==> .==> Step 1 of 9: Starting pplacer.Uncaught exception: Sys_error("/fs03/pg32/zarul/db/GTDBtk_db/release207/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")
Fatal error: exception Sys_error("/fs03/pg32/zarul/db/GTDBtk_db/release207/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")
==> Running pplacer v1.1.alpha19-0-g807f6f3 analysis on /fs03/pg32/zarul/gtdb_workflow/Eanophelis/gtdbtk_out/align/gtdbtk.bac120.user_msa.fasta.gz....Process Process-125:
Traceback (most recent call last):
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 124, in _worker
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: /fs03/pg32/zarul/gtdb_workflow/Eanophelis/gtdbtk_out/classify/intermediate_results/pplacer/pplacer.backbone.bac120.out
                                                                                                                                                      [2022-07-15 20:21:28] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/main.py", line 834, in parse_options
    self.classify(options)
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/main.py", line 458, in classify
    classify.run(genomes=genomes,
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/classify.py", line 396, in run
    high_classify_tree = self.place_genomes(user_msa_file,
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/classify.py", line 261, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/fs02/pg32/Zarul/gtdb_workflow/.snakemake/conda/6d9d175258305f707f9c60e6aa8b5728/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 92, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================
```

And when I was looking at the other log file '/fs03/pg32/zarul/gtdb_workflow/Eanophelis/gtdbtk_out/classify/intermediate_results/pplacer/pplacer.backbone.bac120.out`, it shows this:

```
Running pplacer v1.1.alpha19-0-g807f6f3 analysis on /fs03/pg32/zarul/gtdb_workflow/Eanophelis/gtdbtk_out/align/gtdbtk.bac120.user_msa.fasta.gz...
```

Thank you.

**Comment by Mamingjie543** [comment]
I I have the same issue as ZarulHanifah, is this problem solved now?have the same issue as ZarulHanifah, is this problem solved now?

> Sorry, I am using 2.1.1 but still got this problem. I am using release207. Log file is attached. I installed GTDBtk using conda, did it just today.
> 
> Thank you.
> 
> [log.log](https://github.com/Ecogenomics/GTDBTk/files/9120131/log.log)

**Comment by pchaumeil** [comment]
Hi,
It looks like you are using GTDB-Tk package R207_v1 with GTDB-Tk 2.1.1, That is why the path to gtdbtk_package_backbone.refpkg cannot be found. 
v2.1.0+ is not compatible with GTDB-Tk package [R207_v1](https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_data.tar.gz). It is necessary to upgrade to GTDB-Tk package [R207_v2](https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_v2_data.tar.gz).

Cheers,
Pierre

**Comment by Mamingjie543** [comment]
Hi，
With your help, I solved this problem, you are right, the database I use does not match.
Thank you very much for the help email!&nbsp;


All all all all all the best!!!



Ming-Jie Ma
College of Life Sciences
Beijing Normal University
Beijing 100875
China
Phone: +86-18810186159(direct)
Email: ***@***.***


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ecogenomics/GTDBTk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 上午7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ecogenomics/GTDBTk] Inconsistent pplacer paths in config.py (Issue #400)





 
Hi,
 It looks like you are using GTDB-Tk package R207_v1 with GTDB-Tk 2.1.1, That is why the path to gtdbtk_package_backbone.refpkg cannot be found.
 v2.1.0+ is not compatible with GTDB-Tk package R207_v1. It is necessary to upgrade to GTDB-Tk package R207_v2.
 
Cheers,
 Pierre
