### ISSUE TITLE
A stand-alone "identify" module to use just like FetchMG in motu2?

### ISSUE THREAD

**Issue by jianshu93** [Ecogenomics/GTDBTk#403]
Hello Team,
I found extracting HMMs form proteomes could be very oftenly used in a lot of other applications. Since I/O is the limiting step in this task (loading 120 HMMs), I think the gtdbtk indentify module handles this perfectly after testing but I always need to install gtdbtk and deploy the entire database to make it work (hmm file path variable et.al.). I am wondering whether there could be a stand-alone tool for the public. Hmm file path will be a command line option to allow user specific hmm files.

Thanks,

Jianshu

**Comment by pchaumeil** [comment]
Hi Jianshu,
Thanks for your email,
Unfortunately we currently don't have the bandwith to develop and maintain a separate tool different to GTDB-Tk so an 'identify' stand alone tool wont be implemented.  

Cheers,
Pierre
