### ISSUE TITLE
is Divide and conquer method faster than a big tree?

### ISSUE THREAD

**Issue by jianshu93** [Ecogenomics/GTDBTk#405]
Hello GTBD-tk team,

I am writing to ask wether the new method to reduce memory of phylogenetic replacement will be faster than the original one because this will initiate the pplacer multiple times. Is there a place where I can read about this method.

Thanks,

Jianshu

**Comment by pchaumeil** [comment]
Hi Jianshu,
It really depends on your user genomes and how diverse they are. 

- if your genomes are all in the same class , GTDB-Tk only loads the backbone tree and **one** class-level tree and this is **considerably** than the full-tree approach.

- if your genomes are all across the reference tree  , GTDB-Tk load the backbone tree and **all** class-level trees (6 of them) and this is **slightly** faster than the full-tree approach.

We are preparing a manuscript with the more information about the speed.

Cheers,
Pierre

**Comment by jianshu93** [comment]
Thanks for the response.


Jianshu
