### ISSUE TITLE
pplacer unfamiliar suffix

### ISSUE THREAD

**Issue by Galen-Guo** [Ecogenomics/GTDBTk#406]
I've been having this issue since I upgraded to the 2.1.0 version. 

` Starting pplacer.Uncaught exception: Failure("unfamiliar suffix on /home/galen/gtdbtk_207/align/gtdbtk.ar53.user_msa.fasta.gz")
Fatal error: exception Failure("unfamiliar suffix on /home/galen/gtdbtk_207/align/gtdbtk.ar53.user_msa.fasta.gz")
==> Running pplacer v1.1.alpha13-0-g1ec7786 analysis on /home/galen/gtdbtk_207/align/gtdbtk.ar53.user_msa.fasta.gz....Process Process-173:
Traceback (most recent call last):
  File "/home/galen/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/galen/gtdbtk/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 124, in _worker
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: /home/galen//gtdbtk_207/classify/intermediate_results/pplacer/pplacer.ar53.out
                                                                                                  [2022-06-13 11:44:48] ERROR: Controlled exit resulting from an unrecoverable error or warning.
`

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ #] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: Intel(R) Xeon(R) CPU E7-4850 v4 @ 2.10GHz
128
- RAM: 3170313132
- OS: NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by Galen-Guo** [comment]
just an update. I unzip the `*.fasta.gz ` files in the align and ran `gtdbtk classify` instead and it works. It seems pplacer doesn't recognize the .gz suffix (as state in the error message)

**Comment by pchaumeil** [comment]
Hello, 
I am not able to reproduce this error,
Could you please send me the command line you are running  and the dataset ( as small as possible) you are using to generate this error?

Cheers

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
