### ISSUE TITLE
download-db.sh 404 Not Found https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz

### ISSUE THREAD

**Issue by louellette** [Ecogenomics/GTDBTk#407]
I have installed release 2.1.0 on my linux server from bioconda and the download-db.sh script is pointing to a non-existent file. Did I somehow pick up an old release? I see gtdbtk-1.0.2 in the file names. Thanks in advance for your help! 

conda create -n gtdbtk-2.1.0 -c conda-forge -c bioconda gtdbtk
conda activate gtdbtk-2.1.0
echo $GTDBTK_DATA_PATH
/gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/share/gtdbtk-1.0.2/db/
which gtdbtk
/gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/bin/gtdbtk
download-db.sh
Downloading the GTDB-Tk database to /gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/share/gtdbtk-1.0.2/db/...
--2022-06-17 13:00:03--  https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz
Resolving data.ace.uq.edu.au (data.ace.uq.edu.au)... 130.102.99.4
Connecting to data.ace.uq.edu.au (data.ace.uq.edu.au)|130.102.99.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-17 13:00:05 ERROR 404: Not Found.
which download-db.sh
/gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/bin/download-db.sh

cat /gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/bin/download-db.sh
#!/usr/bin/env bash

echo "Downloading the GTDB-Tk database to ${GTDBTK_DATA_PATH}..."

# GTDBTK_DB_PATH is defined in build.sh, store the db there
wget https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz -P ${GTDBTK_DATA_PATH}
tar xvzf ${GTDBTK_DATA_PATH}/gtdbtk_r89_data.tar.gz -C ${GTDBTK_DATA_PATH} --strip 1
rm ${GTDBTK_DATA_PATH}/gtdbtk_r89_data.tar.gz

echo "GTDB-Tk database has been successfully downloaded."

exit 0

**Comment by louellette** [comment]
I managed to wrangle my way through by
conda create -n gtdbtk-2.1.0 -c conda-forge -c bioconda gtdbtk=2.1.0
download-db.sh then worked but did not update $GTDBTK_DATA_PATH
so then I updated /gusto/dev/software/anaconda3/envs/gtdbtk-2.1.0/etc/conda/activate.d/env_vars.sh to export $GTDBTK_DATA_PATH

**Comment by aaronmussig** [comment]
Correct, you downloaded version 1.0.2. You should fix the specific version when installing e.g. `conda create -n gtdbtk-2.1.0 -c conda-forge -c bioconda gtdbtk==2.1.0`

Without getting into the details too much, the last linux64 conda package was version 1.0.2 whereas subsequent versions are now built as noarch packages ([see here](https://anaconda.org/bioconda/gtdbtk)). I think that conda looks for the "best match" when trying to find what channel to install from, and it may have been that there was no compatible python version on the command line (probably <3.6).
