### ISSUE TITLE
ERROR, skch::validateInputFiles, Could not open >PHP1601 Bacillus velezensis FZB42

### ISSUE THREAD

**Issue by danvir-ramesar** [Ecogenomics/GTDBTk#408]
Greetings,

I hope that you all are well. I am trying to use FastANI to compare a list of a Bacillus genomes (many-to-many for ANI comparisons). The bacillus genomes are in fasta format. I have installed FastANI by cloning the repo and installing it. The problem that i am having is that when i am running FastANI, i get this message:

Kmer size = 16
Fragment length = 3000
Threads = 1
ANI output file = /home/boiinfouser/FastANI/FastANI/ANIOUTPUT/BacillusANIOutput.output
>>>>>>>>>>>>>>>>>>
ERROR, skch::validateInputFiles, Could not open >genome1 Bacillus velezensis FZB42

the ">genome1 Bacillus velezensis FZB42" is the first line of the fasta file for my ref and query list. 

any suggestions on how to resolve this problem? Also, the fragment length is quite short for the genomes in the file. is this another error or a length used for ANI?

Many thanks and kind regards
Danvir

**Comment by pchaumeil** [comment]
Similar to #409
