### ISSUE TITLE
Error: ERROR, skch::validateInputFiles, Could not open >genome1 Bacillus velezensis FZB42

### ISSUE THREAD

**Issue by danvir-ramesar** [Ecogenomics/GTDBTk#409]
Greetings,

I hope that you all are keeping well. 

I have recently installed FastANI by cloning its repo and installing it. I am using it to compare (many-to-many) Bacillus genomes (3.9 - 6 mb each). The genome lists are in fasta (.fasta) format. When i run the fastANI  i get this message:

Kmer size = 16
Fragment length = 3000
Threads = 1
ANI output file = /home/danvir/FastANI/FastANI/ANIOUTPUT/BacillusANIOutput
>>>>>>>>>>>>>>>>>>
ERROR, skch::validateInputFiles, Could not open >genome1 Bacillus velezensis FZB42

The ">genome1 Bacillus velezensis FZB42" is the title of the first genome in both my query and reference lists. I have tried changing the file format to a .txt file and i get the same message.No output nor log file was also made.

The fragment size on the error message is 3000, is that suppposed to be the genome size (which would be at least 1000x too small) or another parameter for FastANI?

Any assistance would be appreciated

Keep well and kind regards
Danvir

**Comment by pchaumeil** [comment]
Hello, 
What command line are you using? What is the name of the file with "`>genome1 Bacillus velezensis FZB42`" as a first line?

**Comment by danvir-ramesar** [comment]
Greetings and thank you for getting in touch with me.

I used the following command:

./fastANI --ql /home/danvir/FastANI/FastANI/QUERY/BacillusSeqForAniQUERY.fasta --rl /home/danvir/FastANI/FastANI/REFERENCE/BacillusSeqForAniREF.fasta -o /home/danvir/FastANI/FastANI/ANIOUTPUT/BacillusANIOutput

I made a folder called QUERY and a folder called REFERENCE in the same folder i installed FastANI for ease of use.
I am using the bash shell on the latest version of ubuntu.

**Comment by pchaumeil** [comment]
_From memory, the --rl argument takes a *list of files*, not the actual file._

That is correct , --ql and  --rl expect files containing paths to genomes, one per line.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
