### ISSUE TITLE
ERROR: Controlled exit resulting from interrupt signal.

### ISSUE THREAD

**Issue by MonaLiu421** [Ecogenomics/GTDBTk#413]
Hello, I got this error when I ran the software for 50,001 MAG taxonomy assignments. This makes me a little confused.
the gtdbtk.log as follows:
[2022-07-04 08:43:42] INFO: GTDB-Tk v2.1.0
[2022-07-04 08:43:42] INFO: gtdbtk classify_wf --genome_dir /genomes --out_dir /data/output/test-5w/classify_wf --prefix AllMags --cpus 80 --extension fa
[2022-07-04 08:43:42] INFO: Using GTDB-Tk reference data version r207: /refdata/
[2022-07-04 08:43:49] INFO: Identifying markers in 50,001 genomes with 80 threads.
[2022-07-04 08:43:49] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-07-04 08:52:44] ERROR: Controlled exit resulting from interrupt signal.

My command is gtdbtk classify_wf --genome_dir /genomes --out_dir /data/output/classify_wf  --prefix $sample --cpus 80 --extension fa
Looking forward to your reply！

**Comment by aaronmussig** [comment]
Hello,

Based on your output it appears that you're running this from within a Docker container(?).

The only way GTDB-Tk will exit with the `Controlled exit resulting from interrupt signal` error code is if a SIGINT is received (or keyboard interrupt, CTRL+C). I suspect that GTDB-Tk has exceeded the resource allocation within the Docker environment.

Are you able to check what resources Docker has been allocated, and monitor the GTDB-Tk execution to see if it's exceeding it? i.e CPU / Memory / Disk.

Cheers

**Comment by MonaLiu421** [comment]
Thanks for your reply, i get it! It's actually running within a Docker container.
I still have a question, 50,000 genomes require a lot of memory, if I run it in batches, such as running 10,000 at a time, 5 times, is it feasible and will it affect my results?

**Comment by pchaumeil** [comment]
Hi,
Running the 50K genomes or 5 x 10K in batches will give the same results (although we have seen cases where RED values slightly change with thousands of genomes on the same reference branch).
Even if this is a bit slower, I would recommend running 10K genomes at a time.

**Comment by BigtigerLi** [comment]
> Thanks for your reply, i get it! It's actually running within a Docker container. I still have a question, 50,000 genomes require a lot of memory, if I run it in batches, such as running 10,000 at a time, 5 times, is it feasible and will it affect my results?

Hi, I'd like to ask how you solved this problem, I'm experiencing the same error
