### ISSUE TITLE
GTDBTK_DATA_PATH

### ISSUE THREAD

**Issue by ZengJiaxiong** [Ecogenomics/GTDBTk#418]
Hi,

In GTDBTK1.7, I used to set the GTDBTK_DATA_PATH by modifying the ~/miniconda3/envs/gtdbtk-1.7/etc/conda/activate.d/gtdbtk.sh, but I cannot find this file in gtdbtk 2.1.0.
How can I set the right path for gtdbtk 2.1.0?

Thanks,

Jiaxiong

**Comment by aaronmussig** [comment]
Hello,

We have updated the Bioconda package to use the [conda env config vars](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables) command for ease of use.

You can now set the environment path by running:

`conda env config vars set TARGET_DIR=/path/to/package`

**Comment by ZengJiaxiong** [comment]
Thank you very much! Now it worked.
