### ISSUE TITLE
GTDB-TK 16S amplicon sequence

### ISSUE THREAD

**Issue by lhy27** [Ecogenomics/GTDBTk#419]
Hi，
I would like to ask if I can use the classify_wf command of GTDB-TK for taxonomic classifications of Zotus sequenced by 16S amplicon, when I run "gtdbtk classify_wf" it always tells me "genomes with no bacterial or archaeal marker" and "Identified 0 single copy bacterial hits"？
Looking forward to your reply！
Thanks.

**Comment by dparks1134** [comment]
GTDB-Tk provides taxonomic classifications for genome assemblies (isolates, MAGs, or SAGs) and not individual genes like the 16S rRNA.
