### ISSUE TITLE
Hanging on classify_wf and TIGRFam

### ISSUE THREAD

**Issue by cjfields** [Ecogenomics/GTDBTk#420]
## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [X] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`

72:
```
model name	: Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz
72
```

- RAM: `grep "^MemTotal" /proc/meminfo`

~2TB:
```
$ grep "^MemTotal" /proc/meminfo
MemTotal:       2113424232 kB
```

- OS: `cat /etc/os-release`

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

## Debugging information
- [x] `gtdbtk.log` has been included (drag and drop the file to upload).

```
[2022-07-27 00:11:37] INFO: GTDB-Tk v2.1.1
[2022-07-27 00:11:37] INFO: gtdbtk classify_wf --genome_dir ./test-bins --out_dir MDG179-test -x fa --prefix MDG179 --cpus 24 --tmpdir /scratch
[2022-07-27 00:11:37] INFO: Using GTDB-Tk reference data version r207: /home/groups/hpcbio/data/GTDB/R207_v2/release207_v2
[2022-07-27 00:11:37] INFO: Identifying markers in 339 genomes with 24 threads.
[2022-07-27 00:11:37] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-07-27 00:44:25] INFO: Completed 339 genomes in 32.80 minutes (10.33 genomes/minute).
[2022-07-27 00:44:26] TASK: Identifying TIGRFAM protein families.
```
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

The main issue is that the `gtdbtk` processes seem to be in a waiting mode; maybe the tool (hmmer?) using tigrpfam isn't working properly?  

The database is on a shared file system on a cluster, `release207_v2` (latest).  

Adding in `ps` info:

```
$ ps aux | grep cjfields
cjfields 4056529  0.0  0.0 689132  4036 ?        Sl   00:11   0:12 /home/apps/software/GTDBTk/2.1.1/bin/python3.8 /home/apps/software/GTDBTk/2.1.1/bin/gtdbtk classify_wf --genome_dir ./test-bins --out_dir MDG179-test -x fa --prefix MDG179 --cpus 24 --tmpdir /scratch
cjfields 4063882  0.0  0.0 689164   544 ?        S    00:44   0:00 /home/apps/software/GTDBTk/2.1.1/bin/python3.8 /home/apps/software/GTDBTk/2.1.1/bin/gtdbtk classify_wf --genome_dir ./test-bins --out_dir MDG179-test -x fa --prefix MDG179 --cpus 24 --tmpdir /scratch
```

**Comment by cjfields** [comment]
I should add, the log file is very small (as you can see above).  I may test copying the database to local disk on the worker node and running it from there in case it's a network file system issue, but it's definitely odd that it's not working...

**Comment by pchaumeil** [comment]
Hello,
I am not sure what is happening here....
Does `gtdbtk check_install` return an error?

Thanks,
Pierre

**Comment by sjaenick** [comment]
https://github.com/Ecogenomics/GTDBTk/blob/master/gtdbtk/external/tigrfam_search.py#L141

Default pipe buffer size is 64k on Linux; if `hmmsearch` produces more than 64k of output, the pipe will block,
thus causing the hang. Since stdout/stderr isn't used anyway, using `stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL` should fix this.

**Comment by aaronmussig** [comment]
Thanks for this! We will include this in the next version of GTDB-Tk.

**Comment by cjfields** [comment]
Hi @aaronmussig we were able to work around this by being very selective with the bins we used. I suspect the issue is as @pchaumeil outlined.
