### ISSUE TITLE
de_novo_wf with gtdb refs fails to parse classify output 

### ISSUE THREAD

**Issue by adityabandla** [Ecogenomics/GTDBTk#427]
Hello,

I am trying to build a tree integrating my genomes with the GTDB refs. After the tree is built, the workflow fails with the error 
`ERROR: Failed to parse taxonomy file on line 1
ERROR: Not a tab-separated line: user_genome	classification	fastani_reference	fastani_reference_radius	fastani_taxonomy	fastani_ani	fastani_af	closest_placement_reference	closest_placement_radius	closest_placement_taxonomy	closest_placement_ani	closest_placement_af	pplacer_taxonomy	classification_method	note	other_related_references(genome_id,species_name,radius,ANI,AF)	msa_percent	translation_table	red_value	warnings
`

I had provided the file produced by gtdb classify to the flag --gtdbtk_classification_file

**Comment by palomo11** [comment]
Hi, I am having the same error. How did you solve it?
