### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by valentinslepukhin** [Ecogenomics/GTDBTk#429]
Hello, 
When I am trying to install GTDB-tk on MacOS using Bioconda I am getting the following error message

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                        

UnsatisfiableError: 

What should I do with it?

Thank you!

**Comment by aaronmussig** [comment]
Hello, this is because Pplacer is not supported on OSX. If you wish to run GTDB-Tk on OSX, then you will need to run it using Docker: https://ecogenomics.github.io/GTDBTk/installing/docker.html
