### ISSUE TITLE
Understanding alphabetical suffixes in classification

### ISSUE THREAD

**Issue by higaredavm** [Ecogenomics/GTDBTk#430]
I am trying to understand the alphabetical suffixes in classification specially when there are double alphabetical suffixes.
Some classification results of our analysis are:

1) Cupriavidus oxalaticus_A
I understand that Cupriavidus oxalaticus_A is a different species that Cupriavidus oxalaticus according to GTDB.  Could be this result taken as a preliminary  to go deeper and try to asses if Cupriavidus oxalaticus_A is a new species?

2) Pseudomonas_E inefficax, Pseudomonas_F furukawaii, Pseudomonas_E palleroniana, Bacillus_A albus, Bacillus_A toyonensis 

Is the suffix after genus an indicator that Bacillus is polyphyletic ?. There are other Bacillus species that doesn't not have a suffix such as Bacillus paralicheniformis, Bacillus spizizenii, Bacillus velezensis .

Thanks
Victor Higareda

GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum:

GTDB forum:
https://forum.gtdb.ecogenomic.org/

**Comment by dparks1134** [comment]
Hi Victor,

You can find details on the alphabetical suffixing of species and genus names in this GTDB FAQ:
https://gtdb.ecogenomic.org/faq#why-do-some-genus-and-species-names-end-with-an-alphabetic-suffix

Cheers,
Donovan
