### ISSUE TITLE
Bioconda GTDB-Tk reference data install issue

### ISSUE THREAD

**Issue by kalen-rasmussen** [Ecogenomics/GTDBTk#435]
I recently installed GTDB-Tk through bioconda, but ran into an issue when trying to download and set up the reference data. It appears that the url in the script to set it up `download-db.sh` is no longer the current location of the data since I received a 404 file not found error when executing the script. One can fix this by opening `download-db.sh` and changing the url. 
Change
`wget https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/gtdbtk_r89_data.tar.gz -P ${GTDBTK_DATA_PATH}`
to 
`wget https://data.gtdb.ecogenomic.org/releases/release89/89.0/gtdbtk_r89_data.tar.gz  -P ${GTDBTK_DATA_PATH}`

Hope this is helpful for others running into this issue.

Kalen

**Comment by aaronmussig** [comment]
Hi, if the reference data is R89 then I imagine this is quite an old version of GTDB-Tk. The newer Bioconda recipes don't have this issue. Try specify the verison of GTDB-Tk when installing to ensure that you're getting the most up-to-date version, e.g.

```
conda install -c bioconda gtdbtk==2.1.1
```

**Comment by aaronmussig** [comment]
I'll close this as it's not a present issue, but it will still be searchable for anyone who is looking to install the specific bioconda version.
