### ISSUE TITLE
Invalid genome ID: binny_XXXX_CXX_PXX_Actinobacteria[class]

### ISSUE THREAD

**Issue by B-1991-ing** [Ecogenomics/GTDBTk#440]
Dear GTDB-Tk support team,

I got the error - "**ERROR: The following characters are invalid:   [ ) = ] ( ; ,**", due to my MAG name "binny_I01R01.000347_C91_P96_Actinobacteria[class].fasta" includes square brackets "[]". Could you give some suggestion to solve it? 

**Log file**
[classify_wf_species_omstrup_sillebotten_sediment_norefinem.log](https://github.com/Ecogenomics/GTDBTk/files/9713876/classify_wf_species_omstrup_sillebotten_sediment_norefinem.log)

Thank you very much.

Best,

Bing

**Comment by aaronmussig** [comment]
Hello, if you rename the MAG to not include any of those characters then it will work, e.g. 

`mv binny_I01R01.000347_C91_P96_Actinobacteria[class].fasta binny_I01R01.000347_C91_P96_Actinobacteria__class__.fasta`

**Comment by B-1991-ing** [comment]
Thank you for the suggestion, I will rename the MAGs.
