### ISSUE TITLE
Certificate expiry for gtdb website

### ISSUE THREAD

**Issue by Somebodyatthdoor** [Ecogenomics/GTDBTk#441]
Hi,

I 'm currently trying to download the newest version of the database from https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz onto my local cluster. However, the download failed due to the website certificate having expired. The folks in charge of my cluster don't tend to be happy with people using the "--no-check-certificate" option to ignore certificates. Do you know if the website certificate will be renewed soon? 

Cheers,
Laura

**Comment by aaronmussig** [comment]
Hi Laura,

When you tried the request the certificate was valid until the [end of the month](https://www.whynopadlock.com/results/f19b7142-9b4d-4708-83f0-2609d09e9fa8). In-case there was something up with it being too close to the expiry date I've renewed the certificate if you want to try again.

Cheers,
Aaron

**Comment by Somebodyatthdoor** [comment]
Hi Aaron,

Thanks. Not sure why but I'm still getting an error when trying to run dowload-db.sh:

Resolving data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)... 203.101.230.53
Connecting to data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)|203.101.230.53|:443... connected.
ERROR: cannot verify data.gtdb.ecogenomic.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.

Cheers,
Laura

**Comment by aaronmussig** [comment]
I think that this might be something to do with the configuration of the server you're running it on. It might be best to put this question to the system administrator.

My best guess is trying to troubleshoot one of these (maybe) related issues:
https://stackoverflow.com/questions/62107565/wget-and-curl-stopped-working-with-https-wrongly-complain-about-an-expired-cert 
https://stackoverflow.com/questions/62107431/curl-error-60-ssl-certificate-problem-certificate-has-expired/62108103#62108103

**Comment by Somebodyatthdoor** [comment]
Hi,

Thanks for your help Aaron. It did seem to be an issue with the cluster I was using. The admin's have made some adjustments and everything seems to be working fine now. 

Cheers,
Laura
