### ISSUE TITLE
error when working with GTDB conda 

### ISSUE THREAD

**Issue by reaset41** [Ecogenomics/GTDBTk#442]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.14.6=0
  - feature:|@/osx-64::__osx==10.14.6=0
  - gtdbtk -> matplotlib-base -> __osx[version='>=10.12']

Your installed version is: 10.14.6

**Comment by aaronmussig** [comment]
Hi, is this on OSX? GTDB-Tk won't run on a Mac as pplacer causes a dependency issue. A workaround is to use Docker.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
