### ISSUE TITLE
No such file or directory: 'minoconda3/envs/gtdbtk-1.3.0/share/gtdbtk-1.3.0/db/markers/pfam/individual_hmms/PF00380.14.hmm'

### ISSUE THREAD

**Issue by litianhui333** [Ecogenomics/GTDBTk#445]
Dear GTDB support team:

I got an error :FileNotFoundError: [Errno 2] No such file or directory: 'minoconda3/envs/gtdbtk-1.3.0/share/gtdbtk-1.3.0/db/markers/pfam/individual_hmms/PF00380.14.hmm'. Could you give some suggestion to solve it?

I used this code to install GTDB:
conda create -n gtdbtk-1.3.0 -c conda-forge -c bioconda gtdbtk=1.3.0
conda activate gtdbtk-1.3.0
download-db.sh

Best wishes,
Tian

**Comment by novitch** [comment]
Hello, 
Got the same error today, 
I downloaded myself the db :
```
wget https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_v2_data.tar.gz
```
then created the conda env 
```
conda create -n gtdbtk-1.3.0 -c conda-forge -c bioconda gtdbtk=1.3.0
conda activate gtdbtk-1.3.0
echo "export GTDBTK_DATA_PATH=/mnt/software/dataset/db/gtdbtk/release207_v2/" >/home/matalb01/miniconda3/envs/gtdbtk/etc/conda/activate.d/gtdbtk.sh
```

All th process was ok until 
```
==> Finished processing 83 of 83 (100.0%) genomes.
[2022-10-20 10:11:48] INFO: Annotations done using HMMER 3.3.2 (Nov 2020)
[2022-10-20 10:11:50] INFO: Done.
[2022-10-20 10:11:50] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: '/mnt/software/dataset/db/gtdbtk/release207_v2/markers/pfam/individual_hmms/PF00380.14.hmm'
________________________________________________________________________________
````

**Comment by pchaumeil** [comment]
Hello,

GTDB-Tk v1.3.0 is not compatible with the latest data package (R207_v2). You will need to install GTDB-Tk v2.1.0+ for this version of the data.
