### ISSUE TITLE
How to get RED values

### ISSUE THREAD

**Issue by BT287** [Ecogenomics/GTDBTk#446]
Hi, 
I'm trying to get RED values from Streptomyces genome to cluster them based on the values.
I implemented gtdb-tk with this command: `gtdbtk classify_wf --genome_dir fna_sample/ --out_dir gtdbtk_sample/ --cpus 4 --debug` but I did not get the RED values from the result, even though RED calculation was done according to the log file.

Please check the attached file, which is the result of the implementation.
Did I miss something?

[gtdbtk.bac120.summary_streptomyces.csv](https://github.com/Ecogenomics/GTDBTk/files/9801989/gtdbtk.bac120.summary_streptomyces.csv)

[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/9801990/gtdbtk.log)

**Comment by dparks1134** [comment]
Hi. Currently we do not report RED values if a genome was classified based on its ANI value to a representative genome. We have flagged this as a potential enhancement for the next GTDB-Tk release.

**Comment by BT287** [comment]
I see,
I hope a future version will provide RED values as additional information.

Thank you for the answer!
