### ISSUE TITLE
ANI results with type strains of species

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/GTDBTk#45]
This will be relevant once the GTDB reference tree is composed entirely of type strains of species and nominated GTDB type genomes for species without type material. At this point in time we should ensure that a genome is only assigned to a species if: i) the type genome of the species has the highest ANI, ii) the ANI >= 95%, and importantly, iii) the ANI is larger than the ANI from the selected type genome to any other type genome. Point iii is critical to ensure assignments aren't made that are likely to result in polyphyly in a phylogenetic tree.

**Comment by pchaumeil** [comment]
@dparks1134 , Can we close this one?

**Comment by dparks1134** [comment]
Done and dusted.
