### ISSUE TITLE
Change database PATH

### ISSUE THREAD

**Issue by PatoUru** [Ecogenomics/GTDBTk#460]
Hi all!
I would like to know the location of the file in order to change the path of the database :)

In te previous GTDBtk version the file was /anaconda3/envs/gtdbtk/etc/conda/activate.d/**gtdbtk.sh**

But i didnt find this file in GTDBtk v2

Thank you very much in advance!

Pat

**Comment by zwets** [comment]
Hi @PatoUru, this is documented [in the installation instructions](https://ecogenomics.github.io/GTDBTk/installing/bioconda.html#step-3-download-and-alias-the-gtdb-tk-reference-data):

    conda env config vars set GTDBTK_DATA_PATH="/path/to/unarchived/gtdbtk/data";

**Comment by pchaumeil** [comment]
Thanks for answering this ticket, I will close it now
