### ISSUE TITLE
help for GTDBTk classification

### ISSUE THREAD

**Issue by JiaZhong28** [Ecogenomics/GTDBTk#463]
when I use assembled bins for genome annotation, I got several classification results like g__Prevotellamassilia;s__Prevotellamassilia sp004558535, I wonder what the number for? Or it that means that this bin has no annotation for species level.  It is odd to find that most of such annotation result ends with 5 rather than any other number.

**Comment by donovan-h-parks** [comment]
Hi. GTDB-Tk uses the GTDB taxonomic framework for  classification. The species `s__Prevotellamassilia sp004558535` was a species cluster in GTDB R202. GTDB is now at R207. It appears you are using an older version of GTDB-Tk. It is highly recommended that you update to the latest version of the software and reference data.

https://gtdb.ecogenomic.org/taxon-history?from=R80&to=R207&query=s__Prevotellamassilia%20sp004558535

**Comment by JiaZhong28** [comment]
> Hi. GTDB-Tk uses the GTDB taxonomic framework for classification. The species `s__Prevotellamassilia sp004558535` was a species cluster in GTDB R202. GTDB is now at R207. It appears you are using an older version of GTDB-Tk. It is highly recommended that you update to the latest version of the software and reference data.
> 
> https://gtdb.ecogenomic.org/taxon-history?from=R80&to=R207&query=s__Prevotellamassilia%20sp004558535

thanks a lot, I noticed that the web you sent me can transform tax annotation from old to new release, I wonder if it is feasible to transform all annotated tax without rerun again under update software?  In other words, I woder what the changes between old and new version of reference data, its only the update of tax classification or the  entire markers genes, in which case re-run the programe has to be done.

**Comment by donovan-h-parks** [comment]
Hi. There is no formal way to update taxonomic classifications between GTDB releases. New GTDB releases contain additional species clusters and existing taxa may be merged or split. Unfortunately, this means there is no simply 1:1 mapping that can be performed.
