### ISSUE TITLE
Any script/method to obtain the closest relative on phylogenetic tree?

### ISSUE THREAD

**Issue by mars188** [Ecogenomics/GTDBTk#468]
Dear developers, 

I have generated a tree with GTDB-tk using my 40 genomes. The GTDB-tk output a big tree with thousands of genomes. I want to find the closest relatives of all my 40 genomes. The output file "gtdbtk.bac120.summary" files contains closest relatives of some of my genomes but not for all. I understand that pplacer may be placed the genome 'high' enough in the tree therefore did not report closest relatives of these genomes, however, I still want to get whatever the closest genome may be. 

It is very difficult to manually look and search for the tree closely placed to the candidate genome. Is there a script or command available for this purpose? 

I would really appreciate your help. 

Many thanks in advance!

**Comment by pchaumeil** [comment]
Hello,

We do not have a script to return the closest representative genome when the user genome is place close to the root in the reference tree. 
However , @aaronmussig has developed a tool to convert a phylogenetic tree into a pairwise distance matrix called [PhyloDM](https://github.com/aaronmussig/PhyloDM), this can be of interest to detect the closest representive based on patristic distance for each of the user genomes.
