### ISSUE TITLE
Combine the bacteria and Archaea tree in the GTDB-Tk

### ISSUE THREAD

**Issue by pengshuoyang** [Ecogenomics/GTDBTk#473]
When I combine the MAG identified as Bacteria and Archaea to run the GTDB-Tk,  an error was returned. Now I know it is caused by the different sets of marker genes. Now I am wondering if there is a way to combine two tree files (bacteria and archaea) obtained from the GTDB-Tk. After I checked the manual of GTDB-Tk, there is no answer for my question.

Thanks

**Comment by pchaumeil** [comment]
Hello, 
As you mentioned, The bacterial and archaeal trees are inferred from different marker genes. We consider the trees to be unrooted as the correct rootings of these trees remains an open area of research. You can artificially combine them by manipulating the Newick files.
Currently, we do not provide a tool to combine these trees. We use DendroPy in GTDB-Tk which is a nice Python package for working with trees ( rooting trees,trimming trees...). This package can used to combine trees.
