### ISSUE TITLE
Bacterial genus for an Archaea ASV

### ISSUE THREAD

**Issue by alegarritano** [Ecogenomics/GTDBTk#477]
Hi guys,

Initially, I'd like to thank you for the hard-work on keeping the database and the GTDK-Tk always updated. I've met Pierre at ISME last year and it was great to have a chat about the software and all the work that is being put into it. 

I am writing to you regarding a persistent error in one of my analysis. I initially ran a set of ASV sequences through GTDK-Tk in 2020 (taxonomy database release 95, if I'm not mistaken). I didn't get any weird results by then.

After completing the study that used GTDB's result as it's basis, I reran the dataset using the taxonomy database release 207.

When I do so, one of my ASVs that was previously being classified as 

Archaea | Thermoproteota | Nitrososphaeria | Nitrososphaerales | Nitrosopumilaceae | PXYB01 | PXYB01 sp003352285

Now is being classified as 

Archaea | Thermoproteota | Nitrososphaeria | Nitrososphaerales | Nitrosopumilaceae | Helicobacter | Helicobacter pylori_CJ

I understand that taxonomies change over time, and this was the primarily reason for me to rerun the ASVs using the most recent taxonomy database, but Helocobacter, as the name suggests, is a Bacteria (d__Bacteria; p__Campylobacterota; c__Campylobacteria; o__Campylobacterales; f__Helicobacteraceae; g__Helicobacter; s__Helicobacter pylori). It should not come up as an archaeal genus. 

In case this is something you can look into, this is the ASV sequence that is resulting in the error:

>Zotu1
CCGCGGTAAAACCAGCACCTCAAGTGGTCAGGAGGATTATTGGGCCTAAAGCATCCGTAGCTTGGTCTATAAGTTTTCGG
TTAAATCCATACGCTCAACGTATGGGCTGCCGGAAATACTGTAGACCTAGGGAGTGGGAGAGGTAGACGGTACTCGATAG
GAAGGGGTAAAATCCTTTGATCTATTGATGACCACCTGTGGCGAAGGCGGTCTACCAGAACACGTCCGACAGTGAGGGAT
GAAAGCTGGGGGAGCAAACCGGATTAGAAACC

Best regards,
Alessandro

**Comment by donovan-h-parks** [comment]
Hi Alessandro,

Thanks for the kind words. 

I assume you are classifying 16S sequences. How are you doing this classification? In particular, where does the taxonomy string indicating Helicobacter is an Archaea come from?

Cheers,
Donovan

**Comment by alegarritano** [comment]
Hi Donovan,

It ended up being an error on my side. This is all good. Thanks for the prompt reply though

**Comment by pchaumeil** [comment]
Solved
