### ISSUE TITLE
Contradictory results using classify_wf and de_novo_wf

### ISSUE THREAD

**Issue by jehaab** [Ecogenomics/GTDBTk#478]
Hello,

I have reconstructed MAGs from stool samples (completeness estimate >50%, contamination estimate <10%).
I used GTDB.tk to classify the recovered genomes. 5 could only be assigned to the family level using classify_wf.

I also used de_novo_wf to build a tree (as recommended by the documentation, classify_wf should not be used for publication purposes). 
3 of the 5 MAGs assigned to the family level are indeed placed within the family assigned by the classify_wf.
However, 2  MAGs are placed within a genus of the family assigned by the classify_wf.

I don't understand how this is possible since I have used the release 207 database for all of my work.
I would appreciate your help in understanding these discrepancies.

Thank you in advance.

**Comment by donovan-h-parks** [comment]
Hi. The `classify_wf` and `de_novo_wf` are independent so will not always agree. The `classify_wf` places your genomes into the fixed GTDB reference tree using the ML placement tool `pplacer`. In contrast, the `de_novo_wf` infers a new tree using `FastTree`. While these results will typically be similar, they will often not be 100% identical. If you inspect the de novo tree, you will also see that not all GTDB taxa remain monophyletic. This is a consequence of tree inference being an estimate of the relationship between extent taxa and this "best guess" will differ each time tree inference is performed, and certain differ once the set of input genomes changes. In general, a de novo tree should be preferred. Depending on your set of MAGs and the assertions you are aiming to make about them, it may be appropriate to infer a more rigorous de novo tree using only a small subset of genomes (e.g. using IQ-Tree with more sophisticated evolutionary models and only the genomes relevant to your MAGs).

**Comment by jehaab** [comment]
Thank you for your answer and suggestions.

Jehane

**Comment by jehaab** [comment]
Hi,

I have another question as I am still working on accurately placing my MAG in a tree.

What does this note mean in GTDB.tk output ? 
"Genome has conflicting families between trees, reverse to backbone tree classification."

Again thank you for your help.

Jehane

**Comment by donovan-h-parks** [comment]
Hi. GTDB-Tk v2 uses a backbone tree and family specific trees in order to establish taxonomic assignments. In rare cases, the classification suggested by a genomes placement in the backbone tree might conflict with the classification indicated in a family level tree. In such cases, we take the conservative classification indicated in the backbone tree.

Details of this can be found in the GTDB-Tk v2 manuscript:
https://academic.oup.com/bioinformatics/article/38/23/5315/6758240
