### ISSUE TITLE
Accuracy of large phylogenetic tree generated by using denovo_wf

### ISSUE THREAD

**Issue by hites77** [Ecogenomics/GTDBTk#483]
I want to know how much accurate are the phylogenetic tree generated by GTDB-Tk, because a single tree is generated and there are no bootstrap values or bipartition support ?

**Comment by donovan-h-parks** [comment]
The de novo workflow in GTDB-Tk uses FastTree. Support values are not calculated as these are computationally expensive. Depending on your needs, you may need to calculate these or use a more rigorous tree inference method and/or evolutionary models.

**Comment by hites77** [comment]
Thanks for the clarification. So I can use the msa file generated during denovo run to construct tree by another program ?

**Comment by donovan-h-parks** [comment]
You certainly can. Best practice will always depend on your data and questions. For example, the marker sets used by GTDB-Tk were selected as they are largely present and single copy across all bacteria or archaea. This is a more limited set of markers than could be used in a more focused study, say, just the Cyanobacteria.

**Comment by hites77** [comment]
I am considering a large dataset with bacteria from diverse phyla. So I thought that GTDB-Tk marker sets and their MSA will be good or do you suggest generating MSA by different methods? The aim is to study evolutionary trends in some gene distribution across the member; the reviewer questions the tree accuracy using FastTree for this purpose.

**Comment by donovan-h-parks** [comment]
Tree inference is generally a trade-off between computing requirements and model sophistication. If your dataset is similar in size to the GTDB, than the GTDB MSA and FastTree is a pragmatic choice. If you can reduce the number of genomes being considered, a longer MSA (we subsample the bac120 MSA to 5,000 columns) or more sophisticated set of evolutionary models (e.g. as provided in IQTree) may be more appropriate.

**Comment by hites77** [comment]
Thanks for the in-depth explanation.
