### ISSUE TITLE
Error in rule GTDBTkAnalysis：PplacerException

### ISSUE THREAD

**Issue by YenlingPeng** [Ecogenomics/GTDBTk#485]
Dear pb-GTDB-Tk support team,

I was running HiFi MAG pipeline and there was an error in rule "GTDBTkAnalysis.
I checked on [2023-03-09T142429.413389.snakemake.log](https://github.com/Ecogenomics/GTDBTk/files/10955502/2023-03-09T142429.413389.snakemake.log)

The error message is as follows:
`Error in rule GTDBTkAnalysis:
jobid: 21
output: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/align, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/classify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/identify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/atcc-msa-1003.Complete.txt
log: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.GTDBTkAnalysis.log (check log file(s) for error message)
conda-env: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/conda/bb4264a0bcbf30c90d0a5e5f8b6acc98
shell:
GTDBTK_DATA_PATH=/data2/PB/Metagenomics/GTDB-Tk/release207_v2 gtdbtk classify_wf --batchfile /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/6-checkm2/atcc-msa-1003/atcc-msa-1003.GTDBTk_batch_file.txt --out_dir /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/ -x fa --prefix atcc-msa-1003 --cpus 3 --pplacer_cpus 3 &> /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/logs/atcc-msa-1003.GTDBTkAnalysis.log && touch /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/atcc-msa-1003.Complete.txt
(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job GTDBTkAnalysis since they might be corrupted:
/data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/align, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/classify, /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/7-gtdbtk/atcc-msa-1003/identify
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data2/PB/Metagenomics/pb-metagenomics-tools-2.0.0/HiFi-MAG-Pipeline/.snakemake/log/2023-03-09T142429.413389.snakemake.log`

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo
model name : Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
128

- RAM: grep "^MemTotal" /proc/meminfo
MemTotal: 527592328 kB

- OS: cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

## Debugging information
- [x] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

At the same time, I also checked the [atcc-msa-1003.GTDBTkAnalysis.log](https://github.com/Ecogenomics/GTDBTk/files/10955510/atcc-msa-1003.GTDBTkAnalysis.log)

`ERROR: Controlled exit resulting from an unrecoverable error or warning. EXCEPTION: PplacerException MESSAGE: An error was encountered while running pplacer.`

In addition, I can't check the log file of pplacer, like `pplacer.backbone.bac120.out` mentioned in atcc-msa-1003.GTDBTkAnalysis.log, because the relay folder under the 7-gtdbtk/atcc-msa-1003/ directory will be deleted automatically.

I have tried using --scratch_dir and --pplacer_cpus 1 parameters in Snakefile-hifimags.smk, but it doesn't work.

Thank you in advance for your time and assistance.

**Comment by pchaumeil** [comment]
Hi ,
I am not sure what is happening here,  Can you run `gtdbtk test` in your environment to make sure its running without issue?

**Comment by pchaumeil** [comment]
Hi , 
What does the `/tmp/gtdbtk_tmp_mh0qns8k/test_execution.log` say?

**Comment by YenlingPeng** [comment]
We encountered an error while running the gtdbtk test, and we are uncertain of the cause. After running the command, we received the following error message:

[2023-03-31 10:43:27] INFO: GTDB-Tk v2.1.1
[2023-03-31 10:43:27] INFO: gtdbtk test
[2023-03-31 10:43:27] INFO: Using GTDB-Tk reference data version r207: /data2/PB/Metagenomics/GTDB-Tk/release207_v2/
[2023-03-31 10:43:27] INFO: Using a temporary directory as out_dir was not specified.
[2023-03-31 10:43:27] INFO: Command: gtdbtk classify_wf --genome_dir /tmp/gtdbtk_tmp_56ocbba7/genomes --out_dir /tmp/gtdbtk_tmp_56ocbba7/output --cpus 1 -f
[2023-03-31 10:44:14] ERROR: The test returned a non-zero exit code.
[2023-03-31 10:44:14] ERROR: A detailed summary of the execution log can be found here: /tmp/gtdbtk_tmp_56ocbba7/test_execution.log
[2023-03-31 10:44:14] ERROR: The test has failed.
[2023-03-31 10:44:14] ERROR: Controlled exit resulting from early termination.

However, upon checking the specified log file path, /tmp/gtdbtk_tmp_flqnsxz5/test_execution.log, we found that the file does not exist.

Could you please provide us with more information on what could have caused this error and how we can resolve it? 

Thank you for your assistance.

**Comment by pchaumeil** [comment]
Can you please rerun the test and provide and output directory so all output files wont be deleted

`gtdbtk test --out_dir /your/output/path`

**Comment by YenlingPeng** [comment]
Thank you for suggesting the new command. I have rerun the test using the command "gtdbtk test --out_dir /your/output/path" and it was successful. I was able to generate the [test_execution.log](https://github.com/Ecogenomics/GTDBTk/files/11165820/test_execution.log) file. 

It seems that the issue earlier was related to permissions.
