### ISSUE TITLE
Expand environmental variables in GTDBTK_DATA_PATH

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBTk#486]
It appears GTDB-Tk currently treats the GTDBTK_DATA_PATH environmental variable as a string literal. This can be challenging in certain environments where the path to the GTDB-Tk reference database is best accessed via an environmental variable, e.g.:

GTDBTK_DATA_PATH =$ROOT_DB_PATH/gtdbtk/release207_v2

Can GTDB-Tk be modified so the $ROOT_DB_PATH environmental variable is expanded out. I believe this can be done with:
```
os.path.expandvars('$ROOT_DB_PATH/gtdbtk/release207_v2')
```

**Comment by pchaumeil** [comment]
available in https://github.com/Ecogenomics/GTDBTk/releases/tag/2.2.5
