### ISSUE TITLE
GTDBtk input file error

### ISSUE THREAD

**Issue by HK0911** [Ecogenomics/GTDBTk#490]
ERROR: Input directory does not exist: /data1/GID8tk-database/contigs.fasta [2023-03-15 11:11:17] ERROR: Controlled exit resulting from an unrecoverable error or warning.

EXCEPTION: BioL1bDlrNotFound

MESSAGE: Input directory does not exist: /data1/GTDBtk-database/contigs.fasta

**Comment by pchaumeil** [comment]
Hi,
We need more information to debug your issue,
please fill the following form to help us spotting the problem



## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
