### ISSUE TITLE
Required files in the GTDB-Tk db releases

### ISSUE THREAD

**Issue by nick-youngblut** [Ecogenomics/GTDBTk#494]
Given the large size of the GTDB-Tk databases, I'm wondering whether all files are actually required for running GTDB-Tk. If possible, I'd like to reduce the size of my local copies of the various GTDB-Tk database releases that I'm currently storing. The large database size also is a challenge for running GTDB-Tk in Nextflow pipelines, since staging the db files can take many hours.

**Comment by pchaumeil** [comment]
Hello,
We are aware our software requires a lot of storage; the largest part of the GTDB-Tk reference data comes from the inclusion of all GTDB representative genome files (65K in R207). These files are used for the ANI comparison.  Unfortunately, we do not have a practical solution to solve this problem with the current release.  We are, however, investigating potential workarounds for the coming Tk releases.

**Comment by nick-youngblut** [comment]
Thanks @pchaumeil for the clarification! It is a ton of files in the releases, but maybe using an ANI comparison tool that allows for highly compressed representations of the genomic data will help? For instance, maybe switching to [dashing](https://github.com/dnbaker/dashing) and using genome sketches.
