### ISSUE TITLE
gtdbtk doc help not available unless GTDBTK_DATA_PATH is set

### ISSUE THREAD

**Issue by nick-youngblut** [Ecogenomics/GTDBTk#498]
This is a small, but annoying thing:

at least for GTDB-Tk v2.2.6, one cannot view the CLI help docs (e.g., `gtdbtk classify_wf -h`) without first setting a valid path to a GTDB-Tk database.  Otherwise, instead of the help docs, the user gets:

```bash
================================================================================
                                     ERROR                                      
________________________________________________________________________________

          The 'GTDBTK_DATA_PATH' environment variable is not defined.           

            Please set this variable to your reference data package.            
           https://ecogenomics.github.io/GTDBTk/installing/index.html           
================================================================================
```

It would be helpful to evaluate `GTDBTK_DATA_PATH` *after* parsing the CLI args.

**Comment by pchaumeil** [comment]
Hello, 
(This issue is similar to #491)

We will look to reimplement the GTDB-Tk logic so the basic options will not require to set  `GTDBTK_DATA_PATH`. 
This should be available in the next version.

**Comment by nick-youngblut** [comment]
Sorry for the re-post of an existing issue. I had just looked through the open issues prior to creating this one
