### ISSUE TITLE
Questions on a mutually exclusive required argument of classify workflow (--skip_ani_screen or --mash_db)

### ISSUE THREAD

**Issue by ilnamkang** [Ecogenomics/GTDBTk#499]
Hi,

According to README, a mutually exclusive required argument has been included in the classify workflow of GTDB-Tk v2.2.0+: "--skip_ani_screen" or "--mash_db".

I have two questions about this new feature.

1\) Can I expect that I can get identical classification results in most cases irrespective of what options I choose?

2\) If I choose "--skip_ani_screen", then can I expect that GTDBTk would work the same way as the previous versions (e.g., v2.1.0)?

Thanks.

**Comment by pchaumeil** [comment]
Hello,
You can expect very similar results between GTDB-Tk with or without `--skip_ani_screen`

We have have compared Tk results with and without the flag using tens of thousands of genomes and we have notice changes for less than 0.1% of the genomes:

There are 2 main explanations for these changes:
- Before the ani_screen step was available ( i.e in GTDB-Tk 2.1.0), genomes being placed by pplacer as the most basal members of a genus ( i.e above the genus node) were not compared with all species in the genus (ANI was never calculated). 

- Before the ani_screen step was available ( i.e in GTDB-Tk 2.1.0), genomes were only compared with the closest 100 representatives genomes in the same genus. For genera with hundreds of species (  like Collinsella ), This was not enough to find the closest representative based on ANI.

So if your genome fits one of these 2 cases, you may have a slightly different result with or without `--skip_ani_screen`  (ani_screen can return a match with a GTDB representative and return a species name).

**Comment by ilnamkang** [comment]
Thank you for a detailed explanation.
