### ISSUE TITLE
Issue with GTDB::TAXA process

### ISSUE THREAD

**Issue by t-doggg** [Ecogenomics/GTDBTk#501]
## I ran gtdb-tk in miniconda3. Also it's integrated in a pipeline called nanophase. 

[2023-03-31 07:38:27] TASK: Genome taxa classification starts
cat: ont-nanophase-out/03-Polishing/Final-bins/tmp/gtdbtk.log: No such file or directory
[2023-03-31 07:38:27] DONE: genome classification done
cat: 'ont-nanophase-out/03-Polishing/Final-bins/tmp/classify/gtdbtk.*summary.tsv': No such file or directory
[2023-03-31 07:38:27] ERROR: Something wrong with GTDB::Taxa process, terminating...

## Unfortunately I can't provide you with a .log file because I can't find one in any directory. The folder structure is as follows:

miniconda3
  - bin
  - compiler_compat
  - condabin
  - conda-meta
  - envs
  - etc
  - include
  - lib
  - libexec
  - man
  - pkgs
  - release207_v2
      - fastani
      - markers
      - masks
      - metadata
      - mrca_red
      - msa
      - pplacer
      - radii
      - split
      - taxonomy
            - ar53_taxonomy_r207_reps.tsv
            - bac120_taxonomy_r207_reps.tsv
            - gtdb_taxonomy.tsv
      - temp
  - sbin
  - share
  - shell
  - ssl
  - x86_64-conda_cos6-linux-gnu
  - x86_64-conda-linux-gnu

**Comment by t-doggg** [comment]
## I think i was able to trigger some Traceback.
Traceback (most recent call last):
  File "/home/drk/miniconda3/envs/nanophase-v0.2.2/lib/python3.8/site-packages/gtdbtk/__main__.py", line 101, in main
    gt_parser.parse_options(args)
  File "/home/drk/miniconda3/envs/nanophase-v0.2.2/lib/python3.8/site-packages/gtdbtk/main.py", line 1145, in parse_options
    all_classified_ani,classified_genomes = self.ani_screen(options)
  File "/home/drk/miniconda3/envs/nanophase-v0.2.2/lib/python3.8/site-packages/gtdbtk/main.py", line 651, in ani_screen
    check_file_exists(options.batchfile)
  File "/home/drk/miniconda3/envs/nanophase-v0.2.2/lib/python3.8/site-packages/gtdbtk/biolib_lite/common.py", line 96, in check_file_exists

**Comment by pchaumeil** [comment]
Hi,
Could you please provide which command line you are using?
I would also be helpful to get the batchfile and the genomes ( or subset of genomes) you are tying to process.

Thank you

**Comment by t-doggg** [comment]
I use the test dataset/genome from the GitHub page and the following command:
conda activate nanophase 
nanophase meta -l lr.fa.gz -t 40 -o ont-nanophase-out  

The pipeline runs perfectly through until the Gtdb-Tk Program, Nanophase crashes again and again.

Thank you very much for helping me!

**Comment by t-doggg** [comment]
https://github.com/Hydro3639/nanophase/blob/main/Usage_tutorial.md

**Comment by pchaumeil** [comment]
Does nanophase install GTDB-Tk , or do you have to install it separately? 
Which version of Tk is it running?

**Comment by t-doggg** [comment]
The database must be downloaded itself "wget". Gtdb-Tk is installed by Nanophase (via Conda). In the environment Gtdb-Tk has the version 2.2.6. 

When I execute the command, this Error message appears:
gtdbtk classify_wf: error: one of the arguments --skip_ani_screen --mash_db is required

When the argument (--skip_ani_screen) is added, Gtdb-Tk works separately.
The argument --mash_db throws new error messages. 
So Gtdb-Tk works seperately, as it looks.

**Comment by pchaumeil** [comment]
It seems nanophase is using the previous command line of GTDB-Tk:

https://github.com/Hydro3639/NanoPhase/search?q=gtdbtk

you can see that both calls to gtdbtk ( line 312 in bin/nanophase.iso and line 654 in bin/nanophase.meta)  are missing one of "mutually exclusive required arguments" : `--skip_ani_screen` or `--mash_db`

nanophase needs to be updated to reflect the latest cli

**Comment by t-doggg** [comment]
i have corrected the wrong parts and now nanophase runs completely with database.

Thanks for the help!
