### ISSUE TITLE
GTDB-tk version 2.2.6 

### ISSUE THREAD

**Issue by 1023011930** [Ecogenomics/GTDBTk#506]
## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [✔] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU:  Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz 32
- RAM: 65854324 kB
- OS: NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

## Debugging information
- [✔] `gtdbtk.log` has been included (drag and drop the file to upload).
- [✔ ] Genomes have been included (if possible, and there are few).

## Additional comments

Here is my running output file
[nohup.txt](https://github.com/Ecogenomics/GTDBTk/files/11208203/nohup.txt)

**Comment by 1023011930** [comment]
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/11208210/gtdbtk.log)
[Hungate1000_TreponemaspC6A8.fna.gz](https://github.com/Ecogenomics/GTDBTk/files/11208211/Hungate1000_TreponemaspC6A8.fna.gz)

**Comment by 1023011930** [comment]
Thank you so much to seeing what is wrong about the task!

**Comment by pchaumeil** [comment]
Hi , 
In the nohup.txt file you have the following error:

```
==> Step 1 of 9: Starting pplacer.Uncaught exception: Sys_error("/refdata/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")
Fatal error: exception Sys_error("/refdata/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")
```

it seems the GTDB reference data is not properly set.
Please follow the documentation to set the GTDB-Tk reference data ( [here](https://ecogenomics.github.io/GTDBTk/installing/index.html#gtdb-tk-reference-data) ) and make sure you download the [R207_v2](https://data.gtdb.ecogenomic.org/releases/release207/207.0/auxillary_files/gtdbtk_r207_v2_data.tar.gz) package.

**Comment by 1023011930** [comment]
Thank you for your reply. Do you have to re-download the whole database, or is there another update plan?

**Comment by pchaumeil** [comment]
You will have to re-download the whole database
