### ISSUE TITLE
ANI value for all the genomes not available

### ISSUE THREAD

**Issue by saras224** [Ecogenomics/GTDBTk#510]
Hi @donovan-h-parks 

I have used several times GTDBtk pipeline for the classification of the MAGs and now I have few doubts about the results it is giving:

1.  which taxonomy is the final taxonomy? the **classification** or the **fastani taxonomy** or **closest placement taxonomy** or **pplacer taxonomy**?
2. For many genomes is is giving FASTANI value N/A why is that so? I want to plot the ANI vs the alignment fraction of all the MAGs but for many MAGs FastANI is Not available. Please correct me if I am wrong but according to my understanding, the ANI values are only provided if the MAGs are having a reference genome at the genus level otherwise the ANI value comes as N/A? but if I want the ANI value for every MAG at whatever level it is giving the classification would it be possible by changing any parameters when I run gtdbtk classify_workflow command?
3. I have not found any archaeal classification file in the "identify" directory and also I checked the gtdbtk log file it starts directly checking the bacterial markers, not the archaeal markers. Can u explain why is it happening is there something wrong with the script or do I need to change any command to identify the markers for the archaeal genomes too?

Thanks in Advance!!!

GTDB forum:
https://forum.gtdb.ecogenomic.org/

**Comment by pchaumeil** [comment]
Hi,

1. which taxonomy is the final taxonomy?
the **classification** column is the final GTDB-Tk taxonomy

2.  That is correct, we do not return any ANI value if a genome is above a genus node. if you want to compare all your genomes against all GTDB genomes please check the `gtdbtk ani_rep` command.

3. GTDB-Tk automatically checks for both archaeal and bacterial markers. if it doesn't identify any archaeal genomes it will skip all archaeal steps in the rest of the pipeline. Do you expect to have archaea in your dataset?

**Comment by saras224** [comment]
Thanks @pchaumeil !
Yeah, we were expecting archeal genomes as we have detected Archaeal species in the read-based taxonomy using metaphlan4.

**Comment by pchaumeil** [comment]
Genomes in GTDB-Tk are identified as Archaea if they have a higher percentage of archaeal marker present compared to bacterial markers.
We do not have a functionality to enforce the domain identification of the submitted genomes.
Are you expected archaeal genomes, in the final bac120 summary file? Are they flagged as bacteria? They may have a warning explaining they have only few bacterial markers ( but more than archaeal markers)
