### ISSUE TITLE
the output of .tree files

### ISSUE THREAD

**Issue by Wanli-HE** [Ecogenomics/GTDBTk#511]
hi !

i had used version v2.2.6. and after running, i get the annnotation files, but i just find that there are many .tree files, like below:

-rw-r--r-- 1 hsv709 mibi  28M Apr 25 05:47 gtdbtk.bac120.summary.tsv
-rw-r--r-- 1 hsv709 mibi 314K Apr 25 05:47 gtdbtk.bac120.tree.mapping.tsv
-rw-r--r-- 1 hsv709 mibi 454K Apr 25 05:46 gtdbtk.bac120.classify.tree.4.tree
-rw-r--r-- 1 hsv709 mibi 280K Apr 25 05:12 gtdbtk.bac120.classify.tree.7.tree
-rw-r--r-- 1 hsv709 mibi 443K Apr 25 04:40 gtdbtk.bac120.classify.tree.1.tree
-rw-r--r-- 1 hsv709 mibi 453K Apr 25 03:43 gtdbtk.bac120.classify.tree.2.tree
-rw-r--r-- 1 hsv709 mibi 508K Apr 25 02:33 gtdbtk.bac120.classify.tree.6.tree
-rw-r--r-- 1 hsv709 mibi 394K Apr 25 00:02 gtdbtk.bac120.classify.tree.5.tree
-rw-r--r-- 1 hsv709 mibi 500K Apr 24 20:15 gtdbtk.bac120.classify.tree.3.tree

so what does these tree files means ??  and how can i get one tree of total genome

**Comment by Wanli-HE** [comment]
and also i check the tree file, the node is reference genome id (GB_GCA_002423385.1) instead of sample id (for example, bins.1 ..), so it is unconvernient to annotate the tree, do you have  any suggestion one that?

**Comment by pchaumeil** [comment]
Hello,
To reduce the memory footprint , GTDB-Tk v2 uses a divide and conquer approach explained in [here](https://academic.oup.com/bioinformatics/article/38/23/5315/6758240). 
the list of gtdbtk.bac120.classify.tree.<digit>.tree represent all the class-level subtrees used for the classification. 
If you want only one final tree with the classify_wf command, you will need to use the flag `--full_tree` ( but it requires 320G of RAM to run the command).

The trees generated by classify_wf (gtdbtk.bac120.classify.tree.<digit>.tree) are not de novo trees and will be comprised of both GTDB representatives genomes  (i.e. GB_GCA_002423385.1) and your genomes ( bins.1 ) . if you only want a tree made with your genomes you will have to generate a de novo tree.

**Comment by Wanli-HE** [comment]
> 
Hi!

i used "--full_tree", and get a tree file, but it seems like something wrong with the tree file. it is 3M record all the  GTDB representatives genomes that my sample are mapped, but when i open it using itol, it only have 6 nodes. 

here is the tree file, looks like.
![image](https://user-images.githubusercontent.com/58076352/235101582-9c50635d-00a6-44fa-a82b-f2213c568626.png)

and i used version 1.6 to re-run. the tree is like below.
![image](https://user-images.githubusercontent.com/58076352/235101909-a1a0ac17-ebd3-4319-939d-ec7280e9d655.png)

but another question is coming, in the 1.6 version, the tree totally has 333 nodes, which means 333  representatives genomes , but for the annnotation file (gtdbtk.bac120.summary.tsv), in the secod line, "classification" , there are 527 different type taxa that are annotated. so i check the tree file, found some nodes are like g__.., or o__.. or f__ ..., not ( GB_GCA_002423385.1), so what is that? are they the unknown taxa from GTDBTK, in genus, order, family level individually?  and when i trying to track which bins are annotated by these name, so i search these nodes name (starts with g__.., or o__.. or f__ ...) in  gtdbtk.bac120.summary.tsv (second line "classification",  in genus, order, famly level), but no annotated taxa name by that? so how can i corresponding the tree nodes with the bin id?

for the  de novo tree, has gtdbtk  this function to generate it?  what i do:  first, becuase in gtdbtk.bac120.summary.tsv file, total have 527 taxa. so i pick up 527 bins id that are annotated to these 527 taxa, if there are many bins annotated to same taxa, just random pick up one as representatives one. Second, i isolating these 527  representatives bins`  multi-align genomes from gtdbtk.bac120.user_msa.fasta file. third, i used iqtree to generate the de nove tree form that. it that ok from your side?

best,
wanli

**Comment by donovan-parks** [comment]
Trees produced by GTDB-Tk are not compatible with the format expected by iTOL. You can use the `convert_to_itol` command to convert a tree:
https://ecogenomics.github.io/GTDBTk/commands/convert_to_itol.html

I'm not clear on your second question.

**Comment by jiangyoufeng** [comment]
I wonder if I can build a de novo tree by GTDB-Tk?
