### ISSUE TITLE
User Genomes no longer present in .tree file when they were assigned to a related species

### ISSUE THREAD

**Issue by richardstoeckl** [Ecogenomics/GTDBTk#514]
In GTDBTk version 2.1.1, all user supplied genomes were represented with a node and a label in the .tree file generated by the classify_wf workflow. However, in versions starting with 2.2.3 (havent checked the versions in between), this is no longer the case, as only user supplied genomes that are not assigned to a close relative are represented with a label in the .tree file.
Therefore, the .tree file no longer contains all user supplied genomes, which makes visualization difficult.

Is this a bug or is there a hidden flag to return to the old behaviour?

**Comment by pchaumeil** [comment]
To run all genomes through the full pipeline and have them displayed in the final trees , you should use the `--skip_ani_screen` flag instead of the `--mash_db` flag
