### ISSUE TITLE
Genome has more than 70.0% of markers with multiple hits

### ISSUE THREAD

**Issue by chengninghui** [Ecogenomics/GTDBTk#519]
Hi GTDB-Tker,
I am Panpan and I am using GTDB-Tk to classify two potential Klebsiella pneumoniae genomes now. The  bac120 showed both of them  indeed belong to  Klebsiella pneumoniae, while it seem this two genomes had high contamination, as the warnings showed "Genome has more than 81.7% of markers with multiple hits". I wonder if I can speculate the invasive strain by the  "list_multiple_genes" of file "gtdbtk.bac120.markers_summary.tsv", while I have no idea of the taxnomy of these marker genes, so any suggestions for tracing  contamination？

Some multiple_genes for  one genome:
PF01025.20,PF02576.18,PF03726.15,TIGR00006,TIGR00019,TIGR00020,TIGR00043,TIGR00054,TIGR00064,TIGR00065,TIGR00082,TIGR00083,TIGR00084,TIGR00086,TIGR00088,TIGR00090,TIGR00092,TIGR00095,TIGR00115,TIGR00116,TIGR00138,TIGR00158,TIGR00166,TIGR00168,TIGR00186,TIGR00194,TIGR00250,TIGR00337,TIGR00344,TIGR00362,TIGR00382,TIGR00396,TIGR00398,TIGR00414,TIGR00416,TIGR00420,TIGR00431,TIGR00435,TIGR00436,TIGR00442,TIGR00445,TIGR00456,TIGR00459,TIGR00460

Best,
Panpan

**Comment by donovan-h-parks** [comment]
Hi,

GTDB-Tk is not designed to identify the source of contamination so doesn't provide any direct information in this regard. In particular, it doesn't determine the taxonomic affiliation of individual genes. A tool like GUNC or MAGpurify can do a better job of helping identify the source of potential contamination.

Cheers,
Donovan

**Comment by chengninghui** [comment]
Thanks, MAGpurify seems suitable for me.
