### ISSUE TITLE
some gtdb classifications result in loss of species classification?

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#52]
Specifically I am concerned with the following genome:

ncbi gid: GCF_000158075.1
ncbi taxonomy:
d__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Lachnoclostridium; s__[Clostridium] asparagiforme
gtdb taxonomy:
d__Bacteria; p__Firmicutes_A; c__Clostridia; o__Lachnospirales; f__Lachnospiraceae; g__Clostridium_M; s__

Keeping the 'asparagiforme' species classification would not have overlapped with any other classifications so I'm confused as to why it was dropped with the gtdb classification?  Are there any other instances of this that you are aware of and is there any underlying pattern and reasoning behind this type of change?

**Comment by dparks1134** [comment]
Hello. Thank you for bringing this to our attention. I have directed this to the GTDB curation team. You can contact them directly via the GTDB website (http://gtdb.ecogenomic.org/about). In this case, the issue appears to be that this genome is highly similar to GCF_000509045.1 (98.4% ANI) which has no species name. The genome GCF_000509045.1 was selected as the representative in our tree for curation as it is a better quality genome. Unfortunately, the species name was not picked up. We are revamping this process for the next GTDB release with a concerted effort to identify all type strains of species and other commonly used (even if not formally validated) species names.
