### ISSUE TITLE
closest reference has completely different taxonomy in NCBI

### ISSUE THREAD

**Issue by saras224** [Ecogenomics/GTDBTk#520]
Hi @donovan-h-parks 

- I used GTDBtk version 2.1.1 for classifying my MAGs. I found that a MAG is classified as _Moraxella_A cinereus_, but when I saw the column that has the information on the closely related genomes it has detected in first place is a genome with Genome id: GCA_014647715.1. Later, I went on to the NCBI Assembly database to download this reference genome and found that NCBI has classified it as _Streptomyces cinereus_. 

I am providing the line which has the information of that MAG detected by GTDBtk tool:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

user_genome | classification | fastani_reference | fastani_reference_radius | fastani_taxonomy | fastani_ani | fastani_af | closest_placement_reference | closest_placement_radius | closest_placement_taxonomy | closest_placement_ani | closest_placement_af | pplacer_taxonomy | classification_method | note | other_related_references(genome_id,species_name,radius,ANI,AF) | msa_percent | translation_table | red_value | warnings
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
A17_bin.4 | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Moraxella_A;s__Moraxella_A cinereus | GCA_014647715.1 | 95 | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Moraxella_A;s__Moraxella_A cinereus | 96.07 | 0.94 | N/A | N/A | N/A | N/A | N/A | d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Moraxella_A;s__ | ANI | topological placement and ANI have incongruent species assignments | GCA_014647715.1, s__Moraxella_A cinereus, 95.0, 96.07, 0.94; GCF_001553955.1, s__Moraxella_A osloensis, 95.0237, 95.48, 0.89; GCF_009867135.1, s__Moraxella_A sp002478835, 95.0237, 94.85, 0.87; GCF_001591265.1, s__Moraxella_A atlantae, 95.0, 81.18, 0.3; GCF_000379845.1, s__Moraxella_A boevrei, 95.0, 79.31, 0.21; GCF_000320365.1, s__Moraxella_A macacae, 95.0, 78.01, 0.17 | 58.54 | 11 | N/A | N/A

</body>

</html>

I would like to know the possible explanation for this ambiguous detection by GTDBtk. 

- Also, I have another question : What does "A" represent in _Moraxella_A osloensis_? The closest reference for Moraxella_A osloensis is named _Moraxella osloensis_ by NCBI. 

Thanks in Advance!
Saras :)

**Comment by pchaumeil** [comment]
Hello,

GTDB-Tk taxonomy is based on the Genome Taxonomy Database (GTDB) which is different than NCBI taxonomy. You can find a manuscript describing this taxonomy by clicking on [this link](https://www.nature.com/articles/nbt.4229) or by visiting the [GTDB Website](https://gtdb.ecogenomic.org/). 

About _Moraxella_A_:
"Genus names ending with an alphabetic suffix indicate genera that are i) polyphyletic according to the current GTDB reference tree, or ii) subdivided based on taxonomic rank normalisation according to the current GTDB reference tree.

Species names end with an alphabetic suffix if the GTDB species cluster is (or was previously) associated with a species name, but the correct application of this name is ambiguous or the name assigned to a different GTDB species cluster based on the presence of type material or via majority voting.

The lineage or species cluster containing the nomenclature type or, in case of species, satisfying the majority vote criteria retains the unsuffixed name and all other lineages/clusters are given alphabetic suffixes, indicating that they are placeholder names that need to be replaced in due course. A best effort is made to retain the same alphabetical suffix for a taxon between GTDB releases, but this is not guaranteed."
