### ISSUE TITLE
[Feature request] Separate script to create --mash_db from database without running GTDB-Tk

### ISSUE THREAD

**Issue by jolespin** [Ecogenomics/GTDBTk#523]
I have GTDB-Tk as an essential step in my [VEBA classify-prokaryotic.py module](github.com/jolespin/veba).  For the install, I download all the required databases prior to using the software.  However, the creation of the --mash_db on first run creates a problem because I want the database directory to be in a read-only location and to be able to be used by multiple users. 

Is there any way I can create the --mash_db without running GTDB-Tk? I want this to be part of my database build command. 

If not, can you provide an accessory script that can achieve this for use cases mentioned above and/or even better add it to database files?

**Comment by pchaumeil** [comment]
Hello,
You can create the mash db compatible with GDB-Tk  by simply running the command:

`>> mash sketch -l -p <number_of_cpus> <input_file> -o <output_file> -k 16 -s 5000
`

where 
`input_file` is a file listing all paths to representative genomes in GTDB-Tk
`output_file` is the name of the .msh file created

the command to generate the input_file is as follows:
`>> find /full/path/to/gtdbtk/package/release214/fastani/database/ -name '*gz' > path_genomes.lst
`

the final command will look like :
`mash sketch -l -p 32 path_genomes.lst -o mash.msh -k 16 -s 5000
`
