### ISSUE TITLE
prodigal on one star in the faa output file

### ISSUE THREAD

**Issue by jianshu93** [Ecogenomics/GTDBTk#527]
Dear GTDB-tk team,

In some very rare cases, I have only a stop codon in a sequence using prodigal, nothing before it. I was using the meta mode for bacterial genomes. Is there a fix or why this happens? I was parsing the aa file using a standard pipeline but it complains in some rare cases where only a star in one sequence. I also asked the same question under prodigal but no response, I feel like the GTDB-tk team might have some experience. 

Thanks,

Jianshu

**Comment by pchaumeil** [comment]
Hello Jianshu,
Apologies we haven't encountered with any of our tests so I am not sure what would be the fix for this problem.
