### ISSUE TITLE
ERROR: Uncontrolled exit resulting from an unexpected error

### ISSUE THREAD

**Issue by MonsterLaplace** [Ecogenomics/GTDBTk#529]
(gtdbtk) xb@zooeco-ESC8000A-E12:~/metagenome/database$ gtdbtk test --out_dir /mnt/z/xb/test
[2023-07-05 16:33:48] INFO: GTDB-Tk v2.3.0
[2023-07-05 16:33:48] INFO: gtdbtk test --out_dir /mnt/z/xb/metagenome/test
[2023-07-05 16:33:48] INFO: Using GTDB-Tk reference data version r214: /mnt/z/xb/database/db
[2023-07-05 16:33:48] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: ValidationError
  MESSAGE: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
________________________________________________________________________________

Traceback (most recent call last):
  File "/mnt/z/xb/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/__main__.py", line 100, in main
    gt_parser = OptionsParser(__version__,
  File "/mnt/z/xb/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 86, in __init__
    self.stage_logger = StageLogger()
  File "/mnt/z/xb/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/files/stage_logger.py", line 172, in __new__
    StageLogger.instance = StageLogger.__StageLogger(steps=[])
  File "/mnt/z/xb/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
================================================================================

**Comment by GeoMicroSoares** [comment]
The same is happening to me as well using `gtdbtk` versions 2.3.0 and 2.2.6 - thanks in advance for any help!

**Comment by Sidduppal** [comment]
Getting the same error as well after doing a fresh install yesterday.

**Comment by MonsterLaplace** [comment]
Problem solved, thank you for your quick response.

**Comment by GeoMicroSoares** [comment]
Hi there - FYI after this solve I was only able to run gtdtk after downgrading gsl to 2.6 - maybe that can be helpful for you! Thanks!

**Comment by pchaumeil** [comment]
Thanks for your feedback!

**Comment by kunaljaani** [comment]
Hi!
If someone is still struggling with this error, the following may help.

python -m pip install gtdbtk --upgrade    #v2.3.2
conda env config vars set GTDBTK_DATA_PATH="/path/to/unarchived/gtdbtk/data"           
or
export GTDBTK_DATA_PATH=/path/to/release/package/
restart your session
