### ISSUE TITLE
command to set_root for data

### ISSUE THREAD

**Issue by elizabethmcd** [Ecogenomics/GTDBTk#53]
Hello, 

I have built a Docker image for gtdbtk and all the dependencies, however due to the size of the database files, I can't build that within the docker image. The ultimate goal is to pull the docker image on VMs or a cluster so the installation process is easier. Specifically I was wondering if there was a way to create a command like in checkm to set the root to direct where the data files are instead of manually creating and changing the config.py file. Manually editing this file isn't really possible when submitting jobs to a cluster. Not sure if this is possible, but thought I would ask since I think a docker implementation could make it easier for a lot of people to use this tool.

**Comment by dparks1134** [comment]
Thank you for the comment. I agreed this would be a useful feature. We have put this on our to-do list, but we are a bit swamped with other development tasks at the moment so I don't expect this will happen in the short term.

**Comment by aaronmussig** [comment]
A bit of an old ticket sorry, but I believe this has been resolved with the use of the GTDBTK_DATA_PATH environment variable. Feel free to re-open the ticket if that's not the case.
