### ISSUE TITLE
Missing MAGs during de_novo_wf 

### ISSUE THREAD

**Issue by XC-Zhai** [Ecogenomics/GTDBTk#535]
GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum:

GTDB forum:
https://forum.gtdb.ecogenomic.org/

Hi I am using GTDB-Tk v2.3.0 to generate output for the use of IPHOP (https://bitbucket.org/srouxjgi/iphop/src/main/) with following command:
gtdbtk de_novo_wf --genome_dir cow_MAGs/ --bacteria --outgroup_taxon p__Bacillota --out_dir cow_MAGs_GTDB-tk_results/ --cpus 36 --force --extension fasta
gtdbtk de_novo_wf --genome_dir cow_MAGs/ --archaea --outgroup_taxon p__Methanobacteriota --out_dir cow_MAGs_GTDB-tk_results/ --cpus 36 --force --extension fasta

However, I found one the genome bin was not found from either gtdbtk.ar53.decorated.tree or gtdbtk.bac120.decorated.tree. Is this normal? 
Do you have any suggestion?

Best regards,
Xichuan

**Comment by pchaumeil** [comment]
Hi, 
Can you attach the gtdbtk.log generated from your command?

Thanks

**Comment by XC-Zhai** [comment]
[gtdbtk.log.txt](https://github.com/Ecogenomics/GTDBTk/files/12174720/gtdbtk.log.txt)
Please find the attached log from gtdbtk.

**Comment by pchaumeil** [comment]
Looking at your log it seems 3 archaeal genomes and 126 bacterial genomes have been filtered out from the tree creation. It is normal, some genomes wont have enough markers to be accurately placed in a de novo tree. These genomes are filtered out before the tree creation. do you have `failed.tsv` files and/or `filtered.tsv` files in the output directory?

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
