### ISSUE TITLE
installing on osx

### ISSUE THREAD

**Issue by Valentin-Bio** [Ecogenomics/GTDBTk#537]
Hello I'm trying to install gtdbtk on a MacOS via conda and I'm getting the following error message:

`conda install gtdbtk`

**UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - gtdbtk -> matplotlib-base -> __osx[version='>=10.11|>=10.12']**

it's clear that the matplotlib dependence is not available for my osx version, is there a way in which I can handle that? 

bests,

Valentín.

**Comment by pchaumeil** [comment]
Hello,

Unfortunately one of the third-party dependencies (pplacer) doesn't run on either the Intel or Silicon macs. You can run it in a Docker container though: https://ecogenomics.github.io/GTDBTk/installing/docker.html
