### ISSUE TITLE
Add script to rename the taxonomy in the phylogenetic tree

### ISSUE THREAD

**Issue by michoug** [Ecogenomics/GTDBTk#54]
Hi,
Would it be possible to add/create a script to replace the GCF_XXXX/UBAXXX in the trees with the taxonomy, such as d__XXX; p__XXX; c__XXX; o__XXX etc...
Thanks!
Greg

**Comment by aaronmussig** [comment]
Hi, if I understood your query, i.e. updating the leaf nodes - there is nothing in the works to do this unless some more interest is shown.

This should just be a matter of writing a script to do a find and replace. You can use the taxonomic data available online [ar122](https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/ar122_taxonomy.tsv) or [bac120](https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/bac120_taxonomy.tsv). Here's a rough idea of what you could write (probably could be done better in bash):

```
import re

TAX = '/tmp/ar122_taxonomy_r89.tsv'
TREE = '/tmp/gtdbtk.ar122.classify.tree'
TREE_OUT = '/tmp/gtdbtk.ar122.classify_edit.tree'

mapping = dict()
with open(TAX, 'r') as f:
    for line in f.readlines():
        gid, tax = line.strip().split('\t')
        mapping[gid] = tax

with open(TREE, 'r') as f:
    tree = f.read()

for gid, tax in mapping.items():
    tree = re.sub(r'(' + gid + '):', f"'{tax}':", tree)

with open(TREE_OUT, 'w') as f:
    f.write(tree)
```
