### ISSUE TITLE
when can we say species is not known

### ISSUE THREAD

**Issue by saras224** [Ecogenomics/GTDBTk#546]
Hi GTDBtk team!
I have been using the GTDBtk classification tool for a long time now and I have read a few papers that used your tool to classify their MAGs and they are claiming their MAGs to be novel when they are not classified at the level of species. But I am wondering what if the MAG is not classified at the level of the species but there is a reference genome already available with an ANI value of more than 95%, in this case, can we claim the MAG might be a novel species? I am attaching a screenshot in which some of the MAGs have been identified to a reference genome but that reference genome is also an unclassified MAG, can we say this is a novel species?

![Screenshot from 2023-08-24 16-05-38](https://github.com/Ecogenomics/GTDBTk/assets/77498189/0bdbd8ac-3f57-465b-9eac-05510908ab1b)

Please clear my doubts so that I can proceed further with the results. 

Thanks! :)

**Comment by donovan-h-parks** [comment]
Hi,

I don't believe that this is typically what people refer to as a novel species. These species clusters are known in GTDB and defined by previously recovered MAGs. I think it would be more accurate to refer to these as MAGs assigned to "species with placeholder names in the GTDB taxonomic framework", or wording to that effect.

In contrast, a truly novel MAG (relative to the GTDB) would be one where GTDB-Tk did not provide a species assignment.

Cheers,
Donovan

**Comment by saras224** [comment]
Hey1
Thanks for the response, do you mean the ones which have a reference genome
with placeholder names like "Bacteroidetes bacterium UBA2030" are not
novel, and all those which are not assigned to a particular taxonomy level
can be novel at that particular level, for example a MAG assigned a
"c__EVY21" and not assigned at order level "o__". So its a novel MAG at the
order level?

Thanks :)

**Comment by donovan-h-parks** [comment]
A placeholder name indicates a taxon that is described by the GTDB. In this sense, it is not novel as it is known to GTDB and there are already genomes assigned to the taxon. 

Yes, if GTDB-Tk assigns a MAG to "c__EVY21; o__; f__; g__; s__" it indicates that the MAG belongs to a novel Order within the GTDB taxonomic framework.

**Comment by saras224** [comment]
Thanks a lot Donovan!!!!
