### ISSUE TITLE
'classify/gtdbtk.ar53.classify.tree' not generated

### ISSUE THREAD

**Issue by bolangsha** [Ecogenomics/GTDBTk#548]
## Environment
- [ ] Using a Docker container (include the `IMAGE ID` of the container)
ecogenomic/gtdbtk:2.3.2
## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

Hi,
When i used gtdbtk (docker Environment ) to analysis archaea genome, the 'gtdbtk.ar53.summary.tsv' file could be generated, but the 'classify/gtdbtk.ar53.classify.tree' could not generated. And if I use bacteria genome , the summary.tsv  and classify.tree file could be both generated. so when I use 'gtdb_to_ncbi_majority_vote.py', there could encount  an error---No such file or directory: '/path/classify/gtdbtk.ar53.classify.tree'.
 I test several different version(2.2.4、2.2.6、2.3.0、2.3.2) and two GTDB-Tk reference data(R214 and R207_v2), the problem still exists.
Thanks.

**Comment by pchaumeil** [comment]
Hello,
Could you please provide the `gtdbtk.log` file for your analysis.
One of the reason the classify.tree may be missing is that all your genomes have been classified using the `ANI step`. if its the case, no genomes would go through the full pipeline.

Thanks,
Pierre

**Comment by bolangsha** [comment]
Hi,
Thank you for your reply. 
Yes, I tested four genomes, three bacteria, one archaea, and the genome of archaea and one bacteria genome were classified using the ANI step. So if I use the 'gtdb_to_ncbi_majority_vote.py'  without the corresponding tree file, how can I successfully perform the gtdbtk to ncbi taxonomy?

Thanks

**Comment by bolangsha** [comment]
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/12679338/gtdbtk.log)

**Comment by pchaumeil** [comment]
Hello, 
The gtdb_to_ncbi_majority_vote.py script has been updated and now work without domain specific tree when the classification is done using ANI.

Cheers,
Pierre
