### ISSUE TITLE
[] are not present in the input list of genome to process 

### ISSUE THREAD

**Issue by anatmaozcrispr** [Ecogenomics/GTDBTk#549]
running:
gtdbtk de_novo_wf --batchfile run_genomes.txt --bacteria --outgroup_taxon p__Chloroflexota --out_dir gtdb -x fa --cpus 10 --force --debug
[2023-09-20 18:41:24] ERROR: [] are not present in the input list of genome to process.
[2023-09-20, 21:41:24 IDT] {pod_manager.py:382} INFO - [2023-09-20 18:41:24] ERROR: Controlled exit resulting from an unrecoverable error or warning.
there are 11 bacteria that Prodigal cannot find genes for. BUT de_novo_wf throws an exception instead of continuing with the rest. I thought "--force" would take care of it.

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by anatmaozcrispr** [comment]
anyone knows why "--force" does not do anything?

**Comment by pchaumeil** [comment]
Hello, 
Seems like an issue with Tk
Are you getting this error when you run --force on a new output_directory? or an existing one with data already in it?
