### ISSUE TITLE
de_novo_wf Bootstrap values

### ISSUE THREAD

**Issue by yunha** [Ecogenomics/GTDBTk#55]
Hi, I've been using the de_novo_wf, it has been very helpful in visualising the data! I was wondering if there is a way to incorporate bootstrapping in this wf? any suggestions?

**Comment by dparks1134** [comment]
You might find the SumTrees script by Dendropy useful:
https://dendropy.org/programs/sumtrees.html

I don't expect we will incorporate bootstrapping into the GTDB-Tk since we'd like to keep it focused on taxonomic classification than a full software suite for phylogenetic inference.
