### ISSUE TITLE
failed to process sequence file "gzip.baggzipfile: not a gzipped file (b'>k')" and prodigal non-zero exit code

### ISSUE THREAD

**Issue by sophiaaredas** [Ecogenomics/GTDBTk#553]
Hello I hope this message finds you well. I am currently working with a large metagenomic dataset and am trying to use GTDB-Tk to create a phylogeny tree. However when I input the command in my conda environment gtdbtk classify_wf --genome_dir /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs --out_dir classify_gtdbtk_output --mash_db 2.3.2 -x .fa.gz --cpus 100
#gtdbtk = command

However this appears on my terminal screen:
gzip.BadGzipFile: Not a gzipped file (b'>k')
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91618_DAStool_bin8.fa.gz

Process Process-132:

[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91619_DAStool_bin144.fa.gz
Process Process-111:

[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91620_DAStool_bin1.fa.gz

Traceback (most recent call last):
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/biolib_lite/seq_io.py", line 64, in read_fasta
    for line in f.readlines():
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/gzip.py", line 305, in read1
    return self._buffer.read1(size)
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'>k')
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91620_DAStool_bin39.fa.gz

Process Process-121:
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91620_DAStool_bin74.fa.gz
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91621_DAStool_bin71.fa.gz
Process Process-105:

Process Process-129:

Process Process-106:
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91621_DAStool_bin74.fa.gz
Process Process-118:
Process Process-116:
Process Process-120:
Process Process-134:
Process Process-130:
Process Process-152:
Process Process-126:
Process Process-128:
Process Process-115:

Traceback (most recent call last):
Exception: An error was encountered while running Prodigal.
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 109, in _run_prodigal
[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91627_DAStool_bin32.fa.gz

[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91627_DAStool_bin42.fa.gz

[Error] Failed to process sequence file: /local/workdir/sna49/SA_Fall2023/Data/346_MAGs/Output/gtdbtk_files/346_MAGs/91627_DAStool_bin57.fa.gz
[2023-10-23 11:14:49] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 211, in run
    raise ProdigalException('Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 1167, in parse_options
    self.identify(options,classified_genomes)
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 319, in identify
    reports = markers.identify(genomes,
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/markers.py", line 205, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/home/sna49/miniconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 220, in run
    raise ProdigalException(f'An exception was caught while running Prodigal: {e}')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.

It appears that some files are able to be processed by GTDB-Tk but weirdly some files are not capable of being read? I have checked to see that the files it is not able to analyze are not corrupted and I have downloaded them from the original source multiple times and they are fine. These .gz files are able to be opened in other programs but for some reason GTDB-Tk seems to not be able to open them.

I have tried looking through the opened and closed issues and I cannot seem to debug this problem. Thank you so much!

**Comment by sophiaaredas** [comment]
My bad I seemed to fix it by just using the .fa file

**Comment by sophiaaredas** [comment]
sorry I meant to leave the issue open as I think there is something wrong with the python code that seems to prevent using .gz files

**Comment by pchaumeil** [comment]
Hi ,

What happens if you unzip then re-zip the one genome (91618_DAStool_bin8.fa.gz for example) ? Can this genome be processed?
The error `gzip.BadGzipFile: Not a gzipped file (b'>k')` could be raised because you are trying to run a genome that could be corrupted or not really being in GZip format.

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
