### ISSUE TITLE
Not all genomes identified

### ISSUE THREAD

**Issue by sophiaaredas** [Ecogenomics/GTDBTk#554]
Hello I am also experiencing the same issue as issue #356 but with version GTDB-Tk v2.3.2. I have a total of 346 genomes that I am trying to analyze and when I do classify_wf it appears that only 188/346 genomes are aligned. I have no clue why it is doing this but it appears that for de_novo_wf it is able to classify the 346 genomes. I am rerunning the classify_wf command again for a third time but I am only able to get 188/346 genomes classified. Additionally, there is nothing written in my gtdbtk.warnings.log nor my gtdbtk.failed_genomes.tsv files. Any help is greatly appreciated!

I have uploaded my classify_wf and its name is gtdbtk_classify.log. You will see that it is able to complete 346 genomes with Mash sketch file but once it gets to identifying markers, only 188 genomes are identified.

Additionally I have also uploaded my de_novo_wf log and it is called gtdbtk_denovo1.log. It is still in the middle of running but you will see that it was able to create an alignment for 346 genomes.

I am using a dataset that has been previously used in my lab and previously the GTDBTK v207 release was able to complete and identify markers in all 346 genomes in this dataset.

Thank you so much for your time!

[gtdbtk_classify.log](https://github.com/Ecogenomics/GTDBTk/files/13127415/gtdbtk_classify.log)
[gtdbtk_denovo1.log](https://github.com/Ecogenomics/GTDBTk/files/13127448/gtdbtk_denovo1.log)

**Comment by pchaumeil** [comment]
Hello,

Looking at the `gtdbtk_classify.log` file you have the following note:
```
[2023-10-23 12:09:52] INFO: 158 genome(s) have been classified using the ANI pre-screening step.
[2023-10-23 12:09:52] INFO: Done.
[2023-10-23 12:09:52] INFO: Identifying markers in 188 genomes with 100 threads.
```
So 158 genomes are classified with ANI and will not be processed in the rest of the pipeline ( Identify, Align and Classify steps) but they will be present in the final summary file.

To avoid genomes be pre-filtered with the ANI step, you can use the `--skip_ani_screen` flag. With this flag, all genomes will go through the full pipeline and it should give you an alignment for the 346 genomes.
