### ISSUE TITLE
gtdbtk: error: unrecognized arguments: --mash_db

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [Ecogenomics/GTDBTk#557]
## Environment

Using a conda environment (include the output of `conda list && conda list --revisions`)
# packages in environment at /tllhome/abel/mambaforge/envs/gtdbtk-2.1.1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
capnproto                 0.10.2               h6239696_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
dendropy                  4.6.1              pyhdfd78af_0    bioconda
fastani                   1.3                  he1c1bb9_0    bioconda
fasttree                  2.1.11               h031d066_2    bioconda
gsl                       2.7                  he838d99_0    conda-forge
gtdbtk                    2.1.1              pyhdfd78af_1    bioconda
hmmer                     3.1b2                         3    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.43.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mash                      2.3                  hd3113c8_6    bioconda
ncurses                   6.4                  h59595ed_1    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                h031d066_6    bioconda
python                    3.8.15          h257c98d_0_cpython    conda-forge
python_abi                3.8                      4_cp38    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

When I run :
 gtdbtk classify --mash_db /tlldata/HenningLab/abel/dereplicated_genomes_all_taxon/test_mash --align_dir HenningLab/abel/dereplicated_genomes_all_taxon/test_align --genome_dir /tlldata/HenningLab/abel/test_genomes  --out_dir /tlldata/HenningLab/abel/dereplicated_genomes_all_taxon/test_taxon

it says
gtdbtk: error: unrecognized arguments: --mash_db /tlldata/HenningLab/abel/dereplicated_genomes_all_taxon/test_mash

**Comment by pchaumeil** [comment]
Hello, 
`--mash-db` and `--skip_ani_screen` were implemented in GTDB-Tk `v2.2.0`. Please update your version of GTDB-Tk is you want to use these flags.

Regards,
Pierre
