### ISSUE TITLE
The annotation results of gtdbtk are inconsistent with the Phylogenetic position.

### ISSUE THREAD

**Issue by wanxn518** [Ecogenomics/GTDBTk#558]
Hello, GTDB team

I use GTDBtk version 2.3.2 to classify my MAGs, so I know that these MAGs belong to a certain phylum and a certain class. However, in the phylogenetic tree, they are inferred to be other classes in the same phylum. Is this because the MAGs was incorrectly classified when it run classify_wf? Can you give me some suggestions? Thank you sincerely in advance!

![image](https://github.com/Ecogenomics/GTDBTk/assets/97587984/da259570-d0c8-49eb-a04e-c57242d19a04)

Best,
xnw

**Comment by wanxn518** [comment]
Hi Donovan,

Thank you very much for your reply.
I've identified a number of classifications of MAGs through GTDBtk. 
`gtdbtk classify_wf --genome_dir MAGs/ --out_dir GTDB_Result -x  fna --prefix KON --cpus 24 --skip_ani_screen` The classification results of these MAGs belong to p__Actinomycetota,c__Geothermincolia in `bac120.summary.tsv`.

I used these MAGs to make phylogenetic trees run  `gtdbtk de_novo_wf`
However, in the phylogenetic tree, the phylogenetic positions of individual MAGs are at p__Actinomycetota & c__Actinomycetia，and is also inferred in the `de_novo_wf/infer/gtdbtk.bac120.decorated.tree-taxonomy` as `d__Bacteria; p__Actinomycetota; c__Actinomycetia; o__; f__; g__; s__`
![image](https://github.com/Ecogenomics/GTDBTk/assets/97587984/7d433bf7-7259-4577-9ba9-9772b25d3aa2)

These are a few MAGs whose classification results from `gtdbtk classify_wf` don't agree with the phylogenetic position, and I'm not sure what their classification results actually are? Looking forward to your help and sincerely appreciate it in advance! 

Best,
xnw

**Comment by donovan-h-parks** [comment]
Hi xnw,

I assume your MAGs are the red entries marked with "???" - yes? It appears the challenge here is that in the de novo tree Actinomycetia is no longer a monophyletic group. Your MAGs are sister to Geotherminicolia and could reasonably be consider the most basal lineage of this class if it weren't for the small subset of Actinomycetia that have moved and are causing Actinomycetia to be polyphyletic. This is, unfortunately, the challenge of doing taxonomic classification with a de novo tree. As it stands, there is no clear classification for your MAGs. They could be considered a basal lineage of Geothermincolia or a new class within the Actinomycetota. Additional trees using different marker genes, evolutionary models, and inference methods are required to resolve which of these scenarios is best supported.

Cheers,
DOnovan

**Comment by phugenholtz** [comment]
Could you send me a high resolution image of your tree please xnw (so I can read the tip names). I suspect this is a know problematic region and I may have a solution.Thx, PhilSent from my iPhoneOn 22 Nov 2023, at 00:48, Donovan H. Parks ***@***.***> wrote:﻿
Hi xnw,
I assume your MAGs are the red entries marked with "???" - yes? It appears the challenge here is that in the de novo tree Actinomycetia is no longer a monophyletic group. Your MAGs are sister to Geotherminicolia and could reasonably be consider the most basal lineage of this class if it weren't for the small subset of Actinomycetia that have moved and are causing Actinomycetia to be polyphyletic. This is, unfortunately, the challenge of doing taxonomic classification with a de novo tree. As it stands, there is no clear classification for your MAGs. They could be considered a basal lineage of Geothermincolia or a new class within the Actinomycetota. Additional trees using different marker genes, evolutionary models, and inference methods are required to resolve which of these scenarios is best supported.
Cheers,
DOnovan
