### ISSUE TITLE
How to understand RELATIVE EVOLUTIONARY DIVERSION (RED)?

### ISSUE THREAD

**Issue by wanxn518** [Ecogenomics/GTDBTk#560]
Dear GTDBtk team,

After reading your article and github question about the RED value, I still have some questions.

In the results from the run using `gtdbtk classify_wf`, REDs were calculated for many MAGs, but why can a MAG have a RED value? The article "A standardized bacterial taxonomy based on genome phylogeny substantially revises the tree of life" mentions: The root of the tree is defined to have a RED of zero, and leaf nodes have a RED of one.
Regardless of the method used to make the phylogenetic tree, the position of the MAG in the phylogenetic tree is always at the outermost leaf node, so RED should be equal to 1? 

In addition，`RED intervals for normalizing taxa at taxonomic ranks was operationally defined as the median RED value (indicated by a blue bar) at each rank ±0.1 (indicated by grey bars)`  How is the median value of each classification level determined? Can I know what the median value is for each classification level?

I'm a newbie to GTDB, thank you for the great tool you have developed, looking forward to your reply and sincerely thank you in advance!

Best,
wanxn

**Comment by donovan-h-parks** [comment]
Hi wanxn,

Indeed your MAG is an extent taxon with an RED = 1. The RED in the GTDB-Tk output refers to the parent node of your MAG in the reference tree. This is used to determine how the MAG should be classified relative to the GTDB taxonomy. For example, if the parent node of your MAG is close to the root your MAG may be determined to be a novel phylum. The GTDB-Tk manuscript has some illustrations of how RED is use to classify a MAG: https://academic.oup.com/bioinformatics/article/36/6/1925/5626182.

The median RED values are determined by re-rooting the tree above each phyla. RED is a relative measurement so the values are only applicable to the tree on which they are calculated. Knowing the value on one tree should not, in general, guide decisions on another tree which span a different set of genomes or was inferred with a different method, MSA, etc. As such, we don't generally make median RED values  available as it is not informative and don't want to give the impression that is should be used in downstream applications.

Cheers,
Donovan

**Comment by wanxn518** [comment]
Hi phugenholtz,

This tree, consisting of MAGs of different classes from the outgroups and phylum Actinomycetes, with branches coloured to represent the outlines of the GTDB's classification from 'gtdbtk classify_wf'.

I would like to know the branches marked as "??? " exactly where the MAGs belong to the c__Actinomycetia or c__Geothermincolia ?  

Thank you for your help.

Best,
wanxn
[tree.pdf](https://github.com/Ecogenomics/GTDBTk/files/13433693/tree.pdf)

**Comment by phugenholtz** [comment]
Hi wanxn

thanks for the tree, but I need to see at least the order classification in
this tree, or better still names at tips (genome acc ids are fine).

thx, Phil

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
