### ISSUE TITLE
Cannot open classify.tree file in Dendroscope

### ISSUE THREAD

**Issue by lewhiteside** [Ecogenomics/GTDBTk#563]
Hi there, Im having trouble viewing my tree in Dendroscope - any help would be greatly appreciated!

Here is what I have done so far:

Install GTDB-Tk and set up environment

`mamba create -c conda-forge -c bioconda gtdbtk=2.3.2 `

download reference data. (using in-house script)

`download-db.sh`

Verify integrity of database ( looks good!)

`gtdbtk check_install`

Run classify_wf :

'gtdbtk classify_wf --genome_dir NovaSeq/Bins/BELFAST/BEL011121_S133_Refined --out_dir NovaSeq/Bins/BELFAST/BEL011121_S133_classify_wf_out_2 --skip_ani_screen --cpus 3  --prefix BEL011121_S133'

remove internal labels from Newick tree, making it suitable for visualization in [iTOL](http://itol.embl.de/)

'gtdbtk convert_to_itol --input NovaSeq/Bins/BELFAST/BEL011121_S133_classify_wf_out/classify/BEL011121_S133.bac120.classify.tree --output NovaSeq/Bins/BELFAST/BEL011121_S133_classify_wf_out/classify/BEL011121_S133.bac120.classify.itol.tree'

- I was able to view this is itol, but when I upload the classify.tree file to dendroscope (v 3.8.10) - i get the following error:

Execute failed: Line 1: ',' expected, got: 's'

Thank you in advance for any help!

Louise

**Comment by pchaumeil** [comment]
Hello, 
Apologies for the very late reply,
Do you still have an issue with dendroscope?

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
