### ISSUE TITLE
pydantic.dev/2.6/v/missing

### ISSUE THREAD

**Issue by WUD2018** [Ecogenomics/GTDBTk#569]
I have downloaded and installed the gtdb-tk v 2.3.0 the via mamba as suggested by the https://ecogenomics.github.io/GTDBTk/installing/bioconda.html

However, when I run the command, 'pydanic.dev.error' occured. Could you please kindly help me out? thanks.

[2024-02-03 10:20:10] INFO: GTDB-Tk v2.3.0
[2024-02-03 10:20:10] INFO: gtdbtk classify_wf --cpus 40 --genome_dir ./ --out_dir ./AnimFece80_gtdbtk2.3_output --extension fa --prefix AnimFece80 --min_af 0.80 --skip_ani_screen
[2024-02-03 10:20:10] INFO: Using GTDB-Tk reference data version r214: /home/disk1/DataBase/GTDBTK-2.3.0/release214
[2024-02-03 10:20:10] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: ValidationError
  MESSAGE: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/disk1/Anaconda3/envs/mamba/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 100, in main
    gt_parser = OptionsParser(__version__,
  File "/home/disk1/Anaconda3/envs/mamba/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/main.py", line 86, in __init__
    self.stage_logger = StageLogger()
  File "/home/disk1/Anaconda3/envs/mamba/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/files/stage_logger.py", line 172, in __new__
    StageLogger.instance = StageLogger.__StageLogger(steps=[])
  File "/home/disk1/Anaconda3/envs/mamba/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
================================================================================

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by pchaumeil** [comment]
Hello, 
Please download the latest version of GTDB-Tk ( 2.3.2). This should fix this issue.

Cheers,
Pierre
