### ISSUE TITLE
Using gtdb_to_ncbi_majority_vote.py script to convert gtbd taxonomy to SILVA taxonomy 

### ISSUE THREAD

**Issue by tarunaaggarwal** [Ecogenomics/GTDBTk#575]
Hello,

I have some MAGs that I'd like to compare with my ASVs which were taxonomically classified using SILVA 138. My advisor found your `gtdb_to_ncbi_majority_vote.py` script that converts gtdb taxonomy to NCBI, but I was wondering if I can change this script easily to use to convert gtdb taxonomy to SILVA taxonomy. Might you please suggest the best way to do so? Thank you!

Taruna

**Comment by donovan-h-parks** [comment]
Hi Taruna,

Sorry for the slow reply. Did you have any success making this modification? It may be possible if you can get the SILVA taxonomy for all genomes in the GTDB-Tk reference tree. If you do have such a script and are willing to share it, I'm sure others would appreciate you posting it here.

Cheers,
Donovan

**Comment by tarunaaggarwal** [comment]
Hi @donovan-h-parks - no worries!  But honestly, I don't even remember what my goal was back then so you can close the issue. Thank you!
