### ISSUE TITLE
Getting the GTDB version used from GTDB-Tk

### ISSUE THREAD

**Issue by wwood** [Ecogenomics/GTDBTk#578]
Hi there,

Is there some way to determine what GTDB version underlies a certain GTDB-Tk version?

I'm looking for something along the lines of
```
$ gtdbtk gtdb-version
08-RS214
```

I have two sets of taxonomies. One I know the provenance of, and the other is generated by GTDB-Tk, so just wanting to know if they match up.

Thanks, ben

**Comment by pchaumeil** [comment]
Hi Ben,
when opening a `gtdbtk.log` file generated by any of Tk command, one of the first line of the file should tell you which version  if GTDB is used to run this command.

`[2022-07-11 11:30:31] INFO: Using GTDB-Tk reference data version r207: /srv/db/gtdbtk/official/release207_v2/`

Thanks,
Pierre

**Comment by wwood** [comment]
cheers.
