### ISSUE TITLE
Incomplete tree

### ISSUE THREAD

**Issue by KunathBJ** [Ecogenomics/GTDBTk#59]
Hello,

I've tried GTDB on few MAG (31) and while it seemed to have run just fine, when exploring the gtdbtk.bac120.classify.tree I can only see 7MAGs with name such as: GB GCA 001796995.1 or f  SM23-28-2' that are not even in the gtdbtk.bac120.summary.tsv file. 
Is there a reason for that that I missed?
Also the gtdbtk.bac120.summary.tsv file provides a classification for all the 31MAGs but an ANI taxonomy for only 4 of them. I don't know if it's link together??

Thanks a lot for your help,
Ben

**Comment by dparks1134** [comment]
Hello,

ANI values are only calculated when a query genome is placed within a defined genus and are calculated for all reference genomes in the genus. You may find the documentation about the classification file useful:
https://github.com/Ecogenomics/GTDBTk#classification-summary-file

All your genomes should be in the gtdbtk.bac120.classify.tree or gtdbtk.ar122.classify.tree. Can you post the output log?

Cheers,
Donovan

**Comment by KunathBJ** [comment]
Hey Donovan,

Thanks a lot for the fast answer.

I've attached the log file as well as the stdout file.

Cheers,
Ben
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/2605608/gtdbtk.log)
[OAR_gtdb_stdout.txt](https://github.com/Ecogenomics/GTDBTk/files/2605609/OAR_gtdb_stdout.txt)

**Comment by dparks1134** [comment]
Hello. Everything seems in order. I'm unclear why you are looking for genomes that start with GB_* or SM23-28-2. You genomes will have names based on their input file names.

**Comment by KunathBJ** [comment]
Hey!

Well those are the IDs I find in the incomplete tree.
I find my genomes name in the gtdbtk.bac120.summary.tsv but not in the tree.
I've attached the tree and the summary

Thanks a lot,
Ben
[treeandsummary.zip](https://github.com/Ecogenomics/GTDBTk/files/2605746/treeandsummary.zip)

**Comment by dparks1134** [comment]
Hello. GTDB-Tk places your genome into a reference tree. All your genomes are in the tree along with the GTDB reference genomes. I verified this by opening the tree in a text editor and simply searching for your genome IDs.

**Comment by dparks1134** [comment]
I use Dendroscope and ARB for large trees and FigTree for small trees (<100 leaves).
