### ISSUE TITLE
Is the lasted GTDB database version220 missing files?

### ISSUE THREAD

**Issue by changhaozhou** [Ecogenomics/GTDBTk#590]
https://data.ace.uq.edu.au/public/gtdb/data/releases/release220/220.0/auxillary_files/gtdbtk_package/full_package/gtdbtk_r220_data.tar.gz

I downloaded the GTDB database version220 and decompressed them,but there were some folders missing, e.g. fastani

![image](https://github.com/Ecogenomics/GTDBTk/assets/52344522/bc726d99-bc51-4ecf-9713-1a720056bab5)
![image](https://github.com/Ecogenomics/GTDBTk/assets/52344522/9f6f6075-7e59-4dc0-a083-897a93afde20)

**Comment by pchaumeil** [comment]
Hello,
`FastANI` has been replaced by `skani` as the primary tool for computing Average Nucleotide Identity (ANI). the `fastani` folder has been rename to `skani`

Regards,
Pierre

**Comment by changhaozhou** [comment]
> Hello, <img alt="Screenshot 2024-05-28 at 15 42 47" width="583" src="https://private-user-images.githubusercontent.com/137225810/334459994-d78275e8-969a-4be2-8974-5c4e13239b33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDM2MTUsIm5iZiI6MTcxNjk0MzMxNSwicGF0aCI6Ii8xMzcyMjU4MTAvMzM0NDU5OTk0LWQ3ODI3NWU4LTk2OWEtNGJlMi04OTc0LTVjNGUxMzIzOWIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwMDQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzZiYThhNTA4MmFiMTE5MTVhZTQ4OGE5Yzk5NzVmZGY0NDM0MGMzNTJjNGQ2NGIzMjY0NjMxN2NkM2EyNTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.li_jArLwgEAodSHyXqXP9o5UnxPhE9zawKJrwOZ21IQ"> <img alt="Screenshot 2024-05-28 at 15 42 35" width="1024" src="https://private-user-images.githubusercontent.com/137225810/334459996-3019a4e0-c6dc-48f7-affd-f74f7f9dd5f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDM2MTUsIm5iZiI6MTcxNjk0MzMxNSwicGF0aCI6Ii8xMzcyMjU4MTAvMzM0NDU5OTk2LTMwMTlhNGUwLWM2ZGMtNDhmNy1hZmZkLWY3NGY3ZjlkZDVmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwMDQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDc2OTU0ZmM1NWFjYzRhY2E4YjU0MmIwYzg1ZjU5Y2E4YTI2MjA5OTI5MWExODc5M2E4NjUxZTFlM2YwYWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I_zviU3NGM9hovdgm8nKwYavT3MP0ifDaegUlOm6r00"> i got the same issue as you can see from the sceenshots. As you mentioned, i found the genome_path.tsv in skani folder, in this case, how can I avoid this error to run GTDB successfully?
> 
> many thanks for your time and looking forward to your reply.

GTDB database v220 needs gtdbtk v2.4.0, so maybe you should install the lastest version of gtdbtk.
![image](https://github.com/Ecogenomics/GTDBTk/assets/52344522/08b2a26c-9077-40a2-b5e4-edadb2b57426)

**Comment by ZhufangWang** [comment]
Hi,

i updated the GTDBtk version to the lasted, and it is working well now. many thanks for your help.
