### ISSUE TITLE
No sequence results for archaea in the align folder of classify_wf

### ISSUE THREAD

**Issue by Liuhanlin22** [Ecogenomics/GTDBTk#593]
bin.ar53.summary.tsv and bin.bac120.summary.tsv are both in the classify folder, and the results are normal, but the align folder only has the results of the bacterial alignment sequence, and the results of the fungal alignment do not exist. I tried four libraries, all of which were like this. My input file was a dRep-filtered bin file. What caused this? I tested other people's data and it was normal, is there something wrong with my data. But why bin.ar53.summary.tsv is normal again, only the align file does not exist.
![28e859854baf6a37cf9d1534d134d9c](https://github.com/Ecogenomics/GTDBTk/assets/160989113/3ec66a59-d10c-4d98-be17-539600bd07f3)
![9dc355a7fe80239d42b1aa75c6d1379](https://github.com/Ecogenomics/GTDBTk/assets/160989113/46d74cf4-26cf-42f2-a21c-60df6c0300a3)

**Comment by pchaumeil** [comment]
Hello,
Please provide the commands you are running and the log files for all these commands.

Thanks,
Pierre

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
