### ISSUE TITLE
Check install showing Hash Mismatch even though database MD5 checks

### ISSUE THREAD

**Issue by ErikLHendrickson** [Ecogenomics/GTDBTk#594]
I have gone through
FAQ: https://ecogenomics.github.io/GTDBTk/faq.html
Issues: Ihttps://github.com/Ecogenomics/GTDBTk/issues
and have been unable to answer my question.

## Environment
conda list
# packages in environment at /usr/local/anaconda3/envs/GTDB:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h10d778d_5    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
capnproto                 1.0.2                heb0080b_1    conda-forge
dendropy                  4.6.1                    pypi_0    pypi
fasttree                  2.1.11               h7437bb3_3    bioconda
gsl                       2.7                  h93259b0_0    conda-forge
gtdbtk                    2.4.0                    pypi_0    pypi
libblas                   3.9.0           22_osx64_openblas    conda-forge
libcblas                  3.9.0           22_osx64_openblas    conda-forge
libcxx                    17.0.6               h88467a6_0    conda-forge
libexpat                  2.6.2                h73e2aa4_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libopenblas               0.3.27          openmp_hfef2a42_0    conda-forge
libsqlite                 3.45.3               h92b6c6a_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               18.1.5               h39e0ece_0    conda-forge
mash                      2.3                  hf785b45_2    bioconda
ncurses                   6.5                  h5846eda_0    conda-forge
numpy                     1.26.4                   pypi_0    pypi
openssl                   3.3.0                h87427d6_3    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.15                  pypi_0    pypi
python                    3.11.9          h657bba9_0_cpython    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
skani                     0.2.1                h85dcccf_0    bioconda
tk                        8.6.13               h1abcd95_1    conda-forge
tqdm                      4.66.4                   pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge

conda list --revisions
2024-05-21 12:49:38  (rev 0)
    +bzip2-1.0.8 (conda-forge/osx-64)
    +ca-certificates-2024.2.2 (conda-forge/osx-64)
    +libexpat-2.6.2 (conda-forge/osx-64)
    +libffi-3.4.2 (conda-forge/osx-64)
    +libsqlite-3.45.3 (conda-forge/osx-64)
    +libzlib-1.2.13 (conda-forge/osx-64)
    +ncurses-6.5 (conda-forge/osx-64)
    +openssl-3.3.0 (conda-forge/osx-64)
    +pip-24.0 (conda-forge/noarch)
    +python-3.11.9 (conda-forge/osx-64)
    +readline-8.2 (conda-forge/osx-64)
    +setuptools-69.5.1 (conda-forge/noarch)
    +tk-8.6.13 (conda-forge/osx-64)
    +tzdata-2024a (conda-forge/noarch)
    +wheel-0.43.0 (conda-forge/noarch)
    +xz-5.2.6 (conda-forge/osx-64)

2024-05-24 11:15:58  (rev 1)
     openssl  {3.3.0 (conda-forge/osx-64) -> 3.3.0 (conda-forge/osx-64)}
    +fasttree-2.1.11 (bioconda/osx-64)
    +llvm-openmp-18.1.5 (conda-forge/osx-64)

2024-05-24 12:19:58  (rev 2)
    +capnproto-1.0.2 (conda-forge/osx-64)
    +gsl-2.7 (conda-forge/osx-64)
    +libblas-3.9.0 (conda-forge/osx-64)
    +libcblas-3.9.0 (conda-forge/osx-64)
    +libcxx-17.0.6 (conda-forge/osx-64)
    +libgfortran-5.0.0 (conda-forge/osx-64)
    +libgfortran5-13.2.0 (conda-forge/osx-64)
    +libopenblas-0.3.27 (conda-forge/osx-64)
    +mash-2.3 (bioconda/osx-64)
    +zlib-1.2.13 (conda-forge/osx-64)

2024-05-24 12:49:07  (rev 3)
    +skani-0.2.1 (bioconda/osx-64)

## Server information
- CPU: 3.3 GHz 12-Core Intel Xeon W
- RAM: 96 GB 2933 MHz DDR4
- OS: Sonoma 14.5

## Debugging information
export GTDBTK_DATA_PATH=/Volumes/Promise_Beast/Databases/GTdatabase/release220/

GTDBTK check_install

## are the important bits. As far as I can tell

2024-06-11 14:22:09] INFO:          |-- FastTree         OK
[2024-06-11 14:22:09] INFO:          |-- FastTreeMP       OK
[2024-06-11 14:22:09] INFO:          |-- guppy            OK
[2024-06-11 14:22:09] INFO:          |-- hmmalign         OK
[2024-06-11 14:22:09] INFO:          |-- hmmsearch        OK
[2024-06-11 14:22:09] INFO:          |-- mash             OK
[2024-06-11 14:22:09] INFO:          |-- pplacer          OK
[2024-06-11 14:22:09] INFO:          |-- prodigal         OK
[2024-06-11 14:22:09] INFO:          |-- skani            OK

[/Volumes/Promise_Beast/Databases/GTdatabase/release220/pplacer/] - 10/11 files                                                                                 [2024-06-11 14:22:13] INFO:          |-- pplacer          HASH MISMATCH f8915ef716c2554ae9875ef86e2d0b1be04926f9

[/Volumes/Promise_Beast/Databases/GTdatabase/release220/markers/] - 184/185 file                                                                                [2024-06-11 14:22:15] INFO:          |-- markers          HASH MISMATCH 99c03d04c576f682ab9064995ab76d876bf78074

[/Volumes/Promise_Beast/Databases/GTdatabase/release220/skani/] - 114007/114008                                                                                 [2024-06-11 14:49:50] INFO:          |-- skani            HASH MISMATCH 9c78950636ea40500d80d3f937031dd43ad5e663

[2024-06-11 14:49:50] ERROR: Unexpected files were seen, or the reference package is corrupt.
[2024-06-11 14:49:50] ERROR: Controlled exit resulting from an unrecoverable error or warning.

## Additional comments
       After seeing this the first time I removed the database, downloaded it again, and checked the MD5, which matched. 
      I still get the same errors. I tried to see whether there were extra files in the skani folder. I found all 114008 files, and no more. I matched the file paths and names listed in genome_paths.tsv and these all matched the files in the skani folder, with no extras. 
     I am not sure how to proceed from here.  Any help would be appreciated.

**Comment by pchaumeil** [comment]
Hello,
Do you still have an issue when downloading the reference package?

Regards,
Pierre

**Comment by ErikLHendrickson** [comment]
Pierre,
      Thank you for responding to my inquiry.
      I do not think that it was an issue with downloading the database. The database seemed to download just fine and the md5 matched. In addition, I tried a completely separate installation of an earlier version of GTDB-TK which used an earlier version of the database. That seemed to download just fine and the md5 matched. However, it gave me basically the same 3 hash mismatches as the other install. Ok, as an earlier version it used fastani and I got a fastani mismatch instead of what the newer version uses. But really, it was the same three errors despite being a different version of GTDB-TK and a different database.
      Thus, it seems to be something very fundamentally wrong. So, we have simply abandoned trying to get GTDB-TK running on this machine.

regards,
Erik
________________________________

**Comment by pchaumeil** [comment]
Hi Erik,
Thanks for the reply, Could be an issue with Hash Mishmatch in Sonoma ( GTDB-Tk was not implemented to run on MacOs).
Hopefully you have managed to install it successfully on an other machine. 

I will close the ticket for now, as we do not have extra information to solve this issue.

Cheers,
Pierre
