### ISSUE TITLE
Using classify_wf with low completeness genomes

### ISSUE THREAD

**Issue by lingrongjin** [Ecogenomics/GTDBTk#597]
I have a couple hundreds of single amplified genomes from single cell assemblies which have low completeness (completeness <50%). I saw that it is not recommended to use classify_wf for genomes with low completeness as “results can be impacted by a lack of marker genes or contamination”. However, my project goal is to study phage-host association in single cells so I want to capture as much host diversity as possible. I’m wondering if there is a way to get reliable taxonomic classifications for genomes with low completeness; for example, is it possible to include all low completeness genomes in the initial classify_wf process and then manually curate the reliable classifications based on presence/absence of marker genes? (for contamination part, I will only use genomes with < 10% contamination).  Thanks for the help!

**Comment by pchaumeil** [comment]
Hello,
We do not recommend running GTDB-Tk with low completeness genomes. We can not confirm with confidence the placement of user genomes in the reference tree if most of the markers are missing.

One workaround solution to get a more reliable taxonomy is to create de novo trees based on individual markers present across your low completeness genomes ( i.e if all your genomes have the marker TIGR00959, you can create a tree based on this marker , and you can also include GTDB representatives)
