### ISSUE TITLE
Difference between fastani_ani and closest_placement_ani

### ISSUE THREAD

**Issue by saras224** [Ecogenomics/GTDBTk#602]
Hi @donovan-h-parks 

I have gtdbtk.bac120.summary.tsv file for the MAGs, the file has two columns for ani; one is fastani_ani and the other is closest_placement_ani. Why are there two columns for ANI and which one to consider fastani or closest placement?. The ones which have the ani values in fastani_ani have NA as values in the closest_placement_ani column and vice-versa. And same is happening for the Reference genomes. 

Thanks in Advance
Saraswati

**Comment by pchaumeil** [comment]
Hi,
This question has been answered in #599
