### ISSUE TITLE
How can we construct a phylogenetic tree that includes both bacteria and archaea?

### ISSUE THREAD

**Issue by qbdong122** [Ecogenomics/GTDBTk#605]
GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum:

GTDB forum:
https://forum.gtdb.ecogenomic.org/

**Comment by pchaumeil** [comment]
Hello,
Please have a look at this closed issue #473

**Comment by qbdong122** [comment]
> Hello, Please have a look at this closed issue #473

Thank you. I'll try it
