### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by jianshu93** [Ecogenomics/GTDBTk#609]
Dear GTDB team,

This is not for GTDB-tk but for GTDB database website. However, there are no responses on the website so I came to this channel for help. The issue mentioned here: https://forum.gtdb.ecogenomic.org/t/release220-wrong-md5hashes/669

is critical for some other program. It would be nice if  the team can update the database files for v220. 

Thanks,
Jianshu

**Comment by pchaumeil** [comment]
Hello,
Thanks for the feedback!

The MD5SUM.txt file has now been updated.

Thanks,
Pierre
