### ISSUE TITLE
NCBI Taxonomy Names in output

### ISSUE THREAD

**Issue by elizabethmcd** [Ecogenomics/GTDBTk#61]
Thanks for the great tool! This suggestion is definitely not critical, but something I think could be useful. I definitely like that on the GTDB website you can search for certain taxa, and it gives the NCBI taxonomy alongside the GTDB taxonomy. For genome sets less than ~50 taxa that I've run through GTDB-tk I've made a metadata file with the GTDB taxonomy and what the NCBI taxonomy is, since for certain taxa the new nomenclature is a little confusing without knowing what changed (e.g. Deltaproteobacteria is now split into multiple phyla). I was wondering if it was possible to either include in the output classification tsv the corresponding NCBI taxonomy, or if there is a more high-throughput way to query the database that is shown on the web-front.

**Comment by cheberling** [comment]
In the short-term something that I've been doing is using the bacterial genome metadata file, available on GTDB's downloads webpage.  You can use the NCBI accession reference to the nearest ANI relative in the GTDB-tk results file to retrieve the NCBI classification from the metadata file.

But I agree, it would be useful to get this information by default in the results file as well without having to do extra manipulation.  Both the full strain name of the genome and the taxonomic lineage to species level would be useful, just as is reported on the website.

**Comment by alienzj** [comment]
Hi, all.
I wrote a command line tool [gtdb2ncbi](https://github.com/alienzj/gtdb2ncbi) which convert taxonomy system from GTDB to NCBI.
Maybe you can try it.

**Comment by elizabethmcd** [comment]
Wow, thanks! Will give this a try.

**Comment by dparks1134** [comment]
Hi alienzj,

Thank you for putting gtdb2ncbi together. Is there an explanation of how it works? There isn't a 1:1 relationship between GTDB and NCBI taxa so it would be nice to inform users of any caveats that may exist. We have provided a script gtdb_to_ncbi_majority_vote.py that uses a majority voting scheme to determine the most common translation between these two taxonomies. We are not officially supporting this script at the moment though and we recommend any results be manually verified.

https://github.com/Ecogenomics/GTDBTk/blob/stable/scripts/gtdb_to_ncbi_majority_vote.py

Cheers,
Donovan

**Comment by alienzj** [comment]
Just a dict contains key and value, key is a single level classification tag from each GTDB taxonomy lineages, value is a single level classification tag from each NCBI taxonomy lineages.

The dict was generated from [ncbi_vs_gtdb_r89_archaea](https://data.ace.uq.edu.au/public/gtdbtk/release_89/89.0/ncbi_vs_gtdb_r89_archaea.xlsx) and [ncbi_vs_gtdb_r89_bacteria](https://data.ace.uq.edu.au/public/gtdbtk/release_89/89.0/ncbi_vs_gtdb_r89_bacteria.xlsx).

As you reminded, there exists many duplicate key map to different value.

The logic:

Firstly insert key which firstly appear in the two excel file which was orderd by genomes numbers.

Then if the key appear again and have bigger percentage value(%), replace it, same key, different value.

Finally, input GTDB classification, replace it from seven taxonomy level using the dict.

**Comment by dparks1134** [comment]
Hi. Thanks for the clarification. It would be great if this was explained on the GitHub page just to make it clear that there isn't a 1:1 mapping between the two taxonomies and that a majority voting type scheme is used to obtain a 1:1 mapping.

**Comment by alienzj** [comment]
Hi. Thanks for the advice. I will update the documentation.

**Comment by shubavarshini** [comment]
Hi. There is metadata file (https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/bac120_metadata_r89.tsv) that will help you associate gtdb_taxonomy to ncbi_taxonomy. It has everything concerned with either of the databases.

**Comment by cristinamunoz** [comment]
> Hi. There is metadata file (https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/bac120_metadata_r89.tsv) that will help you associate gtdb_taxonomy to ncbi_taxonomy. It has everything concerned with either of the databases.

Hi shubavarshini. Thank you so much for this metadata file. It helps me a lot.
