### ISSUE TITLE
Contigs taxonomy classification

### ISSUE THREAD

**Issue by UniAlberta** [Ecogenomics/GTDBTk#614]
GitHub issues are specifically for issues with the GTDB-Tk, please join us on the GTDB forum:

GTDB forum:
https://forum.gtdb.ecogenomic.org/
Hi there, can I use use gtdbtk classify_wf for the taxonomic classification of my contigs (not MAGs)?

Nafsa

**Comment by donovan-h-parks** [comment]
Hi Nafsa. No GTDB-Tk requires the input to be a genome (MAG, SAG, or isolate).
