### ISSUE TITLE
Segmentation Fault during Pfam Search

### ISSUE THREAD

**Issue by kvnforsberg** [Ecogenomics/GTDBTk#62]
Hello,

I've encountered a segmentation fault when running release 86 of the "classify_wf" workflow, specifically at the 'Identifying Pfam protein families' step. I've attached a log file with the stderr output associated with the failed run. I've also copied the 'editable' portion of the config.py file associated with the install (see below). Any help resolving this issue would be appreciated. The workflow makes it through prodigal gene-calling and tigrfam annotations without issue, so I suspect that the dependencies are appropriately installed and that the config file isn't wildly incorrect. 

Thanks very much,

Kevin

config.py file:

############################
# EDIT FROM HERE
############################

# Path to MSA and Taxonomy
GENERIC_PATH = "/path/to/localCopy/ofGTDB_release86/"

############################
# If all downloaded data is in the same folder
# There is no need of editing variable below this point
############################

TIGRFAM_HMMS = GENERIC_PATH + 'markers/tigrfam/tigrfam.hmm'
PFAM_HMM_DIR = GENERIC_PATH + 'markers/pfam/'
MSA_FOLDER = GENERIC_PATH + "msa/"
MASK_DIR = GENERIC_PATH + "masks/"
PPLACER_DIR = GENERIC_PATH + "pplacer/"
FASTANI_DIR = GENERIC_PATH + "fastani/"
TAX_FOLDER = GENERIC_PATH + "taxonomy/"

############################
# STOP EDIT
############################

[GTDB_log.txt](https://github.com/Ecogenomics/GTDBTk/files/2692641/GTDB_log.txt)

**Comment by dparks1134** [comment]
Hello. The issue is likely associated with the Perl dependencies and the pfam_search. pl script. Can you see if you can run this script independently of GTDB-Tk? You can download the script for the following URL or find it on your system:
https://github.com/Ecogenomics/GTDBTk/blob/master/gtdbtk/external/pfam_search.pl

**Comment by kvnforsberg** [comment]
Thanks for the quick reply.

Indeed, I am unable to run the pfam_search.pl from my system (located at: lib/python2.7/site-packages/gtdbtk-0.1.3-py2.7.egg/gtdbtk/external/pfam_search.pl). When I attempt to run it without passing it any arguments, I recreate the same "Segmentation fault (core dumped)" error that we see in my initial log file. Any insight on what I can do to remedy the problem?

**Comment by dparks1134** [comment]
Hello. Not sure what to suggest. Usually issues with the pfam_search.pl have to do with proper installation of the Perl dependencies, but this doesn't result in a segmentation fault. This script call hmmsearch, but this is also used to identify TIGRfams so this is clearly working on your system. Can you run perl?

**Comment by kvnforsberg** [comment]
Thanks for the suggestion, I think you are onto something with the perl dependency idea, I can get the script to run in a different environment, which uses a different perl build. I'll update when I know more.

**Comment by kvnforsberg** [comment]
Hello, an update:

The issue was indeed perl. I was running gtdbtk from a secondary environment, but there were shared library files that perl was accessing from my native environment which contributed to the problem. I'm still not solid on the exact nature of the issue, but if I unset my PERL5LIB before running gtdbtk, I see no issues.

Thanks for helping me hone in on perl/pfam_search.pl.

**Comment by dparks1134** [comment]
Glad the problem could be resolved. We plan to re-write the pfam_search.pl script in Python when time allows.
