### ISSUE TITLE
gtdbtk classify_wf many 'none'

### ISSUE THREAD

**Issue by Sofie8** [Ecogenomics/GTDBTk#63]
Thanks for this great tool Donovan and the efforts to develop this further.

I ran gtdbtk classify_wf on 60 MAGS, but I had only 5 given a closest reference, ANI and tree placement, the rest 'none'.
I checked the gtdbtk_bac120_markers_summary.tsv file, and those that were classified had either 120/120 unique markers, or up to 105/120. These were also the highest quality bins, completeness (> 90 %, contamination < 5 %). From the others on, like completeness in the 70-80% and contamination < 5 %, and around 80/120 markers found, there is a classification till genus, and no species -s_, and the table is filled with none.
So, the higher quality MAGs of course the better, but it means that those MAGs of 80 % completeness, I can't classify? Does 'none' means no fastANI comparison or classification possible, or 'novel'? The MAGs belong to the genus Nitrospira.

Thanks!

**Comment by dparks1134** [comment]
Hello,

Do the 55 genomes without a `fastani_reference` have a genus classification? 

Cheers,
Donovan

**Comment by Sofie8** [comment]
Hi,

Yes most of them do have genus identification. In attachment the summary file, and summary markers file for bacteria.

[gtdbtk.bac120.summary.zip](https://github.com/Ecogenomics/GTDBTk/files/2734690/gtdbtk.bac120.summary.zip)

[gtdbtk_bac120_markers_summary.zip](https://github.com/Ecogenomics/GTDBTk/files/2734695/gtdbtk_bac120_markers_summary.zip)

**Comment by dparks1134** [comment]
Hello,

A 'none' in these cases indicates there is no reference genome with an ANI >= 95%. We plan to change this in the next release so that the closest reference genome is reported whenever a genome can be assigned to a specific genus based on its placement in the reference tree.

Cheers,
Donovan

**Comment by Sofie8** [comment]
Hello,

Ok clear, sounds good to have a placement in the tree, this is based on the 120 taxonomic markers? 
Related to this: which bin quality (completeness, contamination) is according to you still classifiable, cause I have bins of 50 % completeness assigned till genus level, is there some threshold of genome completeness below which ANI get so random that you can't trust it. gANI is sensitive to genome completeness, but ANIm less, which ANI is implemented in your tool?

Also, it surprises me that many Nitrospira's don't show higher ANI values with known genomes. It is compared to the 125,000 bacterial genomes in gtdb-tool right, cause I see Nitrospira well represented in the gdtb database. Other reason, I have only 80 % complete bins of Nitrospira, so ANI can't get higher than 95 %? But I would have sufficient taxonomic markers (at least 60 of the 120) to say something? My question, can I thus say that the Nitrospira bins are novel species (more correct ANI < 95 % similarity with other Nitrospira's in the 125,000 gtdb genomes)?

Thanks!
Sofie

**Comment by dparks1134** [comment]
Hello,

Placement in the reference tree is done using pplacer and a concatenated MSA of 120 bacterial or 122 archaeal proteins filtered and sampled to approximately 5000 amino acids. This keeps computational requirements within reason. We calculate ANI with FastANI which is robust to genome completeness. 

Genomes are only compared to the ~25,000 genomes in the reference tree which was dereplicated to contain 1 genome per species. A 80% complete genome can certainly have an ANI >=95%. It would seem your Nitrospira represent novel genomes. GTDB-Tk is still in development, contains a specific set of reference genomes, and bases ANI using a specific (and somewhat heuristic) method. I would encourage you to explore the issue further before declaring your genomes to be novel species if this will form a focal point on your research. You might find MiGA (http://enve-omics.ce.gatech.edu:3000/) helpful in this regard.

Cheers,
Donovan
