### ISSUE TITLE
Unrecognize bin error

### ISSUE THREAD

**Issue by Lcornet** [Ecogenomics/GTDBTk#64]
I run GTDBtk on a lichen metagenome and i have this error :

Uncaught exception: Failure("Sequence P1030.fasta.metabat-bins-_--veryspecific_-t_40.13 doesn't overlap any reference sequences.")
Fatal error: exception Failure("Sequence P1030.fasta.metabat-bins-_--veryspecific_-t_40.13 doesn't overlap any reference sequences.")
Uncaught exception: Sys_error("gtdbtk_output/pplacer/pplacer.bac120.json: No such file or directory")
Fatal error: exception Sys_error("gtdbtk_output/pplacer/pplacer.bac120.json: No such file or directory")

Si it crash, is it because some bins are Eukaryota ?

**Comment by dparks1134** [comment]
GTDB-Tk only works with archaeal and bacterial genomes, and results will only be meaningful for genomes of reasonable quality (i.e. relatively low contamination and reasonable completeness).
