### ISSUE TITLE
Combining archeal and bacterial trees

### ISSUE THREAD

**Issue by Balays** [Ecogenomics/GTDBTk#77]
Hello.
Is it possible to combine the two generated phylogenetic trees? Are you planning to include this? If not, can you give a tip on how to do that?
Thanks! Cheers.

**Comment by dparks1134** [comment]
Hello. The two trees are inferred independently using different marker genes. We plan to continue treating these domains separately for the foreseeable future.

**Comment by Balays** [comment]
I see. Thanks!

**Comment by nigiord** [comment]
> If not, can you give a tip on how to do that?

I had the same question. I guess you could do it easily using something like ETE toolkit in Python:

```python
import ete3

bac_tree = ete3.PhyloTree(
    "gtdbtk.bac120.classify.tree",
    format=1,
    quoted_node_names=True,
)

ar_tree = ete3.PhyloTree(
    "gtdbtk.ar122.classify.tree",
    format=1,
    quoted_node_names=True,
)

luca_tree = ete3.PhyloTree(name='LUCA')
luca_tree.add_child(bac_tree, dist=1)
luca_tree.add_child(ar_tree, dist=1)
```

Not sure if it makes sense and which `dist` parameter to use though... Any clue? The final goal would be to compute de pairwise phylogenetic distance matrix between the genomes.

−Nils

**Comment by magibc** [comment]
Hi @nigiord ,
I have the same problem because I would like to merge both trees in a single one in order to use after as phylogenetic tree in the phyloseq package.

Have you found some strategy to overcome this situation that you can share it?

thanks on advance,

Magi.
