### ISSUE TITLE
How to open the file <prefix>.classify.tree?

### ISSUE THREAD

**Issue by xuechunxu** [Ecogenomics/GTDBTk#79]
In the OUTPUT, I got two files, `gtdbtk.ar122.classify.tree` and `gtdbtk.bac120.classify.tree`. However, they can't be opened by Mega and ITOL.

How to open the two files?

**Comment by dparks1134** [comment]
Unfortunately the Newick format is not well defined. The format we use can be opened with Dendroscope or ARB, or read into Python using DendropPy.
