### ISSUE TITLE
AttributeError Namespace

### ISSUE THREAD

**Issue by KunathBJ** [Ecogenomics/GTDBTk#83]
Hello,

I've just installed the latest version of GTDBTk from conda (v0.1.5) amd I have issues that I can't figure out. It starts running normally but after Pfam it crashes
log:
INFO: Identifying markers in 107 genomes with 24 threads.
INFO: Running Prodigal to identify genes.
INFO: Identifying TIGRFAM protein families.
INFO: Identifying Pfam protein families.
INFO: Done.

Stderr:
```
Traceback (most recent call last):
  File "/home/users/bkunath/miniconda2/envs/gtdb/bin/gtdbtk", line 373, in <module>
    gt_parser.parse_options(args)
  File "/home/users/bkunath/miniconda2/envs/gtdb/lib/python2.7/site-packages/gtdbtk/main.py", line 348, in parse_options
    self.align(options)
  File "/home/users/bkunath/miniconda2/envs/gtdb/lib/python2.7/site-packages/gtdbtk/main.py", line 175, in align
    options.skip_gtdb_refs,
AttributeError: 'Namespace' object has no attribute 'skip_gtdb_refs
```

I'm not sure what the error means and can't fix it. Have you seen it before?

Thanks a lot,
Ben

**Comment by dparks1134** [comment]
Hello Ben. This is a bug with 0.1.5. The latest version if 0.1.6. We do not maintain the Condo installation and I'm having trouble determine who actually put this together. Hopefully they can update to 0.1.6.

**Comment by chloelulu** [comment]
Hi, @KunathBJ ,

May I know how you update the version by conda to v0.1.6? I met the same problem as you. 
Your help would be really appreciated!

**Comment by KunathBJ** [comment]
Hi @chloelulu, 
I didn't. I went back to "normal" installation.
But conda has now the 0.1.6 version since 5 hours! Lucky you ^^
I haven't tried it though

**Comment by chloelulu** [comment]
Thanks so much! @KunathBJ  I will try it soon.  Good luck with your research, too. haha
