### ISSUE TITLE
taxonomy classification result confusing

### ISSUE THREAD

**Issue by chloelulu** [Ecogenomics/GTDBTk#88]
Hi, developer,

I got the taxonomy classification of the genome bins in gtdbtk. But the assignment result seems wrong. As described below. The classification are like this. 
`d__Archaea;p__Halobacterota;c__Methanomicrobia;o__Methanomicrobiales;f__Methanocullaceae;g__Methanoculleus;s__GCA_001896715.1 `
`d__Archaea;p__Euryarchaeota;c__Methanobacteria;o__Methanobacteriales;f__Methanobacteriaceae;g__UBA419;s__GCA_002494495.1`
From my understanding, `Halobacterota` should be `Euryarchaeota`. May I know is this the problem of the reference database ? 
Thanks so much!

**Comment by dparks1134** [comment]
GTDB-Tk is based on the GTDB taxonomy (http://gtdb.ecogenomic.org/) where Halobacterota is an archaeal phylum.

**Comment by chloelulu** [comment]
@dparks1134     Appreciate for your quick response. I see it. Since I always use Euryarchaeota as the phylum. Just my naive, First time see it. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
