### ISSUE TITLE
#!/home/user_name/.... at beginning of  gtdbtk

### ISSUE THREAD

**Issue by sipesk** [Ecogenomics/GTDBTk#95]
Hello,

What is the path that is suppose to go in the #!/home/../../ line at the beginning of the gtdbtk program file. 

The file is found in home/python/bin.

Also. 
Most of the dependencies need python 3.7, while gtdbtk wants 2.7, how does one satisfy all the programs?

Thanks,
Katie Sipes

**Comment by pchaumeil** [comment]
Hello Katie,
Apologise for the late answer.
Have you managed to get GTDB-Tk running properly?

Regards,
Pierre

**Comment by sipesk** [comment]
Yes,

Thank you. Will there be an update for GTDB-Tk to use python 3.5 in the near future?

Katie Sipes

On Mar 22, 2019, at 07:12, Pierre Chaumeil <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Katie,
Apologise for the late answer.
Have you managed to get GTDB-Tk running properly?

Regards,
Pierre

**Comment by pchaumeil** [comment]
Hello,
We have put a migration to Python 3 on our to-do list but there is no timeline for this yet.

Cheers,
Pierre.
