### ISSUE TITLE
Unrecognized arguments --outgroup_taxa

### ISSUE THREAD

**Issue by carolinelil** [Ecogenomics/GTDBTk#98]
When running

`gtdbtk de_novo_wf --cpus 20 --genome_dir test_delmont --ar122_ms --outgroup_taxon p__Archaea --extension fa --out_dir novo_test_out
`

I get

```
usage: gtdbtk [-f]
              {de_novo_wf,classify_wf,identify,align,infer,classify,root,decorate,trim_msa,check_install}
              ...
gtdbtk: error: unrecognized arguments: --outgroup_taxon p__Archaea
```

This also goes when I change the outgroup_taxon to e.g. p__Planctomycetota. Any ideas what could have gone wrong?

**Comment by pchaumeil** [comment]
Hello,
Thanks for your Email.
This issue will be fixed in the next version of GTDB-Tk available in a few days.

Regards,
Pierre

**Comment by carolinelil** [comment]
Hello,

Thank you for your response. When will the next version of GTDB-Tk be available?

Best regards,
Caroline

**Comment by pchaumeil** [comment]
Hi Caroline,
The new version should be released later this week.
Cheers,
Pierre

**Comment by Gee-Lau** [comment]
Hi Pierre, 

Just saw the new version. Thanks!

Shouldn't the command for downloading for GTDB-Tk external data be:
wget https://data.ace.uq.edu.au/public/gtdbtk/release_86/gtdbtk.r86_v2_data.tar.gz ?

Regards,
G

**Comment by pchaumeil** [comment]
Hello,
You are correct, thanks for the heads up!
I have updated the README page.

Regards,
Pierre
