### ISSUE TITLE
Unnecessary failure

### ISSUE THREAD

**Issue by tnn111** [Ecogenomics/GTDBTk#99]
Suggestion: Don't make not being able to find any matches to a reference sequence in a bin a fatal error. Flag it, but please don't die.

Uncaught exception: Failure("Sequence bin.75 doesn't overlap any reference sequences.")
Fatal error: exception Failure("Sequence bin.75 doesn't overlap any reference sequences.")
Uncaught exception: Sys_error("gtdbtk_output/pplacer/pplacer.bac120.json: No such file or directory")
Fatal error: exception Sys_error("gtdbtk_output/pplacer/pplacer.bac120.json: No such file or directory")

**Comment by dparks1134** [comment]
This failure happens within pplacer so we can't stop it from occurring. The default parameters for the next release of GTDB-Tk will be set to ensure any genome that is processed does have some overlap with the reference sequences. You can set this yourself for now (see --min_perc_aa).

**Comment by Handymanalan** [comment]
Hi Donovan,

I have installed the latest version but I still have the same problem with pplacer.

Here's my script:
gtdbtk classify_wf --cpus 8 -x fa --genome_dir path --out_dir path --min_perc_aa 0

But I still have this error:

IOError: [Errno 2] No such file or directory: '/srv/scratch/z3336178/gtdbThesis/output/gtdbtk.bac120.classify.tree'

Cheers
Alan

**Comment by pchaumeil** [comment]
Hello Alan,
This is probably caused by pplacer running out of memory. 
GTDB-Tk should report this memory issue in the pplacer.<bac120/ar122>.out file or in the the error log file of the queuing system (if the tool is run on HPC).
A machine with over 128 Gb might be required (say 160 GB or so).
Regards,
Pierre

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity
